# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

from ..utils import MAX_GRID_SIZE_X

logger = logging.getLogger("flag_gems").getChild(__name__.lstrip("."))


@triton.jit
def sinh_kernel_(x_ptr, n_elements, BLOCK_SIZE: tl.constexpr, M: tl.constexpr):
    grid_0 = tl.num_programs(0)
    pid = tl.program_id(0)
    while pid < M:
        block_start = pid * BLOCK_SIZE
        offsets = block_start + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements

        x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
        x_f32 = x.to(tl.float32)
        y = 0.5 * (tl.exp(x_f32) - tl.exp(-x_f32))
        y_cast = y.to(x.dtype)
        tl.store(x_ptr + offsets, y_cast, mask=mask)
        pid += grid_0


def sinh_(*args, **kwargs):
    logger.debug("GEMS_CAMBRICON SINH_")
    # Accept various calling conventions: sinh_(tensor), sinh_(self=tensor), sinh_(input=tensor)
    x = None
    if args:
        x = args[0]
    else:
        x = kwargs.get("self", kwargs.get("input", None))
    if x is None:
        raise TypeError("sinh_ expected a Tensor as the first argument")

    if not isinstance(x, torch.Tensor):
        raise TypeError("sinh_ expected a torch.Tensor")

    if x.numel() == 0:
        return x

    if not x.is_contiguous():
        raise RuntimeError(
            "sinh_ Triton kernel currently supports only contiguous tensors"
        )

    supported_dtypes = (torch.float16, torch.float32, torch.bfloat16)
    if x.dtype not in supported_dtypes:
        raise RuntimeError(
            f"sinh_ Triton kernel supports dtypes {supported_dtypes}, but got {x.dtype}"
        )

    n_elements = x.numel()
    BLOCK_SIZE = 1024
    M = triton.cdiv(n_elements, BLOCK_SIZE)
    grid = min(M, MAX_GRID_SIZE_X // 4)

    with torch_device_fn.device(x.device):
        sinh_kernel_[(grid,)](x, n_elements, BLOCK_SIZE=BLOCK_SIZE, M=M)
    return x
