#!/bin/bash

OP_NAME=$1
VERSION=$2

if [ -z "$OP_NAME" ] || [ -z "$VERSION" ]; then
    echo "❌ Usage: bash run_bench.sh <op_name> <version_label>"
    exit 1
fi

DATE=$(date +%Y%m%d)
EXP_DIR="experiments/${OP_NAME}/${DATE}_${VERSION}"
mkdir -p "$EXP_DIR"

echo "🚀 Running benchmark for ${OP_NAME}..."

# 1. 运行测试。我们加上 --log-dir . 强制它在当前执行目录生成
pytest benchmark/test_unary_pointwise_perf.py -k "${OP_NAME}" --record log

# 2. 智能寻找生成的 log 文件
# 搜索当前目录下最近 1 分钟内生成的以 result_ 开头的 .log 文件
LOG_FILE=$(find . -maxdepth 3 -name "result_*.log" -mmin -1 | head -n 1)

if [ -f "$LOG_FILE" ]; then
    mv "$LOG_FILE" "${EXP_DIR}/result.log"
    echo "✅ Success! Result saved to: ${EXP_DIR}/result.log"
else
    echo "❌ Error: No log file generated by pytest."
    echo "请检查 benchmark 脚本是否支持 --record 参数，或手动确认 log 文件名。"
    exit 1
fi