# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Accuracy tests for ``aten::slow_conv_transpose3d``.

The operator applies a 3D transposed convolution with the transposed-conv
weight layout ``(C_in, C_out, kD, kH, kW)``.  3D volumes grow cubically with the
output size, so the shapes below stay deliberately small: a single 3D output
plane already holds thousands of elements, which is enough to cover the
boundary masks, the stride/dilation remainder logic and the channel tiling
without making the reference (CPU/CUDA ``aten::slow_conv_transpose3d``) and the
Triton kernel expensive.
"""

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# (input_shape, weight_shape) pairs, weight is (C_in, C_out, kD, kH, kW).
# Input volumes are kept at D=8, H=16, W=16 or smaller: 3D conv outputs scale
# as D*H*W*kD*kH*kW*C_in*C_out, and larger volumes push the slow reference
# kernel into seconds per case.
SHAPES_AND_WEIGHTS = [
    ((2, 4, 8, 16, 16), (4, 8, 3, 3, 3)),
    ((1, 8, 6, 8, 8), (8, 4, 2, 2, 2)),
]
# Stride/padding combinations in both accepted forms: a scalar int (which the
# operator broadcasts to all three spatial dims) and an explicit 3-triple.
STRIDE_PADDING = [
    (1, 0),
    (2, 0),
    ((2, 1, 1), (1, 0, 2)),
    ((1, 2, 3), (2, 2, 1)),
]


def _triple(value):
    if isinstance(value, int):
        return [value, value, value]
    return list(value)


def _atol(dtype):
    # fp16/bf16 accumulate in fp32 through the tensor-core path while the
    # reference computes in the storage dtype, so the low-precision cases need a
    # looser absolute tolerance than the fp32 default.
    return 2e-2 if dtype in (torch.float16, torch.bfloat16) else 1e-4


@pytest.mark.slow_conv_transpose3d
@pytest.mark.parametrize("shape, weight_shape", SHAPES_AND_WEIGHTS)
@pytest.mark.parametrize("stride, padding", STRIDE_PADDING)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_slow_conv_transpose3d(shape, weight_shape, stride, padding, dtype):
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    weight = torch.randn(weight_shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp, True)
    ref_weight = utils.to_reference(weight, True)

    kernel_size = [weight_shape[2], weight_shape[3], weight_shape[4]]
    st = _triple(stride)
    pa = _triple(padding)

    ref_out = torch.ops.aten.slow_conv_transpose3d(
        ref_inp, ref_weight, kernel_size, None, st, pa, [0, 0, 0], [1, 1, 1]
    )
    res_out = flag_gems.slow_conv_transpose3d(
        inp, weight, kernel_size, None, st, pa, [0, 0, 0], [1, 1, 1]
    )
    utils.gems_assert_close(res_out, ref_out, dtype, atol=_atol(dtype))


@pytest.mark.slow_conv_transpose3d
@pytest.mark.parametrize("shape, weight_shape", SHAPES_AND_WEIGHTS)
@pytest.mark.parametrize("stride, padding", STRIDE_PADDING)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_slow_conv_transpose3d_bias(shape, weight_shape, stride, padding, dtype):
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    weight = torch.randn(weight_shape, dtype=dtype, device=flag_gems.device)
    bias = torch.randn(weight_shape[1], dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp, True)
    ref_weight = utils.to_reference(weight, True)
    ref_bias = utils.to_reference(bias, True)

    kernel_size = [weight_shape[2], weight_shape[3], weight_shape[4]]
    st = _triple(stride)
    pa = _triple(padding)

    ref_out = torch.ops.aten.slow_conv_transpose3d(
        ref_inp, ref_weight, kernel_size, ref_bias, st, pa, [0, 0, 0], [1, 1, 1]
    )
    res_out = flag_gems.slow_conv_transpose3d(
        inp, weight, kernel_size, bias, st, pa, [0, 0, 0], [1, 1, 1]
    )
    utils.gems_assert_close(res_out, ref_out, dtype, atol=_atol(dtype))


@pytest.mark.slow_conv_transpose3d
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_slow_conv_transpose3d_output_padding_dilation(dtype):
    """Non-trivial output padding and dilation exercise the size formula."""
    # A small 4x6x6 input keeps this extra case cheap on top of the main grid.
    shape = (1, 2, 4, 6, 6)
    weight_shape = (2, 3, 2, 2, 2)
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    weight = torch.randn(weight_shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp, True)
    ref_weight = utils.to_reference(weight, True)

    kernel_size = [2, 2, 2]
    stride = [2, 2, 2]
    padding = [0, 1, 1]
    output_padding = [1, 1, 0]
    dilation = [2, 2, 2]

    ref_out = torch.ops.aten.slow_conv_transpose3d(
        ref_inp,
        ref_weight,
        kernel_size,
        None,
        stride,
        padding,
        output_padding,
        dilation,
    )
    res_out = flag_gems.slow_conv_transpose3d(
        inp, weight, kernel_size, None, stride, padding, output_padding, dilation
    )

    utils.gems_assert_close(res_out, ref_out, dtype, atol=_atol(dtype))


@pytest.mark.slow_conv_transpose3d
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_slow_conv_transpose3d_scalar_stride(dtype):
    """Scalar int stride/padding are broadcast across all three spatial dims."""
    # Odd-sized volume (1, 3, 5, 7, 9): exercises the int-broadcast path where
    # the reference API needs explicit triples but the wrapper takes scalars.
    shape = (1, 3, 5, 7, 9)
    weight_shape = (3, 4, 3, 3, 3)
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    weight = torch.randn(weight_shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp, True)
    ref_weight = utils.to_reference(weight, True)

    ref_out = torch.ops.aten.slow_conv_transpose3d(
        ref_inp, ref_weight, [3, 3, 3], None, [2, 2, 2], [1, 1, 1], [0, 0, 0], [1, 1, 1]
    )
    res_out = flag_gems.slow_conv_transpose3d(
        inp, weight, 3, None, stride=2, padding=1, output_padding=0, dilation=1
    )
    utils.gems_assert_close(res_out, ref_out, dtype, atol=_atol(dtype))
