# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Accuracy tests for ``aten::mH`` (the conjugate-transpose view).

``mH`` is a pure metadata/view operator: it swaps the last two dimensions and
toggles the lazy conjugate bit for complex dtypes, without touching any
element.  The checks therefore focus on the view contract rather than values:
shape, strides, shared storage, the ``is_conj()`` lazy bit, rank handling
(1-D rejected, 0-D deprecated warn + conj path) and non-contiguous/batched
inputs.  The reference is ``Tensor.mH`` (``aten::mH``), which is a
CompositeImplicitAutograd view valid on both CPU and CUDA for every dtype.
"""

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# mH is defined for matrices and batches of matrices; every shape here has
# ndim >= 2 except the dedicated 0-D/1-D rank tests below.
MH_SHAPES = [
    (4, 6),
    (64, 128),
    (2, 3, 8, 16),
    (5, 4, 7),
    (3, 1, 0, 9),  # batched with a zero-sized matrix
]


@pytest.mark.mH
@pytest.mark.parametrize("shape", MH_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_mH(shape, dtype):
    # mH for real dtypes is exactly transpose(-2, -1): a stride exchange view.
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = ref_inp.mH
    # Call the wrapper directly (no dispatch): mH is a zero-copy view, so its
    # contract must be observed on the FlagGems implementation itself.
    res_out = flag_gems.ops.mH(inp)
    utils.gems_assert_close(res_out, ref_out, dtype)
    assert res_out.shape == ref_out.shape
    assert res_out.stride() == ref_out.stride()
    assert res_out.is_conj() == ref_out.is_conj()
    assert res_out.untyped_storage().data_ptr() == inp.untyped_storage().data_ptr()


@pytest.mark.mH
@pytest.mark.parametrize("shape", MH_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_mH_non_contiguous(shape, dtype):
    # Non-contiguous (already transposed) and offset-window inputs must stay
    # zero-copy views with the stride-exchanged layout.
    base = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    inp = base.transpose(-2, -1)
    ref_inp = utils.to_reference(inp)

    ref_out = ref_inp.mH
    # Call the wrapper directly (no dispatch): mH is a zero-copy view, so its
    # contract must be observed on the FlagGems implementation itself.
    res_out = flag_gems.ops.mH(inp)
    utils.gems_assert_close(res_out, ref_out, dtype)
    assert res_out.shape == ref_out.shape
    assert res_out.stride() == ref_out.stride()
    assert res_out.untyped_storage().data_ptr() == base.untyped_storage().data_ptr()


@pytest.mark.mH
@pytest.mark.parametrize("shape", [(4, 6), (2, 3, 8, 16)])
def test_mH_complex(shape):
    # mH conjugates the last two dimensions as well as transposing them; the
    # lazy conjugate bit (not a materialized conjugate) must be set and the
    # result must still alias the input storage.
    # mH's conjugation semantics only exist for complex dtypes, so this test
    # covers torch.complex64 (the dtype used by aten's lazy-conj machinery).
    dtype = torch.complex64
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = ref_inp.mH
    # Call the wrapper directly (no dispatch): mH is a zero-copy view, so its
    # contract must be observed on the FlagGems implementation itself.
    res_out = flag_gems.ops.mH(inp)
    utils.gems_assert_close(res_out, ref_out, dtype)
    assert res_out.is_conj()
    assert res_out.shape == ref_out.shape
    assert res_out.stride() == ref_out.stride()
    assert res_out.untyped_storage().data_ptr() == inp.untyped_storage().data_ptr()
    # Materialized values must equal the conjugate-transpose values.
    utils.gems_assert_close(res_out.conj_physical(), ref_inp.mH.conj_physical(), dtype)


@pytest.mark.mH
def test_mH_write_through_view():
    """A write through the mH view is visible in the base tensor."""
    inp = torch.zeros(4, 6, dtype=torch.float32, device=flag_gems.device)
    res = flag_gems.ops.mH(inp)
    res[0, 0] = 7.0
    assert inp[0, 0].item() == 7.0


@pytest.mark.mH
def test_mH_1d_raises():
    """1-D input is rejected with the same RuntimeError as aten."""
    inp = torch.randn(8, dtype=torch.float32, device=flag_gems.device)
    with pytest.raises(RuntimeError):
        flag_gems.ops.mH(inp)


@pytest.mark.mH
def test_mH_0d_warns_and_conjugates():
    """0-D input follows the deprecated aten path: warn once, return conj()."""
    inp_real = torch.randn((), dtype=torch.float32, device=flag_gems.device)
    res_real = flag_gems.ops.mH(inp_real)
    assert res_real.shape == ()
    assert (
        res_real.untyped_storage().data_ptr() == inp_real.untyped_storage().data_ptr()
    )

    inp_cplx = torch.randn((), dtype=torch.complex64, device=flag_gems.device)
    res_cplx = flag_gems.ops.mH(inp_cplx)
    assert res_cplx.is_conj()
    assert (
        res_cplx.untyped_storage().data_ptr() == inp_cplx.untyped_storage().data_ptr()
    )
