# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

SPARSE_DIM = [2, 1, 2, 1]
DENSE_DIM = [0, 1, 0, 0]
SIZE = [[100, 200], [1000, 100], [500, 500], [10000]]
NNZ = [50, 500, 200, 1000]


def _baseline_op(sparse_dim, dense_dim, size, indices, values, *, is_coalesced=None):
    return torch.sparse_coo_tensor(indices, values, size, is_coalesced=is_coalesced)


@pytest.mark.sparse_coo_tensor_with_dims_and_tensors
def test_sparse_coo_tensor_with_dims_and_tensors():
    for sparse_dim, dense_dim, size, nnz in zip(SPARSE_DIM, DENSE_DIM, SIZE, NNZ):
        indices = torch.randint(
            0,
            min(size[:sparse_dim]),
            (sparse_dim, nnz),
            dtype=torch.int64,
            device="cuda",
        )
        values = torch.randn(
            (nnz,) + tuple(size[sparse_dim:]), device="cuda", dtype=torch.float32
        )
        ref_indices = utils.to_reference(indices)
        ref_values = utils.to_reference(values)
        ref = _baseline_op(sparse_dim, dense_dim, size, ref_indices, ref_values)

        with flag_gems.use_gems():
            res = torch.ops.aten._sparse_coo_tensor_with_dims_and_tensors(
                sparse_dim, dense_dim, size, indices, values
            )
        utils.gems_assert_equal(res, ref)


@pytest.mark.sparse_coo_tensor_with_dims_and_tensors
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_sparse_coo_tensor_with_dims_and_tensors_dtype(dtype):
    sparse_dim, dense_dim = 2, 0
    size, nnz = [100, 200], 50
    indices = torch.randint(
        0, min(size[:sparse_dim]), (sparse_dim, nnz), dtype=torch.int64, device="cuda"
    )
    values = torch.randn((nnz,) + tuple(size[sparse_dim:]), device="cuda", dtype=dtype)
    ref_indices = utils.to_reference(indices)
    ref_values = utils.to_reference(values)
    ref = _baseline_op(sparse_dim, dense_dim, size, ref_indices, ref_values)

    with flag_gems.use_gems():
        res = torch.ops.aten._sparse_coo_tensor_with_dims_and_tensors(
            sparse_dim, dense_dim, size, indices, values
        )
    utils.gems_assert_equal(res, ref)


@pytest.mark.sparse_coo_tensor_with_dims_and_tensors
def test_sparse_coo_tensor_with_dims_and_tensors_is_coalesced():
    sparse_dim, dense_dim = 2, 0
    size, nnz = [100, 200], 50
    indices = torch.randint(
        0, min(size[:sparse_dim]), (sparse_dim, nnz), dtype=torch.int64, device="cuda"
    )
    values = torch.randn(
        (nnz,) + tuple(size[sparse_dim:]), device="cuda", dtype=torch.float32
    )
    for is_coalesced in [True, False]:
        ref_indices = utils.to_reference(indices)
        ref_values = utils.to_reference(values)
        ref = _baseline_op(
            sparse_dim,
            dense_dim,
            size,
            ref_indices,
            ref_values,
            is_coalesced=is_coalesced,
        )

        with flag_gems.use_gems():
            res = torch.ops.aten._sparse_coo_tensor_with_dims_and_tensors(
                sparse_dim, dense_dim, size, indices, values, is_coalesced=is_coalesced
            )
        utils.gems_assert_equal(res, ref)
