# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# Custom shapes: (N, H, W) for 2D cases
AFFINE_GRID_BACKWARD_2D_SHAPES = [
    (1, 4, 4),
    (2, 8, 8),
    (4, 16, 16),
    (8, 32, 32),
    (2, 64, 64),
]

# Custom shapes: (N, D, H, W) for 3D cases
AFFINE_GRID_BACKWARD_3D_SHAPES = [
    (1, 4, 4, 4),
    (2, 8, 8, 8),
    (2, 4, 8, 16),
]


@pytest.mark.affine_grid_generator_backward
@pytest.mark.parametrize("shape", AFFINE_GRID_BACKWARD_2D_SHAPES)
# float32 only: kernel uses float32 internal accumulation; half causes mismatch
@pytest.mark.parametrize("dtype", [torch.float32])
@pytest.mark.parametrize("align_corners", [False, True])
def test_affine_grid_generator_backward_2d(shape, dtype, align_corners):
    N, H, W = shape
    grad_output = torch.randn((N, H, W, 2), dtype=dtype, device=flag_gems.device)
    size = [N, 1, H, W]

    ref_grad_output = utils.to_reference(grad_output)
    ref_out = torch.ops.aten.affine_grid_generator_backward(
        ref_grad_output, size, align_corners
    )

    with flag_gems.use_gems():
        res_out = torch.ops.aten.affine_grid_generator_backward(
            grad_output, size, align_corners
        )

    # Reduction over H*W introduces ordering differences; relax tolerance
    utils.gems_assert_close(res_out, ref_out, dtype, reduce_dim=H * W)


@pytest.mark.affine_grid_generator_backward
@pytest.mark.parametrize("shape", AFFINE_GRID_BACKWARD_3D_SHAPES)
# float32 only: kernel uses float32 internal accumulation; half causes mismatch
@pytest.mark.parametrize("dtype", [torch.float32])
@pytest.mark.parametrize("align_corners", [False, True])
def test_affine_grid_generator_backward_3d(shape, dtype, align_corners):
    N, D, H, W = shape
    grad_output = torch.randn((N, D, H, W, 3), dtype=dtype, device=flag_gems.device)
    size = [N, 1, D, H, W]

    ref_grad_output = utils.to_reference(grad_output)
    ref_out = torch.ops.aten.affine_grid_generator_backward(
        ref_grad_output, size, align_corners
    )

    with flag_gems.use_gems():
        res_out = torch.ops.aten.affine_grid_generator_backward(
            grad_output, size, align_corners
        )

    utils.gems_assert_close(res_out, ref_out, dtype, reduce_dim=D * H * W)
