# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Accuracy tests for ``aten::_slow_conv2d_forward``.

The operator is ATen's reference 2-D convolution forward, so the golden
reference is ``torch.ops.aten._slow_conv2d_forward`` itself, evaluated on the
upcast reference tensors.

Inputs are ordinary ``requires_grad=False`` tensors, so the wrapper takes the
plain Triton forward path rather than the autograd ``Function``.
"""

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# Shapes mimic a small ResNet-style stage: the 3x3 kernel at stride 1 keeps
# H_out/W_out equal to H/W and exercises the tap loop, while stride 2 with a
# 1x1 kernel covers the specialised 1x1 dispatch. The (2, 3, 8, 8) entry is
# kept tiny so the padding variants stay cheap.
_SLOW_CONV2D_FORWARD_SHAPES = [
    (2, 3, 8, 8),
    (2, 4, 16, 16),
    (4, 8, 32, 32),
]

# (kernel_size, stride, padding) combinations. stride 2 pairs with kernel 1 to
# hit the plain-GEMM 1x1 kernel; the padded stride-1 case hits the tap loop
# with a non-zero padding mask.
_SLOW_CONV2D_FORWARD_PARAMS = [
    # (kernel_size, stride, padding)
    ((3, 3), (1, 1), (0, 0)),
    ((3, 3), (1, 1), (1, 1)),
    ((1, 1), (1, 1), (0, 0)),
    ((3, 3), (2, 2), (1, 1)),
]


@pytest.mark.slow_conv2d_forward
@pytest.mark.parametrize("shape", _SLOW_CONV2D_FORWARD_SHAPES)
@pytest.mark.parametrize("kernel_size,stride,padding", _SLOW_CONV2D_FORWARD_PARAMS)
@pytest.mark.parametrize("has_bias", [False, True])
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_slow_conv2d_forward(shape, kernel_size, stride, padding, has_bias, dtype):
    n, c_in, h, w = shape
    kh, kw = kernel_size
    c_out = 8
    h_out = (h + 2 * padding[0] - kh) // stride[0] + 1
    w_out = (w + 2 * padding[1] - kw) // stride[1] + 1

    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    weight = torch.randn((c_out, c_in, kh, kw), dtype=dtype, device=flag_gems.device)
    bias = (
        torch.randn((c_out,), dtype=dtype, device=flag_gems.device)
        if has_bias
        else None
    )

    ref_inp = utils.to_reference(inp, True)
    ref_weight = utils.to_reference(weight, True)
    ref_bias = utils.to_reference(bias, True)
    ref_out = torch.ops.aten._slow_conv2d_forward(
        ref_inp,
        ref_weight,
        [kh, kw],
        ref_bias,
        [stride[0], stride[1]],
        [padding[0], padding[1]],
    )

    with flag_gems.use_gems():
        res_out = flag_gems._slow_conv2d_forward(
            inp,
            weight,
            [kh, kw],
            bias,
            [stride[0], stride[1]],
            [padding[0], padding[1]],
        )

    assert res_out.shape == (n, c_out, h_out, w_out)
    # fp16/bf16 convolutions accumulate over the full reduction window in the
    # same fp32 accumulator on both sides, but the tap ordering differs, so the
    # low-precision results need a wider tolerance than the 1e-4 default.
    atol = 2e-2 if dtype in (torch.float16, torch.bfloat16) else 1e-4
    utils.gems_assert_close(
        res_out, ref_out, dtype, reduce_dim=kernel_size[0] * kernel_size[1], atol=atol
    )
