# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Accuracy tests for ``aten::mT(Tensor(a) self) -> Tensor(a)``.

``mT`` is a zero-copy view operator: it swaps the last two dimensions of a
rank >= 2 tensor and returns a view aliasing the operand's storage.  The tests
verify the view contract (shape/stride/storage sharing, laziness of the conj
bit, autograd through the view) and the error paths for rank < 2, mirroring
the ``Tensor.mT`` attribute semantics.  Because a view never touches element
data, one float dtype sweep is enough; the layout checks are dtype-agnostic.
"""

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# 2D / 3D / 4D shapes: the last two dims get swapped, earlier dims stay put.
MT_SHAPES = [(16, 32), (7, 8, 9), (2, 3, 4, 5)]


def _check_view_metadata(res, ref):
    # The view must match the reference layout exactly and alias the operand.
    assert res.shape == ref.shape
    assert res.stride() == ref.stride()
    assert res.storage_offset() == ref.storage_offset()
    assert res.is_conj() == ref.is_conj()


@pytest.mark.mT
@pytest.mark.parametrize("shape", MT_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_mT(shape, dtype):
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    with flag_gems.use_gems():
        res_out = flag_gems.mT(inp)

    ref_out = torch.ops.aten.mT(ref_inp)
    _check_view_metadata(res_out, ref_out)
    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.mT
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_mT_noncontiguous(dtype):
    # A transposed / sliced operand is still only relaid out, never copied.
    base = torch.randn((32, 16), dtype=dtype, device=flag_gems.device)
    inp = base.t()[4:12, 2:14]
    ref_inp = utils.to_reference(inp)

    with flag_gems.use_gems():
        res_out = flag_gems.mT(inp)

    ref_out = torch.ops.aten.mT(ref_inp)
    _check_view_metadata(res_out, ref_out)
    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.mT
@pytest.mark.parametrize("shape", [(5, 6), (2, 3, 4, 5)])
def test_mT_shares_storage(shape):
    # The result is a view: same storage pointer, writes propagate both ways,
    # and the operand's own layout metadata is untouched.
    inp = torch.randn(shape, device=flag_gems.device, dtype=torch.float32)
    inp_shape, inp_stride, inp_offset = (
        inp.shape,
        inp.stride(),
        inp.storage_offset(),
    )

    with flag_gems.use_gems():
        res_out = flag_gems.mT(inp)

    assert res_out is not inp
    assert res_out.untyped_storage().data_ptr() == inp.untyped_storage().data_ptr()

    snapshot = inp.clone()
    res_out.fill_(1.0)
    ref = torch.ops.aten.mT(snapshot)
    assert torch.equal(inp, torch.ops.aten.mT(ref).fill_(1.0))
    assert inp.shape == inp_shape
    assert inp.stride() == inp_stride
    assert inp.storage_offset() == inp_offset


@pytest.mark.mT
def test_mT_autograd():
    # The view participates in autograd and routes the gradient transposed.
    inp = torch.randn(
        4, 6, device=flag_gems.device, dtype=torch.float32, requires_grad=True
    )
    ref_inp = utils.to_reference(inp).detach().requires_grad_(True)

    with flag_gems.use_gems():
        res_out = flag_gems.mT(inp)
    grad = torch.randn(res_out.shape, device=flag_gems.device, dtype=torch.float32)
    res_out.backward(grad)

    ref_out = torch.ops.aten.mT(ref_inp)
    ref_out.backward(utils.to_reference(grad))
    utils.gems_assert_close(inp.grad, ref_inp.grad, torch.float32)


@pytest.mark.mT
def test_mT_rank1_raises():
    # rank < 2 has no last two dimensions to swap: rank 1 must raise, while
    # rank 0 follows the deprecated ATen identity path (the same object).
    inp = torch.randn(8, device=flag_gems.device, dtype=torch.float32)
    with pytest.raises(RuntimeError):
        with flag_gems.use_gems():
            flag_gems.mT(inp)

    scalar = torch.tensor(3.14, device=flag_gems.device, dtype=torch.float32)
    with flag_gems.use_gems():
        res_out = flag_gems.mT(scalar)
    assert res_out is scalar
