# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE


def _make_coo_plain(device, dtype=torch.float32):
    indices = torch.tensor([[0, 1, 1], [1, 0, 1]], dtype=torch.int64, device=device)
    values = torch.randn(3, dtype=dtype, device=device)
    return torch.sparse_coo_tensor(indices, values, (2, 3))


def _make_coo_hybrid(device, dtype=torch.float32):
    # One sparse dim plus one dense trailing dim: the values tensor carries the
    # dense dim, shape (nnz, 2).
    indices = torch.tensor([[0, 1]], dtype=torch.int64, device=device)
    values = torch.randn(2, 2, dtype=dtype, device=device)
    return torch.sparse_coo_tensor(indices, values, (2, 2))


def _make_coo_uncoalesced(device, dtype=torch.float32):
    # Duplicate coordinates: deliberately not coalesced; _values must return
    # the raw stored values regardless of coalescing state.
    indices = torch.tensor([[0, 0, 1], [0, 0, 2]], dtype=torch.int64, device=device)
    values = torch.randn(3, dtype=dtype, device=device)
    return torch.sparse_coo_tensor(indices, values, (2, 3))


def _make_coo_zero_nnz(device, dtype=torch.float32):
    indices = torch.zeros(2, 0, dtype=torch.int64, device=device)
    values = torch.zeros(0, dtype=dtype, device=device)
    return torch.sparse_coo_tensor(indices, values, (2, 3))


COO_CASES = [
    ("coo-plain", _make_coo_plain),
    ("coo-hybrid", _make_coo_hybrid),
    ("coo-uncoalesced", _make_coo_uncoalesced),
    ("coo-zero-nnz", _make_coo_zero_nnz),
]
if QUICK_MODE:
    COO_CASES = [
        ("coo-plain", _make_coo_plain),
        ("coo-uncoalesced", _make_coo_uncoalesced),
    ]


@pytest.mark.values
@pytest.mark.parametrize(
    "name, make",
    COO_CASES,
    ids=[name for name, _ in COO_CASES],
)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_accuracy_values_coo(name, make, dtype):
    inp = make(flag_gems.device, dtype=dtype)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten._values(ref_inp)
    res_out = flag_gems.values(inp)

    assert res_out.shape == ref_out.shape
    assert res_out.dtype == ref_out.dtype == inp._values().dtype
    assert res_out.is_sparse is False
    assert res_out.layout == torch.strided
    utils.gems_assert_equal(res_out, ref_out)
    # Zero-copy alias: the view must share the input's values storage.
    assert res_out.data_ptr() == inp._values().data_ptr()


@pytest.mark.values
def test_values_mutation_through_view():
    # Writing through the returned view must be visible through the native
    # ``_values`` accessor and vice versa: proves a real alias, not a copy.
    inp = _make_coo_plain(flag_gems.device)
    ref_inp = utils.to_reference(inp.clone())

    res_out = flag_gems.values(inp)
    ref_out = ref_inp._values()

    assert res_out.data_ptr() == inp._values().data_ptr()
    res_out.fill_(1.0)
    ref_out.fill_(1.0)

    utils.gems_assert_equal(inp._values(), ref_out)
    utils.gems_assert_equal(inp.to_dense(), ref_inp.to_dense())


@pytest.mark.values
def test_values_strided_raises():
    # ATen implements _values only for sparse COO: the dispatcher raises
    # NotImplementedError for strided (dense) tensors. The registered
    # implementation mirrors that with its layout guard (it also guards before
    # delegating, because the override sits on the CUDA backend key too and a
    # strided re-dispatch would recurse).
    inp = torch.randn(4, dtype=torch.float32, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    with pytest.raises(NotImplementedError):
        torch.ops.aten._values(ref_inp)
    with pytest.raises(NotImplementedError):
        flag_gems.values(inp)


@pytest.mark.values
def test_values_sparse_compressed():
    # Verify natively whether aten::_values supports the sparse compressed
    # layouts; on this torch build it does not (SparseCsr* backends have no
    # kernel), so the registered path must raise the same NotImplementedError.
    dense = torch.tensor([[1.0, 2.0], [3.0, 4.0]], device=flag_gems.device)
    ref_dense = utils.to_reference(dense)

    try:
        torch.ops.aten._values(ref_dense.to_sparse_csr())
        native_csr_ok = True
    except NotImplementedError:
        native_csr_ok = False
    assert native_csr_ok is False, "native _values unexpectedly supports CSR"

    inp = dense.to_sparse_csr()
    with pytest.raises(NotImplementedError):
        flag_gems.values(inp)

    try:
        torch.ops.aten._values(ref_dense.to_sparse_csc())
        native_csc_ok = True
    except NotImplementedError:
        native_csc_ok = False
    assert native_csc_ok is False
    with pytest.raises(NotImplementedError):
        flag_gems.values(dense.to_sparse_csc())


@pytest.mark.values
def test_values_unsupported_layouts_reject_like_native():
    # Native ATen implements ``_values`` only on the Sparse{CPU,CUDA} keys:
    # every non-COO layout reaches the dispatcher, which reports the
    # *backend* key the tensor dispatched on ('SparseCsrCUDA' for all four
    # sparse compressed layouts, 'CUDA' for strided -- both spelled with
    # uppercase acronyms, not the Python layout spelling). The registered
    # guard must reject with the same exception type and a message that
    # includes the same operator+backend identification; a layout-spelled
    # message ("torch.sparse_bsr layout") fails this comparison. (The
    # dispatcher's full message appends a build-specific backend enumeration
    # and fallback note that a host-side reproduction cannot byte-match, so
    # the assertion is on the identifying portion.)
    dense = torch.tensor([[1.0, 2.0], [3.0, 4.0]], device=flag_gems.device)

    unsupported = [
        dense,  # strided -> 'CUDA' backend
        dense.to_sparse_csr(),  # -> 'SparseCsrCUDA' backend
        dense.to_sparse_csc(),
        dense.to_sparse_bsr((2, 2)),
        dense.to_sparse_bsc((2, 2)),
    ]
    for tensor in unsupported:
        with pytest.raises(NotImplementedError) as ours_exc:
            flag_gems.values(tensor)
        with pytest.raises(NotImplementedError) as native_exc:
            # Call native on the SAME device tensor: the dispatcher message
            # names the *backend key* of the tensor's device ('CUDA' vs
            # 'CPU'), so a CPU-side reference would report a different
            # backend than our GPU implementation and break the comparison.
            torch.ops.aten._values(tensor)
        ours, native = str(ours_exc.value), str(native_exc.value)
        # The identifying prefix of the native message ends with the backend
        # key token; ours must reach at least that token in the same order.
        native_prefix = native.split("backend.")[0]
        assert ours.startswith(
            native_prefix
        ), f"layout={tensor.layout}: ours: {ours!r}\nnative: {native!r}"


@pytest.mark.values
@pytest.mark.parametrize("dtype", [torch.int64, torch.int32, torch.bool])
def test_values_non_float_dtypes_alias(dtype):
    # Non-float stored values must come back through the same zero-copy
    # alias contract as float values: identical storage, preserved dtype,
    # equal elements -- compared against native ATen.
    if dtype is torch.bool:
        values = torch.tensor([True, False, True], device=flag_gems.device)
    else:
        values = torch.arange(3, dtype=dtype, device=flag_gems.device)
    inp = torch.sparse_coo_tensor(
        torch.tensor(
            [[0, 1, 1], [1, 0, 1]], dtype=torch.int64, device=flag_gems.device
        ),
        values,
        (2, 3),
    )

    ref_out = torch.ops.aten._values(utils.to_reference(inp))
    res_out = flag_gems.values(inp)

    assert res_out.dtype == ref_out.dtype == dtype
    assert res_out.shape == ref_out.shape == values.shape
    assert res_out.data_ptr() == inp._values().data_ptr()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.values
def test_values_int_hybrid_alias():
    # Hybrid COO (trailing dense dims) with integer stored values: the alias
    # view keeps the dense dims in the values shape and stays zero-copy.
    values = torch.arange(4, dtype=torch.int32, device=flag_gems.device).reshape(2, 2)
    inp = torch.sparse_coo_tensor(
        torch.tensor([[0, 1]], dtype=torch.int64, device=flag_gems.device),
        values,
        (2, 2),
    )

    ref_out = torch.ops.aten._values(utils.to_reference(inp))
    res_out = flag_gems.values(inp)

    assert res_out.dtype == ref_out.dtype == torch.int32
    assert res_out.shape == ref_out.shape == values.shape
    assert res_out.data_ptr() == inp._values().data_ptr()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.values
def test_values_requires_grad_nondifferentiable_contract():
    # ``_values`` is the *internal* accessor: on this build native returns a
    # plain alias view that is NOT part of autograd -- even when the stored
    # values carry ``requires_grad=True``, the returned view has
    # ``requires_grad=False``, no ``grad_fn`` and is a leaf (the public,
    # differentiable accessor is ``sparse.values()``, a different operator).
    # The registered path must reproduce exactly this non-differentiable view
    # contract, compared live against native on the same tensor.
    values = torch.randn(3, device=flag_gems.device, requires_grad=True)
    assert values.requires_grad
    inp = torch.sparse_coo_tensor(
        torch.tensor(
            [[0, 1, 1], [1, 0, 1]], dtype=torch.int64, device=flag_gems.device
        ),
        values,
        (2, 3),
    )

    res_out = flag_gems.values(inp)
    ref_out = torch.ops.aten._values(utils.to_reference(inp))

    assert res_out.requires_grad == ref_out.requires_grad
    assert res_out.grad_fn is None and ref_out.grad_fn is None
    assert res_out.is_leaf and ref_out.is_leaf
    assert res_out.data_ptr() == inp._values().data_ptr()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.values
def test_values_sparse_requires_grad_view_contract():
    # A sparse tensor that itself requires grad (e.g. built from a leaf
    # differentiable dense tensor via ``to_sparse``) must yield the same
    # non-differentiable internal view through both entry points: the
    # requires_grad state of the source does not leak into ``_values``.
    dense = torch.randn(2, 3, device=flag_gems.device, requires_grad=True)
    inp = dense.to_sparse()
    assert inp.requires_grad

    res_out = flag_gems.values(inp)
    ref_out = torch.ops.aten._values(utils.to_reference(inp))

    assert res_out.requires_grad == ref_out.requires_grad
    assert res_out.grad_fn is None and ref_out.grad_fn is None
    assert res_out.is_leaf and ref_out.is_leaf
    assert res_out.data_ptr() == inp._values().data_ptr()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.values
def test_values_dispatch_stability():
    # Repeated calls and cross-op interference must stay stable: the impl
    # delegates below the autograd key, so repeated dispatch never recurses and
    # unrelated dispatcher traffic (``aten::_nnz``) does not disturb it.
    inp = _make_coo_plain(flag_gems.device)
    ref_inp = utils.to_reference(inp)
    ref_values = torch.ops.aten._values(ref_inp)

    for _ in range(3):
        res = flag_gems.values(inp)
        assert res.shape == ref_values.shape
        assert res.data_ptr() == inp._values().data_ptr()
        # Unrelated registered-metadata dispatcher traffic in between.
        assert torch.ops.aten._nnz(inp) == 3
        utils.gems_assert_equal(res, ref_values)
