# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import pytest
import torch

import flag_gems

from . import test_utils as tu

# aten::to_mkldnn converts a dense CPU tensor into an opaque oneDNN (mkldnn)
# tensor. It is CPU-only, so values are generated by the shared generators and
# moved to CPU before the call: the reference and the candidate receive the same
# CPU tensors. The result has no data pointer, so values are observed through
# to_dense(); a reorder introduces no rounding, so materialized values are
# compared exactly.

# The reorder accepts exactly these five input dtypes. int32/int64/float64/bool
# and both FP8 types raise "dense_to_mkldnn expects float, bfloat16, half, uint8,
# int8 tensor input". CPU oneDNN supports all five, so this grid is not gated by
# the accelerator capability flags.
SUPPORTED_DTYPES = [
    torch.int8,
    torch.uint8,
    torch.float32,
    torch.bfloat16,
    torch.float16,
]

# 0-dim input has no reorder primitive ("could not create a primitive descriptor
# for the reorder primitive"), so () is covered by a negative case below.
SHAPES = [shape for shape in tu.selected_shapes() if shape != ()]

# Zero-element input still builds a valid reorder primitive.
EMPTY_SHAPES = [(0,), (0, 3)]

# The legal (input dtype, optional dtype) matrix, including the omitted dtype
# (None). Floating input may change dtype; int8/uint8 must keep it: "For int8,
# uint8 cpu_tensor input, we should not change the dtype".
DTYPE_PAIRS = [
    (torch.float32, None),
    (torch.float32, torch.float32),
    (torch.float32, torch.bfloat16),
    (torch.float32, torch.float16),
    (torch.float32, torch.int8),
    (torch.float32, torch.uint8),
    (torch.bfloat16, None),
    (torch.bfloat16, torch.bfloat16),
    (torch.bfloat16, torch.float32),
    (torch.bfloat16, torch.float16),
    (torch.bfloat16, torch.int8),
    (torch.bfloat16, torch.uint8),
    (torch.float16, None),
    (torch.float16, torch.float16),
    (torch.float16, torch.float32),
    (torch.float16, torch.bfloat16),
    (torch.float16, torch.int8),
    (torch.float16, torch.uint8),
    (torch.int8, None),
    (torch.int8, torch.int8),
    (torch.uint8, None),
    (torch.uint8, torch.uint8),
]
CONVERSION_SHAPES = tu.selected_cases(
    [(256,), (2, 19, 7), (20, 320, 15), (1024, 1024)], quick=[(2, 19, 7)]
)

# Floating input narrowed to int8/uint8 keeps the native conversion over the
# whole value range; the native result is the oracle, so no manual clipping or
# saturation is applied or expected here.
INT_NARROW_PAIRS = [
    (torch.float32, torch.int8),
    (torch.float32, torch.uint8),
    (torch.float16, torch.uint8),
]
INT_NARROW_SHAPES = tu.selected_cases([(2, 19, 7), (256,)], quick=[(2, 19, 7)])

# Non-contiguous / storage-offset inputs: the values must survive the strided
# read of the source tensor.
STRIDED_KINDS = ["transpose", "offset_slice", "strided_window", "channel_slice"]
STRIDED_DTYPES = [torch.float32, torch.float16, torch.int8]

# The out buffer must itself be an mkldnn tensor whose dtype matches the
# requested dtype; dtype=None (the schema default) is a valid request too.
OUT_ROWS = [
    ((2, 19, 7), torch.float32, None),
    ((2, 19, 7), torch.float32, torch.bfloat16),
    ((256,), torch.float16, None),
    ((20, 320, 15), torch.int8, None),
    ((1024, 1024), torch.float32, torch.float32),
]

# The backward of a layout conversion does not depend on the shape.
BACKWARD_ROWS = tu.selected_cases(
    [
        (shape, dtype)
        for shape in [(256,), (2, 19, 7), (20, 320, 15)]
        for dtype in [torch.float32, torch.bfloat16, torch.float16]
    ],
    quick=[],
)

# e4m3fn/e5m2 are rejected outright by this operator, so the special-value
# matrix runs over the three floating dtypes it accepts.
SPECIAL_ROWS = tu.selected_cases(
    tu.special_value_cases([torch.float32, torch.bfloat16, torch.float16]),
    quick=[],
)

UNSUPPORTED_INPUT_DTYPES = [
    torch.float64,
    torch.int32,
    torch.int64,
    torch.bool,
    torch.float8_e4m3fn,
    torch.float8_e5m2,
]

# "For int8, uint8 cpu_tensor input, we should not change the dtype".
INT_KEEP_DTYPE_PAIRS = [
    (torch.int8, torch.float32),
    (torch.int8, torch.uint8),
    (torch.uint8, torch.float16),
]

# aten::to_mkldnn has no kernel for a non-CPU framework device; on a CPU
# backend the scenario cannot exist and the row list is empty.
ACCELERATOR_DEVICES = [] if str(flag_gems.device) == "cpu" else [flag_gems.device]


def _strided_input(kind, dtype):
    """Build a non-contiguous / storage-offset CPU input."""
    if kind == "channel_slice":
        base = tu.make_input(dtype, (8, 10, 6, 6), ["-1", "1"]).cpu()
        return base[:, ::2, :, :]
    base = tu.make_input(dtype, (16, 8, 12), ["-1", "1"]).cpu()
    if kind == "transpose":
        return base.transpose(1, 2)
    if kind == "offset_slice":
        return base[3:11]
    return base[:, ::2, 1:9]


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("shape", SHAPES)
@pytest.mark.parametrize("value_range", tu.selected_ranges())
@pytest.mark.parametrize("dtype", SUPPORTED_DTYPES)
def test_to_mkldnn_with_value_range(shape, value_range, dtype):
    inp = tu.make_input(dtype, shape, value_range).cpu()
    ref_inp = tu.to_reference(inp)

    ref_out = torch.ops.aten.to_mkldnn(ref_inp)
    res_out = flag_gems.to_mkldnn(inp)

    assert res_out.is_mkldnn
    assert res_out.device == inp.device
    tu.assert_result_equal(res_out.to_dense(), ref_out.to_dense())
    # The conversion only reads its source.
    tu.assert_result_equal(inp, ref_inp)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("shape", EMPTY_SHAPES)
@pytest.mark.parametrize("dtype", [torch.float32, torch.int8])
def test_to_mkldnn_empty_input(shape, dtype):
    inp = tu.make_input(dtype, shape, ["-1", "1"]).cpu()
    ref_inp = tu.to_reference(inp)

    ref_out = torch.ops.aten.to_mkldnn(ref_inp)
    res_out = flag_gems.to_mkldnn(inp)

    assert res_out.is_mkldnn
    tu.assert_result_equal(res_out.to_dense(), ref_out.to_dense())
    tu.assert_result_equal(inp, ref_inp)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("shape", CONVERSION_SHAPES)
@pytest.mark.parametrize("in_dtype,out_dtype", DTYPE_PAIRS)
def test_to_mkldnn_dtype_conversion(shape, in_dtype, out_dtype):
    inp = tu.make_input(in_dtype, shape, ["-1", "1"]).cpu()
    ref_inp = tu.to_reference(inp)

    ref_out = torch.ops.aten.to_mkldnn(ref_inp, out_dtype)
    res_out = flag_gems.to_mkldnn(inp, out_dtype)

    assert res_out.is_mkldnn
    tu.assert_result_equal(res_out.to_dense(), ref_out.to_dense())
    tu.assert_result_equal(inp, ref_inp)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("in_dtype,out_dtype", DTYPE_PAIRS)
def test_to_mkldnn_dtype_keyword(in_dtype, out_dtype):
    inp = tu.make_input(in_dtype, (2, 19, 7), ["-1", "1"]).cpu()
    ref_inp = tu.to_reference(inp)

    ref_out = torch.ops.aten.to_mkldnn(ref_inp, dtype=out_dtype)
    res_out = flag_gems.to_mkldnn(inp, dtype=out_dtype)

    assert res_out.is_mkldnn
    tu.assert_result_equal(res_out.to_dense(), ref_out.to_dense())
    tu.assert_result_equal(inp, ref_inp)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("shape", INT_NARROW_SHAPES)
@pytest.mark.parametrize("value_range", tu.selected_ranges())
@pytest.mark.parametrize("in_dtype,out_dtype", INT_NARROW_PAIRS)
def test_to_mkldnn_int_narrowing_range(shape, value_range, in_dtype, out_dtype):
    inp = tu.make_input(in_dtype, shape, value_range).cpu()
    ref_inp = tu.to_reference(inp)

    ref_out = torch.ops.aten.to_mkldnn(ref_inp, out_dtype)
    res_out = flag_gems.to_mkldnn(inp, out_dtype)

    assert res_out.is_mkldnn
    tu.assert_result_equal(res_out.to_dense(), ref_out.to_dense())
    tu.assert_result_equal(inp, ref_inp)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("kind", STRIDED_KINDS)
@pytest.mark.parametrize("dtype", STRIDED_DTYPES)
def test_to_mkldnn_strided_input(kind, dtype):
    inp = _strided_input(kind, dtype)
    ref_inp = tu.to_reference(inp)

    ref_out = torch.ops.aten.to_mkldnn(ref_inp)
    res_out = flag_gems.to_mkldnn(inp)

    assert res_out.is_mkldnn
    tu.assert_result_equal(res_out.to_dense(), ref_out.to_dense())
    tu.assert_result_equal(inp, ref_inp)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("shape,dtype,out_dtype", OUT_ROWS)
def test_to_mkldnn_out_overload(shape, dtype, out_dtype):
    inp = tu.make_input(dtype, shape, ["-1", "1"]).cpu()
    ref_inp = tu.to_reference(inp)
    result_dtype = inp.dtype if out_dtype is None else out_dtype

    ref_out = torch.empty(shape, dtype=result_dtype, layout=torch._mkldnn)
    res_out = torch.empty(shape, dtype=result_dtype, layout=torch._mkldnn)

    torch.ops.aten.to_mkldnn(ref_inp, out_dtype, out=ref_out)
    res = flag_gems.to_mkldnn(inp, out_dtype, out=res_out)

    # The out overload returns the buffer it was given, not a fresh tensor.
    assert res is res_out
    tu.assert_result_equal(res_out.to_dense(), ref_out.to_dense())
    tu.assert_result_equal(inp, ref_inp)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("shape,dtype", BACKWARD_ROWS)
def test_to_mkldnn_backward(shape, dtype):
    inp = tu.make_input(dtype, shape, ["-1", "1"]).cpu()
    ref_inp = tu.to_reference(inp)
    upstream = tu.make_input(dtype, shape, ["-1", "1"]).cpu()
    inp.requires_grad_(True)
    ref_inp.requires_grad_(True)

    ref_out = torch.ops.aten.to_mkldnn(ref_inp)
    res_out = flag_gems.to_mkldnn(inp)

    # Forward contract first: the candidate returns the native opaque layout.
    assert res_out.is_mkldnn
    tu.assert_result_equal(res_out.to_dense(), ref_out.to_dense())

    # An mkldnn result only accepts an mkldnn upstream gradient, so the identity
    # through to_dense() carries the non-uniform upstream to the original leaf.
    (ref_grad,) = torch.autograd.grad(
        ref_out.to_dense(), ref_inp, grad_outputs=upstream
    )
    (res_grad,) = torch.autograd.grad(res_out.to_dense(), inp, grad_outputs=upstream)

    tu.assert_result_equal(res_grad, ref_grad)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("dtype,scenario", SPECIAL_ROWS)
def test_to_mkldnn_special_values(dtype, scenario):
    inp = tu.make_special_input(dtype, scenario).cpu()
    ref_inp = tu.to_reference(inp)

    ref_out = torch.ops.aten.to_mkldnn(ref_inp)
    res_out = flag_gems.to_mkldnn(inp)

    assert res_out.is_mkldnn
    tu.assert_result_equal(res_out.to_dense(), ref_out.to_dense())
    tu.assert_result_equal(inp, ref_inp)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("dtype", UNSUPPORTED_INPUT_DTYPES)
def test_to_mkldnn_rejects_unsupported_input_dtype(dtype):
    inp = torch.ones((2, 3)).to(dtype)
    with pytest.raises(RuntimeError):
        flag_gems.to_mkldnn(inp)


@pytest.mark.to_mkldnn
def test_to_mkldnn_rejects_zero_dim_input():
    inp = torch.ones(())
    with pytest.raises(RuntimeError):
        flag_gems.to_mkldnn(inp)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("in_dtype,out_dtype", INT_KEEP_DTYPE_PAIRS)
def test_to_mkldnn_rejects_int_input_dtype_change(in_dtype, out_dtype):
    inp = torch.ones((2, 3), dtype=in_dtype)
    with pytest.raises(RuntimeError):
        flag_gems.to_mkldnn(inp, out_dtype)


@pytest.mark.to_mkldnn
def test_to_mkldnn_rejects_dense_out_buffer():
    inp = torch.ones((2, 3))
    out = torch.empty((2, 3))
    with pytest.raises(RuntimeError):
        flag_gems.to_mkldnn(inp, out=out)


@pytest.mark.to_mkldnn
def test_to_mkldnn_rejects_out_dtype_mismatch():
    inp = torch.ones((2, 3))
    out = torch.empty((2, 3), dtype=torch.float32, layout=torch._mkldnn)
    with pytest.raises(RuntimeError):
        flag_gems.to_mkldnn(inp, torch.int8, out=out)


@pytest.mark.to_mkldnn
@pytest.mark.parametrize("device", ACCELERATOR_DEVICES)
def test_to_mkldnn_rejects_accelerator_input(device):
    inp = torch.ones((2, 3), device=device)
    with pytest.raises(NotImplementedError):
        flag_gems.to_mkldnn(inp)
