# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# ``col_indices`` returns the internal column-index buffer of a sparse
# compressed tensor as a zero-copy aliasing view. Coverage is therefore driven
# by layout and by the alias contract rather than by element values:
# row-compressed layouts (CSR/BSR) expose the buffer, while column-compressed
# layouts (CSC/BSC), COO and strided tensors follow the native ATen rejection.
if QUICK_MODE:
    CSR_SHAPES = [(2, 3)]
else:
    CSR_SHAPES = [(2, 3), (8, 16), (33, 65)]


def _make_csr(shape, nnz, seed=0, idx_dtype=torch.int64):
    """Build a CSR tensor with ``nnz`` random entries on ``flag_gems.device``."""
    gen = torch.Generator().manual_seed(seed)
    crow = torch.zeros(shape[0] + 1, dtype=idx_dtype)
    counts = torch.bincount(
        torch.randint(0, shape[0], (nnz,), generator=gen), minlength=shape[0]
    )
    crow[1:] = counts.cumsum(0)
    crow = crow.to(idx_dtype)
    ccol = torch.randint(0, shape[1], (nnz,), generator=gen).to(idx_dtype)
    values = torch.randn(nnz, generator=gen)
    return torch.sparse_csr_tensor(
        crow.to(flag_gems.device),
        ccol.to(flag_gems.device),
        values.to(flag_gems.device),
        shape,
    )


def _make_bsr(shape, block=2):
    """Build a BSR tensor with one fully-covered 2x2 block pair."""
    crow = torch.tensor([0, 1, 2], dtype=torch.int64, device=flag_gems.device)
    ccol = torch.tensor([0, 1], dtype=torch.int64, device=flag_gems.device)
    values = torch.randn(2, block, block, device=flag_gems.device)
    return torch.sparse_bsr_tensor(crow, ccol, values, shape)


@pytest.mark.col_indices
@pytest.mark.parametrize("shape", CSR_SHAPES)
def test_accuracy_col_indices_csr(shape):
    csr = _make_csr(shape, nnz=min(shape[0], 4), seed=0)

    ref_out = utils.to_reference(csr).col_indices()
    res_out = flag_gems.col_indices(csr)

    # Contract: 1-D int64 buffer with one entry per stored element.
    assert res_out.shape == (csr._nnz(),)
    assert res_out.dtype == torch.int64
    # Zero-copy alias: the view shares the input's col_indices storage.
    assert res_out.data_ptr() == csr.col_indices().data_ptr()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.col_indices
def test_accuracy_col_indices_bsr():
    # BSR is the other row-compressed layout; the native op accepts it too.
    bsr = _make_bsr((4, 6))

    ref_out = utils.to_reference(bsr).col_indices()
    res_out = flag_gems.col_indices(bsr)

    assert res_out.shape == (bsr._nnz(),)
    assert res_out.dtype == torch.int64
    assert res_out.data_ptr() == bsr.col_indices().data_ptr()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.col_indices
def test_accuracy_col_indices_mutation_through_view():
    # Real aliasing proof: a write through the returned view must be visible in
    # the sparse tensor's own buffer, and vice versa.
    csr = _make_csr((2, 4), nnz=3, seed=3)
    original = csr.col_indices().clone()

    res_out = flag_gems.col_indices(csr)
    assert res_out.data_ptr() == csr.col_indices().data_ptr()

    res_out[0] = -7
    assert csr.col_indices()[0].item() == -7

    # Reverse direction: mutate the tensor's own buffer and observe the change
    # through the previously returned view.
    csr.col_indices()[1] = -9
    assert res_out[1].item() == -9

    # Restore and confirm the buffers are still identical element-wise.
    res_out.copy_(original)
    assert torch.equal(res_out, csr.col_indices())
    utils.gems_assert_equal(res_out, utils.to_reference(csr).col_indices())


@pytest.mark.col_indices
def test_accuracy_col_indices_unsupported_layouts():
    # Only row-compressed layouts carry a column-index buffer. Column-compressed
    # (CSC/BSC), COO and strided inputs must reproduce the native ATen
    # rejection message verbatim; the strided case additionally proves the
    # override does not re-enter itself (a naive delegation would recurse).
    crow = torch.tensor([0, 2, 4], dtype=torch.int64, device=flag_gems.device)
    ccol = torch.tensor([0, 1, 0, 1], dtype=torch.int64, device=flag_gems.device)
    val = torch.randn(4, device=flag_gems.device)

    csc = torch.sparse_csc_tensor(ccol, crow, val, (3, 3))
    bsc = torch.sparse_bsc_tensor(
        ccol, crow, torch.randn(4, 2, 2, device=flag_gems.device), (4, 4)
    )
    coo = torch.sparse_coo_tensor(
        torch.tensor([[0, 1], [1, 0]], dtype=torch.int64, device=flag_gems.device),
        torch.randn(2, device=flag_gems.device),
        (2, 3),
    )
    dense = torch.randn(2, 3, device=flag_gems.device)

    for tensor in (csc, bsc, coo, dense):
        with pytest.raises(RuntimeError, match="expected sparse row compressed"):
            flag_gems.col_indices(tensor)


@pytest.mark.col_indices
def test_accuracy_col_indices_dispatch_stability():
    # Repeated dispatcher-routed calls plus an unrelated sparse metadata op in
    # between must not recurse, re-route or lose the alias (no shared mutable
    # state in the implementation).
    csr = _make_csr((4, 8), nnz=5, seed=7)
    ref = utils.to_reference(csr).col_indices()

    first = flag_gems.col_indices(csr)
    for _ in range(3):
        again = flag_gems.col_indices(csr)
        assert again.data_ptr() == first.data_ptr()
        assert torch.ops.aten._nnz(csr) == csr._nnz()
        utils.gems_assert_equal(again, ref)

    # The dispatcher-routed path (used once registration is active) must reach
    # the same buffer as well.
    via_dispatch = torch.ops.aten.col_indices(csr)
    assert via_dispatch.data_ptr() == first.data_ptr()
    utils.gems_assert_equal(via_dispatch, ref)


@pytest.mark.col_indices
def test_accuracy_col_indices_dispatch_sentinel():
    # Sentinel test: verify that the FlagGems wrapper is actually reached
    # through the Autograd-key dispatch path (reviewer-requested). Patch
    # flag_gems.col_indices with a counting wrapper and verify the call
    # goes through the registered implementation.
    import flag_gems.ops.col_indices as impl_mod

    original_impl = impl_mod.col_indices
    calls = {"count": 0}

    def counting_impl(tensor):
        calls["count"] += 1
        return original_impl(tensor)

    impl_mod.col_indices = counting_impl
    try:
        csr = _make_csr((3, 5), nnz=4, seed=3)
        flag_gems.col_indices(csr)
        assert (
            calls["count"] > 0
        ), "flag_gems.col_indices did not reach the registered implementation"
    finally:
        impl_mod.col_indices = original_impl
    utils.gems_assert_equal(
        flag_gems.col_indices(csr), utils.to_reference(csr).col_indices()
    )


def test_accuracy_col_indices_int32_indices():
    # int32 index tensors: the copied buffer dtype must follow the input.
    for idx_dtype in (torch.int64, torch.int32):
        dense = torch.zeros(3, 5)
        for r in range(3):
            dense[r, r] = 1.0
        crow = torch.tensor([0, 1, 2, 3], dtype=idx_dtype)
        ccol = torch.tensor([0, 1, 2], dtype=idx_dtype)
        values = torch.randn(3)
        csr = torch.sparse_csr_tensor(
            crow.to(flag_gems.device),
            ccol.to(flag_gems.device),
            values.to(flag_gems.device),
            (3, 5),
        )
        assert csr.col_indices().dtype == idx_dtype
        ref = utils.to_reference(csr).col_indices()
        res = flag_gems.col_indices(csr)
        assert res.dtype == ref.dtype
        utils.gems_assert_equal(res, ref)


def test_accuracy_col_indices_batched():
    # Batched CSR: col-indices view includes batch dims. Every row has
    # exactly 1 nonzero so the construction is well-formed.
    dense = torch.zeros(2, 3, 4)
    for b in range(2):
        for m in range(3):
            dense[b, m, m] = 1.0
    csr = dense.to_sparse_csr()
    ref = utils.to_reference(csr).col_indices()
    res = flag_gems.col_indices(csr)
    assert res.shape == ref.shape
    utils.gems_assert_equal(res, ref)


def test_accuracy_col_indices_empty_csr():
    # nnz=0: the col-indices buffer exists but is empty; must still work.
    crow = torch.tensor([0, 0, 0], dtype=torch.int64, device=flag_gems.device)
    ccol = torch.zeros(0, dtype=torch.int64, device=flag_gems.device)
    values = torch.zeros(0, device=flag_gems.device)
    csr = torch.sparse_csr_tensor(crow, ccol, values, (3, 4))
    assert csr._nnz() == 0
    res = flag_gems.col_indices(csr)
    assert res.numel() == 0
    utils.gems_assert_equal(res, utils.to_reference(csr).col_indices())
