import numpy as np
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils


# Define shapes and strides for as_strided_ tests
AS_STRIDED_SHAPES = [(12,), (24,), (48,), (120,)]
AS_STRIDED_SIZE_STRIDE_COMBOS = [
    # (size, stride)
    ([3, 4], [4, 1]),
    ([4, 3], [3, 1]),
    ([2, 6], [6, 1]),
    ([6, 2], [2, 1]),
    ([12, 1], [1, 1]),
    ([1, 12], [12, 1]),
    ([2, 2, 3], [6, 3, 1]),
]


def _is_valid_as_strided(shape, size, stride, storage_offset=0):
    """Check whether size / stride / storage_offset is valid for as_strided_."""
    if len(size) != len(stride):
        return False

    if storage_offset < 0:
        return False

    if any(dim < 0 for dim in size):
        return False

    if any(st < 0 for st in stride):
        return False

    storage_size = int(np.prod(shape))

    # Empty tensor does not access storage.
    if int(np.prod(size)) == 0:
        return storage_offset <= storage_size

    max_index = storage_offset
    for dim, st in zip(size, stride):
        max_index += (dim - 1) * st

    return max_index < storage_size


@pytest.mark.as_strided_
@pytest.mark.parametrize("shape", AS_STRIDED_SHAPES)
@pytest.mark.parametrize("size_stride", AS_STRIDED_SIZE_STRIDE_COMBOS)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_as_strided_(shape, size_stride, dtype):
    """Test as_strided_ operator changes shape and stride correctly."""
    size, stride = size_stride

    # Invalid input combinations are generated by parametrization.
    # They are not known defects, so return instead of pytest.skip().
    if not _is_valid_as_strided(shape, size, stride):
        return

    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp.clone())

    # Apply as_strided_.
    ref_out = ref_inp.as_strided_(size, stride)

    with flag_gems.use_gems():
        res_out = inp.as_strided_(size, stride)

    # Verify inplace behavior.
    assert res_out is inp, "as_strided_ should return the same tensor object"

    # Verify shape and stride match.
    assert res_out.shape == torch.Size(size), (
        f"Shape mismatch: {res_out.shape} vs {size}"
    )

    assert res_out.stride() == tuple(stride), (
        f"Stride mismatch: {res_out.stride()} vs {stride}"
    )

    # Verify data is correct.
    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.as_strided_
@pytest.mark.parametrize("shape", AS_STRIDED_SHAPES)
@pytest.mark.parametrize("size_stride", AS_STRIDED_SIZE_STRIDE_COMBOS)
@pytest.mark.parametrize("storage_offset", [0, 2, 4, 6])
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_as_strided_with_offset(shape, size_stride, storage_offset, dtype):
    """Test as_strided_ with storage_offset parameter."""
    size, stride = size_stride

    # Invalid input combinations are generated by parametrization.
    # They are not known defects, so return instead of pytest.skip().
    if not _is_valid_as_strided(shape, size, stride, storage_offset):
        return

    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp.clone())

    # Apply as_strided_ with storage_offset.
    ref_out = ref_inp.as_strided_(size, stride, storage_offset)

    with flag_gems.use_gems():
        res_out = inp.as_strided_(size, stride, storage_offset)

    # Verify inplace behavior.
    assert res_out is inp, "as_strided_ should return the same tensor object"

    # Verify shape, stride and storage_offset match.
    assert res_out.shape == torch.Size(size), (
        f"Shape mismatch: {res_out.shape} vs {size}"
    )

    assert res_out.stride() == tuple(stride), (
        f"Stride mismatch: {res_out.stride()} vs {stride}"
    )

    assert res_out.storage_offset() == storage_offset, (
        f"Storage offset mismatch: {res_out.storage_offset()} vs {storage_offset}"
    )

    # Verify data is correct.
    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.as_strided_
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_as_strided_inplace(dtype):
    """Test that as_strided_ is in-place and returns the original tensor."""
    shape = (12,)
    size = [3, 4]
    stride = [4, 1]
    storage_offset = 0

    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp.clone())

    # Apply as_strided_.
    ref_out = ref_inp.as_strided_(size, stride, storage_offset)

    with flag_gems.use_gems():
        res_out = inp.as_strided_(size, stride, storage_offset)

    # Verify inplace behavior.
    assert res_out is inp, "as_strided_ should return the same tensor object"
    assert ref_out is ref_inp, (
        "Reference as_strided_ should return the same tensor object"
    )

    # Verify shape, stride and storage_offset.
    assert inp.shape == torch.Size(size), (
        f"Shape mismatch: {inp.shape} vs {size}"
    )

    assert inp.stride() == tuple(stride), (
        f"Stride mismatch: {inp.stride()} vs {stride}"
    )

    assert inp.storage_offset() == storage_offset, (
        f"Storage offset mismatch: {inp.storage_offset()} vs {storage_offset}"
    )

    # Verify data is correct.
    utils.gems_assert_close(inp, ref_inp, dtype)
