# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Accuracy tests for ``aten::slow_conv_dilated3d``.

The golden reference is ATen's own ``torch.ops.aten.slow_conv_dilated3d``
(it is implemented on both CPU and CUDA), so the comparison is against the
exact same algorithm PyTorch uses for this operator.
"""

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# (input, weight, bias, stride, padding, dilation)
#
# Every tuple is a 3-D convolution case. The spatial extents are kept small
# (D <= 16, H = W <= 16) because the reference is a full im2col + GEMM path
# whose intermediate column buffer grows as Cout * kD * kH * kW * Do * Ho * Wo;
# small extents keep that buffer in the low tens of MB. The set covers unit
# stride/padding/dilation, strided cases, atrous (dilation > 1) cases,
# asymmetric pad/dilation triples and an unbatched 4-D input.
SLOW_CONV_DILATED3D_CASES = [
    ((2, 3, 8, 16, 16), (4, 3, 3, 3, 3), (1, 1, 1), (1, 1, 1), (1, 1, 1)),
    ((2, 4, 8, 12, 12), (6, 4, 2, 3, 2), (2, 1, 2), (0, 1, 0), (1, 2, 1)),
    ((1, 2, 8, 8, 8), (3, 2, 3, 3, 3), (2, 2, 2), (2, 2, 2), (1, 1, 1)),
    ((3, 8, 10, 10), (5, 3, 2, 2, 2), (1, 1, 1), (1, 1, 1), (1, 1, 1)),
    ((2, 3, 6, 9, 9), (4, 3, 2, 2, 2), (1, 2, 2), (1, 1, 1), (2, 1, 2)),
    ((2, 3, 6, 9, 9), (4, 3, 2, 2, 2), (1, 1, 1), (0, 1, 2), (2, 2, 2)),
    ((1, 4, 8, 8, 8), (6, 4, 3, 3, 3), (1, 1, 1), (1, 1, 1), (2, 2, 2)),
]


@pytest.mark.slow_conv_dilated3d
@pytest.mark.parametrize("case", SLOW_CONV_DILATED3D_CASES)
@pytest.mark.parametrize("bias", [True, False])
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_slow_conv_dilated3d(case, bias, dtype):
    inp_shape, weight_shape, stride, padding, dilation = case
    if len(inp_shape) == 4 and bias:
        # Upstream aten::slow_conv_dilated3d misindexes the bias in the
        # unbatched 4-D path (both CPU and CUDA add the wrong bias elements,
        # verified against F.conv3d), and it raises IndexError when an unbatched
        # 4-D input is combined with stride > 1 and dilation > 1. The Triton
        # kernel follows the batched 5-D semantics, so the bias variant of the
        # unbatched case has no usable ATen baseline.
        pytest.skip("aten unbatched 4-D + bias path is broken upstream")
    inp = torch.randn(inp_shape, dtype=dtype, device=flag_gems.device)
    weight = torch.randn(weight_shape, dtype=dtype, device=flag_gems.device)
    if bias:
        bias_t = torch.randn(weight_shape[0], dtype=dtype, device=flag_gems.device)
    else:
        bias_t = None

    # Upcast the reference to fp64 so the ATen baseline accumulates at high
    # precision; the kernel is then compared against that (near-exact) result.
    ref_inp = utils.to_reference(inp, True)
    ref_weight = utils.to_reference(weight, True)
    ref_bias = utils.to_reference(bias_t, True)

    kernel_size = list(weight_shape[2:])
    ref_out = torch.ops.aten.slow_conv_dilated3d(
        ref_inp,
        ref_weight,
        kernel_size,
        ref_bias,
        list(stride),
        list(padding),
        list(dilation),
    ).to(dtype)

    res_out = flag_gems.slow_conv_dilated3d(
        inp, weight, kernel_size, bias_t, stride, padding, dilation
    )
    # fp16/bf16 accumulate in fp32 inside the kernel but the baseline is an
    # fp64 im2col + GEMM, so those two need a loosened absolute tolerance.
    atol = 2e-2 if dtype in (torch.float16, torch.bfloat16) else 1e-4
    utils.gems_assert_close(res_out, ref_out, dtype, atol=atol)
