# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Metax backend specialization for cdist_forward.
# Currently delegates to the generic Triton kernel in flag_gems.ops._cdist_forward.
# This file exists as an extension point for future Metax-specific optimizations.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

from flag_gems.ops._cdist_forward import (
    _cdist_forward,
    _cdist_forward_kernel,
)

__all__ = ["_cdist_forward", "_cdist_forward_kernel"]
