# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger("flag_gems." + __name__)


@libentry()
@triton.jit
def _cdist_forward_kernel(
    x1_ptr,
    x2_ptr,
    output_ptr,
    P,
    R,
    M,
    batch_size,
    x1_stride_b,
    x1_stride_p,
    x1_stride_m,
    x2_stride_b,
    x2_stride_r,
    x2_stride_m,
    output_stride_b,
    output_stride_p,
    output_stride_r,
    BLOCK_M: tl.constexpr,
):
    """Kernel for computing cdist between two point sets with p=2 (L2 norm).

    x1 shape: (..., P, M) - P points in M-dimensional space
    x2 shape: (..., R, M) - R points in M-dimensional space
    output shape: (..., P, R) - distances between each pair

    Flattened shape: (batch_size, P, M), (batch_size, R, M), (batch_size, P, R)
    """
    # Get program IDs
    pid_p = tle.program_id(0)
    pid_r = tle.program_id(1)
    pid_b = tle.program_id(2)

    # Add batch offset
    x1_ptr_batch = x1_ptr + pid_b * x1_stride_b
    x2_ptr_batch = x2_ptr + pid_b * x2_stride_b
    output_ptr_batch = output_ptr + pid_b * output_stride_b

    # Calculate output position
    output_offset = pid_p * output_stride_p + pid_r * output_stride_r

    # Load point from x1
    x1_offset = pid_p * x1_stride_p
    x1_ptr_row = x1_ptr_batch + x1_offset

    # Load point from x2
    x2_offset = pid_r * x2_stride_r
    x2_ptr_row = x2_ptr_batch + x2_offset

    # Compute L2 distance (p=2)
    acc = tl.zeros([BLOCK_M], dtype=tl.float32)

    # Process in blocks over the feature dimension M
    for m_start in range(0, M, BLOCK_M):
        m_offsets = m_start + tl.arange(0, BLOCK_M)
        m_mask = m_offsets < M

        # Load x1[p, m]
        x1_vals = tl.load(
            x1_ptr_row + m_offsets * x1_stride_m, mask=m_mask, other=0.0
        ).to(tl.float32)

        # Load x2[r, m]
        x2_vals = tl.load(
            x2_ptr_row + m_offsets * x2_stride_m, mask=m_mask, other=0.0
        ).to(tl.float32)

        diff = x1_vals - x2_vals
        acc = acc + diff * diff

    # Finalize: sqrt for L2 norm
    result = tl.sqrt(tl.sum(acc, axis=0))

    # Store result
    tl.store(output_ptr_batch + output_offset, result.to(output_ptr.dtype.element_ty))


def _cdist_forward(
    x1: torch.Tensor, x2: torch.Tensor, p: float = 2.0, compute_mode=None
):
    """Compute the p-norm distance between each pair of the two collections of row vectors.

    Args:
        x1: Input tensor of shape (..., P, M) where P is number of points and M is feature dimension
        x2: Input tensor of shape (..., R, M) where R is number of points and M is feature dimension
        p: p value for the p-norm distance (default: 2.0)
        compute_mode: Computation mode (not used in this implementation)

    Returns:
        Tensor of shape (..., P, R) containing pairwise distances

    Note:
        This implementation only supports p=2.0 (L2 norm). For other p values,
        the function falls back to torch.cdist.
    """
    logger.debug("GEMS_METAX CDIST_FORWARD")

    # Only support p=2.0 for now
    if p != 2.0:
        logger.debug("GEMS_METAX CDIST_FORWARD falling back to torch (p != 2.0)")
        return torch.cdist(x1, x2, p=p, compute_mode=compute_mode)

    # Handle broadcasting - get leading dimensions
    x1_shape = x1.shape
    x2_shape = x2.shape

    # Get the batch dimensions (everything except last two)
    batch_dims_x1 = x1_shape[:-2]
    batch_dims_x2 = x2_shape[:-2]

    # Calculate batch size
    batch_size = 1
    for dim in range(max(len(batch_dims_x1), len(batch_dims_x2))):
        d1 = batch_dims_x1[dim] if dim < len(batch_dims_x1) else 1
        d2 = batch_dims_x2[dim] if dim < len(batch_dims_x2) else 1
        batch_size *= max(d1, d2)

    P = x1_shape[-2]
    R = x2_shape[-2]
    M = x1_shape[-1]

    # Flatten batch dimensions
    x1_flat = x1.reshape(-1, P, M)
    x2_flat = x2.reshape(-1, R, M)

    # Create output tensor
    output = torch.empty((batch_size, P, R), dtype=x1.dtype, device=x1.device)

    # Launch kernel
    grid = (P, R, batch_size)

    # Choose BLOCK_M based on M
    BLOCK_M = min(triton.next_power_of_2(M), 64)

    with torch_device_fn.device(x1.device):
        _cdist_forward_kernel[grid](
            x1_flat,
            x2_flat,
            output,
            P,
            R,
            M,
            batch_size,
            x1_flat.stride(0),  # batch stride
            x1_flat.stride(1),  # P stride
            x1_flat.stride(2),  # M stride
            x2_flat.stride(0),  # batch stride
            x2_flat.stride(1),  # R stride
            x2_flat.stride(2),  # M stride
            output.stride(0),  # batch stride
            output.stride(1),  # P stride
            output.stride(2),  # R stride
            BLOCK_M=BLOCK_M,
        )

    # Reshape output to match expected shape
    # Calculate output batch shape
    output_batch_shape = []
    for dim in range(max(len(batch_dims_x1), len(batch_dims_x2))):
        d1 = batch_dims_x1[dim] if dim < len(batch_dims_x1) else 1
        d2 = batch_dims_x2[dim] if dim < len(batch_dims_x2) else 1
        output_batch_shape.append(max(d1, d2))

    output = output.view(*output_batch_shape, P, R)

    return output
