# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger("flag_gems." + __name__)


@triton.jit
def _special_bessel_j0_kernel(x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    x_f32 = x.to(tl.float32)
    ax = tl.abs(x_f32)

    # Bessel J0 using series expansion
    # J0(x) = sum_{k=0}^{inf} (-1)^k * (x^2/4)^k / (k!^2)
    #       = 1 - (x^2)/4 + (x^2/4)^2/4 - (x^2/4)^3/36 + ...
    # Let y = x^2/4 = (x/2)^2
    #
    # For |x| <= 8: series expansion
    # For |x| > 8: asymptotic expansion

    # ===== Small x region =====
    x2 = x_f32 * x_f32  # x^2
    y = x2 / 4.0  # x^2/4

    # Compute 7 terms of series
    # term_0 = 1
    # term_1 = -y
    # term_2 = y^2 / 4
    # term_3 = -y^3 / 36
    # term_4 = y^4 / 576
    # term_5 = -y^5 / 14400
    # term_6 = y^6 / 518400

    term0 = 1.0
    term1 = -y
    term2 = y * y / 4.0
    term3 = -(y * y * y) / 36.0
    term4 = (y * y * y * y) / 576.0
    term5 = -(y * y * y * y * y) / 14400.0
    term6 = (y * y * y * y * y * y) / 518400.0

    ans_small = term0 + term1 + term2 + term3 + term4 + term5 + term6

    # Handle x near 0: J0(0) = 1
    ans_small = tl.where(ax < 1e-30, 1.0, ans_small)

    # ===== Large x region =====
    # Asymptotic: J0(x) ~ sqrt(2/pi/x) * cos(x - pi/4)
    ax_safe = tl.maximum(ax, 8.0)
    half_pi = 1.5707963267948966
    x_phase = ax_safe - half_pi / 2.0  # x - pi/4

    sqrt_2_over_pi = 0.7978845608028654
    sqrt_term = sqrt_2_over_pi / tl.sqrt(ax_safe)
    cos_term = tl.cos(x_phase)

    ans_large = sqrt_term * cos_term

    # Combine
    is_large = ax > 8.0
    ans = tl.where(is_large, ans_large, ans_small)

    # Store result
    tl.store(out_ptr + offsets, ans.to(x.dtype), mask=mask)


def _launch_special_bessel_j0(x: torch.Tensor, out: torch.Tensor):
    assert x.is_cuda and out.is_cuda, "Tensors must be CUDA tensors"
    assert (
        x.numel() == out.numel()
    ), "Input and output must have the same number of elements"
    assert x.dtype == out.dtype, "Input and output must have the same dtype"

    n_elements = x.numel()
    if n_elements == 0:
        return

    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        _special_bessel_j0_kernel[grid](x, out, n_elements, BLOCK_SIZE=BLOCK_SIZE)


def special_bessel_j0(x: torch.Tensor):
    logger.debug("GEMS_METAX SPECIAL_BESSEL_J0")
    x_c = x.contiguous()
    out = torch.empty_like(x_c)
    _launch_special_bessel_j0(x_c, out)
    if x.layout == torch.strided and x.is_contiguous():
        return out
    else:
        return out.view_as(x)


def special_bessel_j0_out(x: torch.Tensor, out: torch.Tensor):
    logger.debug("GEMS_METAX SPECIAL_BESSEL_J0_OUT")
    if out.dtype != x.dtype:
        raise TypeError("out dtype must match input dtype")
    if out.device != x.device:
        raise TypeError("out device must match input device")

    x_c = x.contiguous()
    out_c = out.contiguous()
    _launch_special_bessel_j0(x_c, out_c)
    if out_c.data_ptr() != out.data_ptr():
        out.copy_(out_c)
    return out
