# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import importlib
import logging
import os
import threading

import torch

from .attention import scaled_dot_product_attention_forward  # [attn-route 2026-09-16]

logger = logging.getLogger(__name__)


_SDPA_LSE_MASK_CACHE = {}


def _sdpa_causal_add_mask(sq, sk, dtype, device):
    """[attn-route 2026-09-17 v3] cached additive causal mask (0 / -1.0e6)."""
    key = (sq, sk, str(dtype), str(device))
    m = _SDPA_LSE_MASK_CACHE.get(key)
    if m is None:
        import numpy as np

        rows = np.arange(sq).reshape(-1, 1)
        cols = np.arange(sk).reshape(1, -1)
        add = np.where(cols <= rows + (sk - sq), 0.0, -1.0e6).astype(np.float32)
        m = torch.from_numpy(add).to(device=device, dtype=dtype)
        _SDPA_LSE_MASK_CACHE[key] = m
    return m


def _sdpa_logsumexp(query, key, is_causal, scale, attn_mask=None):
    """[attn-route 2026-09-17 v3] xpu-side lse; causal via cached additive mask."""
    sm_scale = scale if scale is not None else 1.0 / (query.shape[-1] ** 0.5)
    qf = query.float()
    kf = key.float()
    if qf.shape[1] != kf.shape[1]:
        kf = kf.repeat_interleave(qf.shape[1] // kf.shape[1], dim=1)
    scores = torch.matmul(qf, kf.transpose(-1, -2)) * sm_scale
    if attn_mask is not None:
        scores = scores + attn_mask.float()
    if is_causal:
        scores = scores + _sdpa_causal_add_mask(
            scores.shape[-2], scores.shape[-1], scores.dtype, scores.device
        )
    return torch.logsumexp(scores, dim=-1)


def _sdpa_forward_with_lse(
    query, key, value, attn_mask, dropout_p, is_causal, scale, enable_gqa=False
):
    """[attn-route v4 2026-09-17] Run the kunlunxin sdpa forward and recover the
    kernel's own softmax_lse from the autograd ctx (save_for_backward order:
    query, key, value, o, M). Zero recompute; avoids the flaky xblas JIT-C
    bmm path used by earlier recompute-based helpers."""
    need_grad = any(t.requires_grad for t in (query, key, value))
    if not need_grad:
        q_in = query.detach().requires_grad_(True)
        with torch.enable_grad():
            out = scaled_dot_product_attention_forward(
                q_in,
                key,
                value,
                attn_mask=attn_mask,
                dropout_p=dropout_p,
                is_causal=is_causal,
                scale=scale,
                enable_gqa=enable_gqa,
            )
    else:
        out = scaled_dot_product_attention_forward(
            query,
            key,
            value,
            attn_mask=attn_mask,
            dropout_p=dropout_p,
            is_causal=is_causal,
            scale=scale,
            enable_gqa=enable_gqa,
        )
    lse = None
    gf = getattr(out, "grad_fn", None)
    if gf is not None:
        saved = getattr(gf, "saved_tensors", None) or ()
        if len(saved):
            cand = saved[-1]
            if (
                torch.is_tensor(cand)
                and cand.dim() == 3
                and cand.dtype == torch.float32
            ):
                lse = cand
    if not need_grad:
        out = out.detach()
    return out, lse


# ---------------------------------------------------------------------------
# [attn-route 2026-09-18, C-161] host fast path.
#
# The generic entry rebuilds the whole launch machinery on every call (autograd
# Function apply -> ScaleDotProductAttention.forward -> triton Autotuner ->
# JITFunction.run -> launcher -> xfa) plus several small device tensors.  On the
# first call for a config key we delegate to the generic path and capture the
# deepest JITFunction.run arguments; later calls replay them with the fresh
# input/output tensors spliced back in (bit-identical kernel, same arguments).
# Any doubt falls back to the generic path; FG_OVERRIDEABLE_FASTPATH=0 disables.
# ---------------------------------------------------------------------------

_ENABLED = os.environ.get("FG_OVERRIDEABLE_FASTPATH", "1") != "0"

_LOCK = threading.Lock()
_CACHE = {}
_MAX_KEYS = 64
_LAST = None  # (query, key, value, flags, rec)


def _attn_jit_function():
    # NOTE: the runtime backend is the top-level "_kunlunxin.ops" package;
    # resolve the sibling module through THIS module's own package (there is a
    # second copy under flag_gems.runtime.backend._kunlunxin.ops).
    att = importlib.import_module(__package__ + ".attention")
    kern = att._attn_fwd
    jf = getattr(kern, "fn", None)
    if jf is None or not hasattr(jf, "run"):
        jf = kern
    return jf if hasattr(jf, "run") else None


def _eligible(query, key, value, attn_bias, dropout_p, return_debug_mask):
    return (
        attn_bias is None
        and (dropout_p or 0.0) == 0.0
        and not return_debug_mask
        and query.is_cuda
        and query.dtype in (torch.float16, torch.bfloat16, torch.float32)
        and key.dtype == query.dtype
        and value.dtype == query.dtype
        and not any(t.requires_grad for t in (query, key, value))
    )


def _key_of(query, key, value, is_causal, scale):
    return (
        tuple(query.shape),
        tuple(query.stride()),
        query.dtype,
        tuple(key.shape),
        tuple(key.stride()),
        tuple(value.shape),
        tuple(value.stride()),
        bool(is_causal),
        None if scale is None else float(scale),
    )


def _match_indices(a, tensors):
    """Map each tensor to the (unique) position in args sharing its data_ptr."""
    out = []
    for t in tensors:
        hit = None
        for i, x in enumerate(a):
            if isinstance(x, torch.Tensor) and x.data_ptr() == t.data_ptr():
                if hit is not None:
                    hit = None  # ambiguous
                    break
                hit = i
        if hit is None:
            return None
        out.append(hit)
    return out


def _make_glue(batch_size, seq_len_q, seq_len_k, device):
    cum_q = torch.tensor(
        [0, seq_len_q] * batch_size, dtype=torch.int32, device=device
    ).reshape(batch_size, 2)
    cum_k = torch.tensor(
        [0, seq_len_k] * batch_size, dtype=torch.int32, device=device
    ).reshape(batch_size, 2)
    philox_seed = torch.tensor([0], dtype=torch.int64, device=device)
    philox_offset = torch.tensor([0], dtype=torch.int64, device=device)
    debug = torch.empty(0, dtype=torch.float16, device=device)
    return {
        "cum_q": cum_q,
        "cum_k": cum_k,
        "seed": philox_seed,
        "off": philox_offset,
        "debug": debug,
    }


def _capture_and_delegate(jf, call):
    cap = {}
    orig = jf.run

    def hook(*a, **k):
        if "a" not in cap:
            cap["a"] = tuple(a)
            cap["kw"] = dict(k)
        return orig(*a, **k)

    # NOTE: `triton.runtime.driver` the module is shadowed on the package by the
    # DriverConfig instance; resolve the instance the same way jit.py does.
    drv_cfg = getattr(importlib.import_module("triton.runtime"), "driver")
    launcher_cls = getattr(drv_cfg.active, "launcher_cls_xpu", None) or getattr(
        drv_cfg.active, "launcher_cls", None
    )
    orig_calls = launcher_cls.__call__ if launcher_cls is not None else None

    def call_hook(launcher_self, *a, **k):
        if "launcher" not in cap:
            cap["launcher"] = launcher_self
            orig_launch = launcher_self.launch

            def launch_hook(*la):
                if "a2" not in cap:
                    cap["a2"] = tuple(la)
                return orig_launch(*la)

            cap["orig_launch"] = orig_launch
            launcher_self.launch = launch_hook
        return orig_calls(launcher_self, *a, **k)

    jf.run = hook
    if orig_calls is not None:
        launcher_cls.__call__ = call_hook
    try:
        ret = call()
    finally:
        jf.run = orig
        if orig_calls is not None:
            launcher_cls.__call__ = orig_calls
        lself = cap.get("launcher")
        if lself is not None and "orig_launch" in cap:
            try:
                lself.launch = cap["orig_launch"]
            except Exception:
                pass
    return ret, cap


def _generic_impl(
    query, key, value, attn_bias, dropout_p, is_causal, return_debug_mask, scale
):
    output, logsumexp = _sdpa_forward_with_lse(
        query,
        key,
        value,
        attn_bias,
        dropout_p,
        is_causal,
        scale,
        enable_gqa=(query.shape[1] != key.shape[1]),
    )
    if logsumexp is None:
        logsumexp = _sdpa_logsumexp(query, key, is_causal, scale, attn_bias)

    batch_size = query.shape[0]
    seq_len_q = query.shape[2]
    seq_len_k = key.shape[2]

    cum_seq_q = torch.tensor(
        [0, seq_len_q] * batch_size, dtype=torch.int32, device=query.device
    ).reshape(batch_size, 2)
    cum_seq_k = torch.tensor(
        [0, seq_len_k] * batch_size, dtype=torch.int32, device=key.device
    ).reshape(batch_size, 2)
    max_q = seq_len_q
    max_k = seq_len_k
    philox_seed = torch.tensor([0], dtype=torch.int64, device=query.device)
    philox_offset = torch.tensor([0], dtype=torch.int64, device=query.device)
    if return_debug_mask:
        debug_attn_mask = torch.zeros(
            (batch_size, query.shape[1], seq_len_q, seq_len_k),
            dtype=query.dtype,
            device=query.device,
        )
    else:
        debug_attn_mask = torch.empty(0, dtype=query.dtype, device=query.device)

    return (
        output,
        logsumexp,
        cum_seq_q,
        cum_seq_k,
        max_q,
        max_k,
        philox_seed,
        philox_offset,
        debug_attn_mask,
    )


def _replay(rec, query, key, value):
    out = torch.empty_like(query, dtype=value.dtype)
    lse = torch.empty_like(rec["lse_ref"])
    launched = False
    if "launch" in rec:
        try:
            cur = torch.cuda.current_stream().cuda_stream
            if cur == rec["stream2"]:
                a2 = list(rec["a2"])
                a2[rec["j_q"]] = query
                a2[rec["j_k"]] = key
                a2[rec["j_v"]] = value
                a2[rec["j_o"]] = out
                a2[rec["j_lse"]] = lse
                rec["launch"](*a2)
                launched = True
        except Exception:
            launched = False
    if not launched:
        a = list(rec["a"])
        a[rec["i_q"]] = query
        a[rec["i_k"]] = key
        a[rec["i_v"]] = value
        a[rec["i_o"]] = out
        a[rec["i_lse"]] = lse
        rec["jf"].run(*a, **rec["kw"])
    g = rec["glue"]
    return (
        out,
        lse,
        g["cum_q"],
        g["cum_k"],
        rec["max_q"],
        rec["max_k"],
        g["seed"],
        g["off"],
        g["debug"],
    )


def _scaled_dot_product_fused_attention_overrideable(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attn_bias: torch.Tensor = None,
    dropout_p: float = 0.0,
    is_causal: bool = False,
    return_debug_mask: bool = False,
    scale: float = None,
):
    """FlagGems implementation of aten::_scaled_dot_product_fused_attention_overrideable.

    Computes scaled dot-product attention with the interface expected by
    aten::_scaled_dot_product_fused_attention_overrideable.

    Args:
        query: (batch, num_heads, seq_len_q, head_dim)
        key: (batch, num_kv_heads, seq_len_kv, head_dim)
        value: (batch, num_kv_heads, seq_len_kv, head_dim)
        attn_bias: Optional attention bias tensor
        dropout_p: Dropout probability (currently only 0.0 is supported)
        is_causal: Whether to use causal masking
        return_debug_mask: Whether to return debug attention mask
        scale: Optional scale factor for QK dot product

    Returns:
        Tuple of (output, logsumexp, cum_seq_q, cum_seq_k, max_q, max_k,
                  philox_seed, philox_offset, debug_attn_mask)
    """
    logger.debug("GEMS _SCALED_DOT_PRODUCT_FUSED_ATTENTION_OVERRIDEABLE")

    assert dropout_p == 0.0, "Only dropout_p=0.0 is supported"

    if not _ENABLED or not _eligible(
        query, key, value, attn_bias, dropout_p, return_debug_mask
    ):
        return _generic_impl(
            query, key, value, attn_bias, dropout_p, is_causal, return_debug_mask, scale
        )

    jf = _attn_jit_function()
    if jf is None:
        return _generic_impl(
            query, key, value, attn_bias, dropout_p, is_causal, return_debug_mask, scale
        )

    global _LAST
    last = _LAST
    flags = (is_causal, scale)
    rec = None
    kk = None
    if (
        last is not None
        and query is last[0]
        and key is last[1]
        and value is last[2]
        and flags == last[3]
    ):
        rec = last[4]
    if rec is None:
        kk = _key_of(query, key, value, is_causal, scale)
        with _LOCK:
            rec = _CACHE.get(kk)
        if rec is not None:
            _LAST = (query, key, value, flags, rec)
    if rec is not None:
        try:
            return _replay(rec, query, key, value)
        except Exception:
            with _LOCK:
                _CACHE.pop(kk, None)
            rec = None

    # first call for this key: run the generic path and capture the deepest launch
    if kk is None:
        kk = _key_of(query, key, value, is_causal, scale)
    ret, cap = _capture_and_delegate(
        jf,
        lambda: _generic_impl(
            query, key, value, attn_bias, dropout_p, is_causal, return_debug_mask, scale
        ),
    )
    a = cap.get("a")
    if a:
        out_ref, lse_ref = ret[0], ret[1]
        if torch.is_tensor(lse_ref):
            idx = _match_indices(a, [query, key, value, out_ref, lse_ref])
            if idx is not None:
                rec = {
                    "a": a,
                    "kw": cap["kw"],
                    "jf": jf,
                    "i_q": idx[0],
                    "i_k": idx[1],
                    "i_v": idx[2],
                    "i_o": idx[3],
                    "i_lse": idx[4],
                    "lse_ref": lse_ref,
                    "glue": _make_glue(
                        query.shape[0], query.shape[2], key.shape[2], query.device
                    ),
                    "max_q": ret[4],
                    "max_k": ret[5],
                }
                a2 = cap.get("a2")
                if a2 is not None:
                    jdx = _match_indices(a2, [query, key, value, out_ref, lse_ref])
                    if jdx is not None:
                        rec["launch"] = cap["orig_launch"]
                        rec["a2"] = a2
                        rec["j_q"], rec["j_k"], rec["j_v"], rec["j_o"], rec["j_lse"] = (
                            jdx
                        )
                        rec["stream2"] = a2[3]
                with _LOCK:
                    if len(_CACHE) >= _MAX_KEYS:
                        _CACHE.clear()
                    _CACHE[kk] = rec
                _LAST = (query, key, value, flags, rec)
    return ret
