# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from .attention import scaled_dot_product_attention_forward  # [attn-route 2026-09-16]

logger = logging.getLogger(__name__)


_SDPA_LSE_MASK_CACHE = {}


def _sdpa_causal_add_mask(sq, sk, dtype, device):
    """[attn-route 2026-09-17 v3] cached additive causal mask (0 / -1.0e6)."""
    key = (sq, sk, str(dtype), str(device))
    m = _SDPA_LSE_MASK_CACHE.get(key)
    if m is None:
        import numpy as np

        rows = np.arange(sq).reshape(-1, 1)
        cols = np.arange(sk).reshape(1, -1)
        add = np.where(cols <= rows + (sk - sq), 0.0, -1.0e6).astype(np.float32)
        m = torch.from_numpy(add).to(device=device, dtype=dtype)
        _SDPA_LSE_MASK_CACHE[key] = m
    return m


def _sdpa_logsumexp(query, key, is_causal, scale, attn_mask=None):
    """[attn-route 2026-09-17 v3] xpu-side lse; causal via cached additive mask."""
    sm_scale = scale if scale is not None else 1.0 / (query.shape[-1] ** 0.5)
    qf = query.float()
    kf = key.float()
    if qf.shape[1] != kf.shape[1]:
        kf = kf.repeat_interleave(qf.shape[1] // kf.shape[1], dim=1)
    scores = torch.matmul(qf, kf.transpose(-1, -2)) * sm_scale
    if attn_mask is not None:
        scores = scores + attn_mask.float()
    if is_causal:
        scores = scores + _sdpa_causal_add_mask(
            scores.shape[-2], scores.shape[-1], scores.dtype, scores.device
        )
    return torch.logsumexp(scores, dim=-1)


def _sdpa_forward_with_lse(
    query, key, value, attn_mask, dropout_p, is_causal, scale, enable_gqa=False
):
    """[attn-route v4 2026-09-17] Run the kunlunxin sdpa forward and recover the
    kernel's own softmax_lse from the autograd ctx (save_for_backward order:
    query, key, value, o, M). Zero recompute; avoids the flaky xblas JIT-C
    bmm path used by earlier recompute-based helpers."""
    need_grad = any(t.requires_grad for t in (query, key, value))
    if not need_grad:
        q_in = query.detach().requires_grad_(True)
        with torch.enable_grad():
            out = scaled_dot_product_attention_forward(
                q_in,
                key,
                value,
                attn_mask=attn_mask,
                dropout_p=dropout_p,
                is_causal=is_causal,
                scale=scale,
                enable_gqa=enable_gqa,
            )
    else:
        out = scaled_dot_product_attention_forward(
            query,
            key,
            value,
            attn_mask=attn_mask,
            dropout_p=dropout_p,
            is_causal=is_causal,
            scale=scale,
            enable_gqa=enable_gqa,
        )
    lse = None
    gf = getattr(out, "grad_fn", None)
    if gf is not None:
        saved = getattr(gf, "saved_tensors", None) or ()
        if len(saved):
            cand = saved[-1]
            if (
                torch.is_tensor(cand)
                and cand.dim() == 3
                and cand.dtype == torch.float32
            ):
                lse = cand
    if not need_grad:
        out = out.detach()
    return out, lse


def _scaled_dot_product_cudnn_attention(
    query,
    key,
    value,
    attn_bias=None,
    compute_log_sumexp=True,
    dropout_p=0.0,
    is_causal=False,
    return_debug_mask=False,
    *,
    scale=None,
):
    """
    Scaled dot product attention using FlagGems Triton kernels.

    This function wraps the FlagGems attention implementation to provide
    the same interface as torch._scaled_dot_product_cudnn_attention.

    Args:
        query: Query tensor of shape (batch, num_heads, seq_len_q, head_dim)
        key: Key tensor of shape (batch, num_heads, seq_len_k, head_dim)
        value: Value tensor of shape (batch, num_heads, seq_len_k, head_dim)
        attn_bias: Optional attention bias tensor
        compute_log_sumexp: Whether to compute and return log-sum-exp values
        dropout_p: Dropout probability (currently must be 0.0)
        is_causal: Whether to apply causal masking
        return_debug_mask: Whether to return debug attention mask
        scale: Optional scale factor for attention scores

    Returns:
        tuple: (output, logsumexp, cum_seq_q, cum_seq_k, max_q, max_k,
                philox_seed, philox_offset, debug_attn_mask)
    """
    logger.debug("GEMS _SCALED_DOT_PRODUCT_CUDNN_ATTENTION")

    # Convert attn_bias to attn_mask if provided
    attn_mask = attn_bias

    # [attn-route v4 2026-09-17] real lse from ctx; recompute only as fallback
    if compute_log_sumexp:
        output, logsumexp = _sdpa_forward_with_lse(
            query, key, value, attn_mask, dropout_p, is_causal, scale, enable_gqa=False
        )
        if logsumexp is None:
            logsumexp = _sdpa_logsumexp(query, key, is_causal, scale, attn_mask)
    else:
        output = scaled_dot_product_attention_forward(
            query,
            key,
            value,
            attn_mask=attn_mask,
            dropout_p=dropout_p,
            is_causal=is_causal,
            scale=scale,
            enable_gqa=False,
        )
        logsumexp = torch.empty(0, device=query.device, dtype=torch.float32)

    # Create placeholder tensors for cumulative sequence lengths
    # These are used for variable-length sequences, which we don't handle here
    cum_seq_q = torch.empty(0, device=query.device, dtype=torch.int32)
    cum_seq_k = torch.empty(0, device=query.device, dtype=torch.int32)

    # Get max sequence lengths
    max_q = query.shape[2]
    max_k = key.shape[2]

    # Philox seed and offset for dropout (currently not used as dropout_p must be 0)
    philox_seed = torch.empty((), device=query.device, dtype=torch.int64)
    philox_offset = torch.empty((), device=query.device, dtype=torch.int64)

    # Debug attention mask
    if return_debug_mask:
        # Create a debug mask of the appropriate shape
        batch = query.shape[0]
        num_heads = query.shape[1]
        seq_len_q = query.shape[2]
        seq_len_k = key.shape[2]
        debug_attn_mask = torch.zeros(
            (batch, num_heads, seq_len_q, seq_len_k),
            device=query.device,
            dtype=query.dtype,
        )
    else:
        debug_attn_mask = torch.empty(0, device=query.device, dtype=query.dtype)

    return (
        output,
        logsumexp,
        cum_seq_q,
        cum_seq_k,
        max_q,
        max_k,
        philox_seed,
        philox_offset,
        debug_attn_mask,
    )
