# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def _cdist_forward(x1, x2, p=2.0, compute_mode=None):
    """Compute the p-norm distance between each pair of the two collections of row vectors."""
    logger.debug("GEMS CDIST_FORWARD")

    assert x1.dtype in (
        torch.float32,
    ), f"Unsupported dtype '{x1.dtype}'. Only float32 is supported for cdist."

    from flag_gems.runtime.backend._metax.ops._cdist_forward import (
        _cdist_forward as _metax_cdist_forward,
    )
    return _metax_cdist_forward(x1, x2, p, compute_mode)


__all__ = ["_cdist_forward"]
