# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

from flag_gems.ops.conv1d import conv1d
from flag_gems.ops.conv2d import conv2d
from flag_gems.ops.conv3d import conv3d
from flag_gems.ops.conv_transpose1d import conv_transpose1d
from flag_gems.ops.conv_transpose2d import conv_transpose2d

logger = logging.getLogger(__name__)


def _convolution(
    input,
    weight,
    bias,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
    benchmark,
    deterministic,
    cudnn_enabled,
    allow_tf32,
):
    logger.debug("GEMS _CONVOLUTION")

    spatial_dims = weight.ndim - 2

    if transposed:
        if spatial_dims == 1:
            s = stride[0] if isinstance(stride, (list, tuple)) else stride
            p = padding[0] if isinstance(padding, (list, tuple)) else padding
            op = (
                output_padding[0]
                if isinstance(output_padding, (list, tuple))
                else output_padding
            )
            d = dilation[0] if isinstance(dilation, (list, tuple)) else dilation
            return conv_transpose1d(input, weight, bias, s, p, op, groups, d)
        elif spatial_dims == 2:
            return conv_transpose2d(
                input, weight, bias, stride, padding, output_padding, groups, dilation
            )
        else:
            raise NotImplementedError(
                f"Transposed convolution is not supported for {spatial_dims}D. "
                f"Only 1D and 2D transposed convolutions are supported."
            )

    if spatial_dims == 1:
        s = stride[0] if isinstance(stride, (list, tuple)) else stride
        p = padding[0] if isinstance(padding, (list, tuple)) else padding
        d = dilation[0] if isinstance(dilation, (list, tuple)) else dilation
        return conv1d(input, weight, bias, s, p, d, groups)
    elif spatial_dims == 2:
        return conv2d(input, weight, bias, stride, padding, dilation, groups)
    elif spatial_dims == 3:
        return conv3d(input, weight, bias, stride, padding, dilation, groups)
    else:
        raise ValueError(
            f"Unsupported convolution dimension: {spatial_dims}. "
            f"Only 1D, 2D, and 3D convolutions are supported."
        )
