# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@triton.jit
def _round_half_to_even(x):
    """Round to nearest with ties to even (banker's rounding). x must be fp32."""
    r = tl.floor(x)
    d = x - r  # fractional part
    is_odd = tl.abs(r - 2.0 * tl.floor(r / 2.0)) > 0.5
    return tl.where((d > 0.5) | ((tl.abs(d - 0.5) < 1e-10) & is_odd), r + 1.0, r)


@pointwise_dynamic(
    is_tensor=[True, False, False, False, False, False],
    num_outputs=2,
    promotion_methods=[
        (0, "DEFAULT"),
        (0, "ALWAYS_BOOL"),
    ],
)
@triton.jit
def _fake_quantize_per_tensor_affine_cachemask_tensor_qparams_kernel(
    x,
    scale,
    zero_point,
    fake_quant_enabled,
    quant_min,
    quant_max,
):
    # Compute in fp32 for numerical stability across fp16/bf16 inputs.
    x_fp32 = x.to(tl.float32)
    q = _round_half_to_even(x_fp32 / scale + zero_point)
    in_range = (q >= quant_min) & (q <= quant_max)
    q_clamped = tl.minimum(tl.maximum(q, quant_min), quant_max)
    quantized = scale * (q_clamped - zero_point)
    # When fake quantization is disabled, pass through the input and report
    # the whole tensor as in-range (mask all True).
    output = tl.where(fake_quant_enabled, quantized.to(x.dtype), x)
    mask = tl.where(fake_quant_enabled, in_range, True)
    return output, mask


def _fake_quantize_per_tensor_affine_cachemask_tensor_qparams(
    self, scale, zero_point, fake_quant_enabled, quant_min, quant_max
):
    logger.debug("GEMS FAKE_QUANTIZE_PER_TENSOR_AFFINE_CACHEMASK_TENSOR_QPARAMS")
    scale_val = scale.item()
    zero_point_val = zero_point.item()
    fake_quant_enabled_val = bool(fake_quant_enabled.item())
    out, mask = _fake_quantize_per_tensor_affine_cachemask_tensor_qparams_kernel(
        self, scale_val, zero_point_val, fake_quant_enabled_val, quant_min, quant_max
    )
    return out, mask
