# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import importlib
import logging
import os
from functools import lru_cache
from typing import Any, Callable, Mapping, Tuple

import torch

from flag_gems.runtime import torch_device_fn
from flag_gems.utils.code_cache import code_cache_dir
from flag_gems.utils.code_utils import IndentedBuffer, write_atomic

logger = logging.getLogger(__name__)


def generate_imports(code: IndentedBuffer) -> IndentedBuffer:
    code.writeline("import torch")
    code.writeline("import triton")
    code.writeline("import triton.language as tl")
    code.newline()
    code.writeline("from flag_gems.utils import libentry")
    code.writeline("from flag_gems.utils import triton_lang_extension as ext")
    code.newline()
    code.newline()
    return code


def generate_kernel(
    rank: int, kernel_name: str, code: IndentedBuffer
) -> IndentedBuffer:
    code.newline()
    code.writeline("@libentry()")
    code.writeline("@triton.jit")
    code.writeline(f"def {kernel_name}(")
    with code.indent():
        args = ["index_ptr, ", "out_ptr, ", "nnz, ", "dim, "]
        args += [f"dim_size{i}, " for i in range(rank)]
        args += ["dim_count: tl.constexpr, ", "BLOCK_SIZE: tl.constexpr, "]
        code.writelines(args)
    code.writeline("):")

    with code.indent():
        code.writeline("pid = ext.program_id(0)")
        code.writeline(
            "offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE).to(tl.int64)"
        )
        code.writeline("mask = offs < nnz")
        code.writeline(
            "idx_gather = tl.load(index_ptr + offs, mask=mask, other=0).to(tl.int64)"
        )
        code.writeline("cur = offs")
        for d in range(rank - 1, -1, -1):
            code.writeline(f"coord{d} = cur % dim_size{d}")
            code.writeline(f"cur = cur // dim_size{d}")
            code.writeline(f"store_val{d} = tl.where({d} == dim, idx_gather, coord{d})")
            code.writeline(
                f"tl.store(out_ptr + {d} * nnz + offs, store_val{d}, mask=mask)"
            )
    code.newline()
    code.newline()
    return code


def generate_wrapper(
    rank: int, wrapper_name: str, kernel_name: str, code: IndentedBuffer
) -> IndentedBuffer:
    code.writeline(
        f"def {wrapper_name}(index_flat, out, nnz, dim, dim_count, dim_sizes):"
    )
    with code.indent():
        code.writeline("BLOCK_SIZE = 1024")
        code.writeline("grid = (triton.cdiv(nnz, BLOCK_SIZE),)")
        code.writeline(f"{kernel_name}[grid](")
        with code.indent():
            args = ["index_flat, ", "out, ", "nnz, ", "dim, "]
            args += [f"dim_sizes[{i}], " for i in range(rank)]
            args += ["dim_count, ", "BLOCK_SIZE, "]
            code.writelines(args)
        code.writeline(")")
    code.newline()
    code.newline()
    return code


def generate_code(
    inputs: Tuple[Any], wrapper_name: str, kernel_name: str, code: IndentedBuffer
) -> IndentedBuffer:
    rank = inputs[0]
    code = generate_imports(code)
    code = generate_kernel(rank, kernel_name, code)
    code = generate_wrapper(rank, wrapper_name, kernel_name, code)
    return code


class GatherSparseBackwardFunction:
    def __init__(self):
        self.pid = os.getpid()
        self.overloads: Mapping[str, Callable] = {}

    def __call__(self, *args, **kwargs):
        key = self.arg_key(*args)
        if key in self.overloads:
            overload = self.overloads[key]
        else:
            rank = args[4]  # dim_count is the 5th positional arg
            code = IndentedBuffer()
            code = generate_code(
                (rank,),
                "_gather_sparse_backward_wrapper",
                "_gather_sparse_backward_kernel",
                code,
            )
            file_name = f"_gather_sparse_backward_rank_{key}.py"
            file_path = code_cache_dir() / file_name
            write_atomic(file_path, code.getvalue())

            spec = importlib.util.spec_from_file_location(
                f"_gather_sparse_backward_gen_rank_{key}", file_path
            )
            m = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(m)
            overload = getattr(m, "_gather_sparse_backward_wrapper")
            self.overloads[key] = overload

        return overload(*args, **kwargs)

    def arg_key(self, *args):
        return str(args[4])


@lru_cache(maxsize=1)
def _kernel_func() -> "GatherSparseBackwardFunction":
    # Lazily instantiated inside a function (not a module-level global) so the
    # code-gen overload cache lives on the returned singleton, per reviewer
    # guidance to avoid module-level global state.
    return GatherSparseBackwardFunction()


def _gather_sparse_backward(self, dim, index, grad):
    logger.debug("GEMS _GATHER_SPARSE_BACKWARD")

    ndim = self.ndim
    if ndim != index.ndim:
        raise IndexError(
            f"self and index must have the same number of dimensions, "
            f"got self.ndim = {ndim} and index.ndim = {index.ndim}"
        )

    # Normalize the gather dimension (matches aten's `maybe_wrap_dim`).
    dim = dim if dim >= 0 else dim + ndim

    index = index.contiguous()
    grad = grad.contiguous()
    nnz = index.numel()

    # The sparse values are simply the flattened gradient.
    values = grad.reshape(-1)

    # Build the sparse COO indices tensor of shape [ndim, nnz].
    if nnz == 0:
        sparse_indices = torch.empty((ndim, 0), dtype=torch.int64, device=index.device)
        out = torch.sparse_coo_tensor(
            sparse_indices, values, self.size(), device=self.device
        )
        return out

    index_flat = index.reshape(-1)
    if index_flat.dtype != torch.int64:
        index_flat = index_flat.to(torch.int64)

    sparse_indices = torch.empty((ndim, nnz), dtype=torch.int64, device=index.device)

    dim_sizes = tuple(int(s) for s in index.shape)
    with torch_device_fn.device(index.device):
        _kernel_func()(index_flat, sparse_indices, nnz, dim, ndim, dim_sizes)

    out = torch.sparse_coo_tensor(
        sparse_indices, values, self.size(), device=self.device
    )
    return out
