# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _unpad_contiguous_prefix_kernel(
    padded,
    metadata,
    values,
    RANK: tl.constexpr,
    PAD_SHAPE_BASE: tl.constexpr,
    OFFSETS_BASE: tl.constexpr,
    PAD_BATCH_STRIDE: tl.constexpr,
    BLOCK: tl.constexpr,
):
    """Fast path: only the first (ragged) dimension differs per component.

    Component ``b`` of the result is the contiguous ``[len_b, *D]`` prefix of
    ``padded[b]`` (every trailing dim is full), so the whole component is one
    contiguous run copied from ``padded[b]`` into
    ``values[storage_offsets[b]]``.
    """
    b = tl.program_id(0).to(tl.int64)
    chunk = tl.program_id(1)

    start = tl.load(metadata + OFFSETS_BASE + b)

    # Component numel == len_b * product(full trailing dims). The ragged length
    # comes from the first size column; the trailing sizes are equal to the
    # padded tensor's trailing dims (guaranteed by the fast-path selection in
    # the host code), so multiply by the padded trailing shape.
    n = tl.load(metadata + b * RANK).to(tl.int64)
    for d in tl.static_range(1, RANK):
        n *= tl.load(metadata + PAD_SHAPE_BASE + d).to(tl.int64)

    idx = (chunk * BLOCK + tl.arange(0, BLOCK)).to(tl.int64)
    mask = idx < n

    src = b * PAD_BATCH_STRIDE + idx
    dst = start + idx

    x = tl.load(padded + src, mask=mask)
    tl.store(values + dst, x, mask=mask)


@triton.jit
def _unpad_general_kernel(
    padded,
    metadata,
    values,
    B: tl.constexpr,
    RANK: tl.constexpr,
    OFFSETS_BASE: tl.constexpr,
    PAD_SHAPE_BASE: tl.constexpr,
    PAD_BATCH_STRIDE: tl.constexpr,
    BLOCK: tl.constexpr,
):
    """General path: any trailing dimension may be ragged.

    Maps a compact flat index inside a nested component back to its coordinate
    using the component's own ``sizes``, then walks the padded tensor's shape to
    recover the strided source offset. This handles nested sizes whose trailing
    dimensions differ from the padded tensor's, e.g. ``[[3, 4], [5, 2]]`` inside a
    ``[2, 8, 4]`` padded tensor.
    """
    b = tl.program_id(0).to(tl.int64)
    chunk = tl.program_id(1)

    start = tl.load(metadata + OFFSETS_BASE + b)

    # Component numel is the product of its own per-dim sizes.
    component_numel = tl.full([], 1, tl.int64)
    for d in tl.static_range(RANK):
        component_numel *= tl.load(metadata + b * RANK + d).to(tl.int64)

    local = (chunk * BLOCK + tl.arange(0, BLOCK)).to(tl.int64)
    mask = local < component_numel

    rem = local
    src_inner = tl.zeros(local.shape, dtype=tl.int64)
    padded_stride = tl.full([], 1, tl.int64)

    for d in tl.static_range(RANK - 1, -1, -1):
        size_d = tl.load(metadata + b * RANK + d).to(tl.int64)
        # Avoid div-by-zero for empty dimensions.
        safe_size = tl.maximum(size_d, 1)

        coord = rem % safe_size
        rem = rem // safe_size

        src_inner += coord * padded_stride

        padded_dim = tl.load(metadata + PAD_SHAPE_BASE + d).to(tl.int64)
        padded_stride *= padded_dim

    src = b * PAD_BATCH_STRIDE + src_inner
    dst = start + local

    x = tl.load(padded + src, mask=mask)
    tl.store(values + dst, x, mask=mask)


def _has_full_suffix(nt_example, padded, rank):
    """True when every trailing dim (d >= 1) of the example is regular and
    equals the padded tensor's corresponding trailing dimension.

    Uses the NestedTensor's cached ``opt_size_`` lookup (``nt_example.size(d)``),
    which raises for an irregular dimension; the irregular case is not the hot
    path, so using an exception for control flow is acceptable here.
    """
    for d in range(1, rank):
        try:
            regular_size = int(nt_example.size(d + 1))
        except RuntimeError:
            return False
        if regular_size != padded.shape[d + 1]:
            return False
    return True


def _nested_from_padded_and_nested_example(padded, nt_example):
    """Create a legacy NestedTensor from a padded dense tensor.

    ``nt_example`` only supplies the per-component ``sizes`` metadata; component
    ``b`` of the result is ``padded[b, :sizes[b, 0], ..., :sizes[b, -1]]`` packed
    contiguously into a flat buffer. The result is a legacy (``torch.strided``
    layout) NestedTensor, matching the reference aten implementation.
    """
    logger.debug("GEMS _NESTED_FROM_PADDED_AND_NESTED_EXAMPLE")

    if nt_example.layout != torch.strided or not nt_example.is_nested:
        raise RuntimeError(
            "_nested_from_padded_and_nested_example expects a legacy NestedTensor "
            "example"
        )

    # CPU int64 (B, rank) metadata; cheap, no GPU sync.
    sizes = nt_example._nested_tensor_size()
    B = sizes.shape[0]
    rank = sizes.shape[1]

    if padded.dim() != rank + 1:
        raise RuntimeError("padded dimension does not match nested component dimension")

    # PyTorch ships a specialized CUDA kernel (remove_padding_kernelLauncher) for
    # the 3D + fp16/fp32 regime that runs in ~10 us, far below anything a Triton
    # kernel plus Python-side metadata preparation can reach. Route those cases
    # to the native implementation instead of regressing them. ``_nested_from_padded``
    # is not registered in FlagGems, so this does not recurse into this op.
    if padded.dim() == 3 and padded.dtype in (torch.float16, torch.float32):
        return torch.ops.aten._nested_from_padded.default(padded, sizes, False)

    padded = padded.contiguous()

    # Empty nested tensor: upstream _nested_from_padded segfaults on B == 0 on
    # current torch, so handle it explicitly here.
    if B == 0:
        nested_strides = torch.empty_like(sizes)
        storage_offsets = torch.empty((0,), dtype=torch.int64)
        values = padded.new_empty((0,))
        return torch.ops.aten._nested_view_from_buffer.default(
            values, sizes, nested_strides, storage_offsets
        )

    # One C++ call replaces the previous Python prod / cumsum / for-loop / .item()
    # pipeline. Returns contiguous (per-component) strides and storage offsets.
    nested_strides, storage_offsets = (
        torch.ops.aten._nested_compute_contiguous_strides_offsets.default(sizes)
    )

    # ``nt_example.numel()`` sums the component numels in C++ and returns a Python
    # int. Allocate the exact backing buffer -- do not over-allocate, since
    # _nested_view_from_buffer exposes the full storage to downstream readers.
    total_numel = nt_example.numel()
    values = padded.new_empty((total_numel,))

    if total_numel == 0:
        return torch.ops.aten._nested_view_from_buffer.default(
            values, sizes, nested_strides, storage_offsets
        )

    # Pack all GPU metadata into a single H2D copy: [sizes, storage_offsets,
    # padded_shape]. The kernels index into it via the constexpr bases below.
    OFFSETS_BASE = B * rank
    PAD_SHAPE_BASE = OFFSETS_BASE + B
    padded_shape_cpu = torch.tensor(padded.shape[1:], dtype=torch.int64)
    metadata = torch.cat([sizes.reshape(-1), storage_offsets, padded_shape_cpu]).to(
        padded.device, non_blocking=True
    )

    # 256 threads/block balances launch overhead against occupancy: the
    # un-pad copy is memory-bound and the grid already parallelizes over
    # (batch, chunk), so a larger block would only waste idle lanes on the
    # typically-small components.
    BLOCK = 256

    suffix_full = _has_full_suffix(nt_example, padded, rank)

    # Upper bound on per-component capacity. Using ``padded.stride(0)`` (the
    # per-batch row length) avoids a ``component_numel.max().item()`` sync and
    # only launches extra fully-masked blocks in high-padding cases, which stay
    # at the kernel-launch floor.
    max_capacity = padded.stride(0)
    grid = (B, triton.cdiv(max_capacity, BLOCK))

    if suffix_full:
        _unpad_contiguous_prefix_kernel[grid](
            padded,
            metadata,
            values,
            RANK=rank,
            PAD_SHAPE_BASE=PAD_SHAPE_BASE,
            OFFSETS_BASE=OFFSETS_BASE,
            PAD_BATCH_STRIDE=padded.stride(0),
            BLOCK=BLOCK,
        )
    else:
        _unpad_general_kernel[grid](
            padded,
            metadata,
            values,
            B=B,
            RANK=rank,
            OFFSETS_BASE=OFFSETS_BASE,
            PAD_SHAPE_BASE=PAD_SHAPE_BASE,
            PAD_BATCH_STRIDE=padded.stride(0),
            BLOCK=BLOCK,
        )

    # Reconstruct the legacy NestedTensor directly from the packed values.
    return torch.ops.aten._nested_view_from_buffer.default(
        values, sizes, nested_strides, storage_offsets
    )


__all__ = ["_nested_from_padded_and_nested_example"]
