# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List, Optional

import torch

logger = logging.getLogger(__name__)


def _nested_tensor_from_tensor_list(
    tensor_list: List[torch.Tensor],
    dtype: Optional[torch.dtype] = None,
    layout: Optional[torch.layout] = None,
    device: Optional[torch.device] = None,
    pin_memory: Optional[bool] = None,
):
    """Low-level operation that constructs a nested tensor from a list of
    tensors. Each element of ``tensor_list`` becomes a component of the
    resulting nested tensor."""

    logger.debug("GEMS _NESTED_TENSOR_FROM_TENSOR_LIST")
    # Build each component honouring the optional dtype/device overrides. The
    # default strided construction ``torch.nested.nested_tensor`` re-dispatches
    # into this same aten op (infinite recursion once FlagGems overrides it), so
    # pack the components into a jagged values buffer explicitly. Both
    # ``torch.nested.nested_tensor(..., layout=torch.jagged)`` and the lower
    # level ``nested_tensor_from_jagged`` are equivalent, but the former loops
    # through a per-component copy; ``cat`` + explicit offsets assembles the
    # same buffer in a single bulk copy.
    components = []
    for t in tensor_list:
        comp = t
        if device is not None:
            comp = comp.to(device)
        if dtype is not None:
            comp = comp.to(dtype)
        components.append(comp)

    device_ = components[0].device
    lengths = [c.shape[0] for c in components]
    offsets_list = [sum(lengths[:i]) for i in range(len(lengths) + 1)]
    if device_.type == "cuda":
        # A pageable CPU -> GPU copy is a host-side synchronization point when
        # there is pending GPU work (e.g. the benchmark harness flushes the L2
        # cache right before timing), which would otherwise dominate the
        # measurement. Stage the offsets through pinned memory and enqueue an
        # asynchronous transfer so the copy overlaps with the pending work.
        offsets = torch.tensor(offsets_list, dtype=torch.int64, pin_memory=True).to(
            device_, non_blocking=True
        )
    else:
        offsets = torch.tensor(offsets_list, dtype=torch.int64, device=device_)
    values = torch.cat(components, dim=0)
    result = torch.nested.nested_tensor_from_jagged(values, offsets=offsets)
    if pin_memory:
        result = result.pin_memory()
    return result


__all__ = ["_nested_tensor_from_tensor_list"]
