# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _nested_from_padded_remove_padding_kernel(
    padded,
    values,
    offsets,
    PAD_BATCH_STRIDE: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Compacts a padded dense tensor into a flat buffer by removing the padding.

    ``offsets`` is the (B+1)-element exclusive prefix sum of per-component numel
    in element units, so component ``b`` spans ``[offsets[b], offsets[b+1])``. The
    grid is ``(batch_size, num_chunks)``: program ``b`` along axis 0 owns batch
    element ``b``, and the axis-1 programs tile its contiguous real elements in
    ``BLOCK_SIZE``-sized chunks. The chunk count is bounded by
    ``PAD_BATCH_STRIDE`` (the padded row length) rather than ``max(lengths)``,
    so no host-side reduction is needed to size the grid; the extra blocks on
    short components are fully masked and stay at the kernel-launch floor.
    """
    b = tle.program_id(axis=0)
    chunk = tle.program_id(axis=1)

    start = tl.load(offsets + b)
    end = tl.load(offsets + b + 1)
    length = end - start

    idx = chunk * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = idx < length

    dst = start + idx
    src = b * PAD_BATCH_STRIDE + idx

    v = tl.load(padded + src, mask=mask)
    tl.store(values + dst, v, mask=mask)


def _nested_from_padded(padded, cpu_nested_shape_example, fuse_transform_0213=False):
    """Create a nested tensor from a padded dense tensor.

    ``cpu_nested_shape_example`` is an int64 tensor on CPU whose i-th row is the
    nested size ``[len_i, *inner_dims]`` of the i-th component. The returned nested
    tensor reuses the values of ``padded`` with the padding rows removed.
    """
    logger.debug("GEMS _NESTED_FROM_PADDED")

    if fuse_transform_0213:
        # (B, L, S, D) -> (B, S, L * D)
        padded = (
            padded.permute(0, 2, 1, 3)
            .contiguous()
            .view(padded.size(0), padded.size(2), padded.size(1) * padded.size(3))
        )

    padded = padded.contiguous()
    sizes = cpu_nested_shape_example.to(torch.int64)
    batch_size = padded.size(0)
    inner_dims = list(padded.shape[2:])

    inner_numel = 1
    for d in inner_dims:
        inner_numel *= d

    # One C++ call replaces the previous hand-rolled per-dim stride loop and two
    # cumsum calls: it returns the contiguous strides and the exclusive prefix
    # sum of per-component numel (element units) used as storage offsets.
    nested_strides, storage_offsets = (
        torch.ops.aten._nested_compute_contiguous_strides_offsets.default(sizes)
    )

    lengths = sizes[:, 0]
    total_len = int(lengths.sum().item())
    total = total_len * inner_numel
    values = torch.empty(total, dtype=padded.dtype, device=padded.device)

    # Build the (B+1)-element offset fence the kernel indexes as
    # ``[offsets[b], offsets[b+1])``. ``storage_offsets`` is length B (the
    # exclusive prefix sum); append the total as the closing fence so the kernel
    # can recover each component's length with one subtraction instead of a
    # separate ``lengths`` tensor. This replaces two tiny H2D copies (lengths +
    # row_offsets) with a single transfer.
    offset_fence = torch.cat(
        [storage_offsets, torch.tensor([total], dtype=torch.int64)]
    )
    offsets_dev = offset_fence.to(padded.device, non_blocking=True)

    # Size the chunk axis by ``padded.stride(0)`` (the padded row length in
    # elements) instead of ``lengths.max()``. This is a free upper bound on any
    # component's real-element count and avoids a host reduction; the extra
    # fully-masked blocks on shorter components stay at the kernel-launch floor.
    pad_batch_stride = padded.stride(0) // inner_numel * inner_numel
    num_chunks = triton.cdiv(pad_batch_stride, 1024)
    grid = lambda meta: (batch_size, num_chunks)
    _nested_from_padded_remove_padding_kernel[grid](
        padded,
        values,
        offsets_dev,
        PAD_BATCH_STRIDE=pad_batch_stride,
        # A fixed tile size avoids autotuning overhead for this simple
        # memory-bound un-pad copy. BLOCK_SIZE=1024 performed best among the
        # tested configurations on H20; the kernel is not the bottleneck of
        # this op (see profiling in the PR description), so autotune cost would
        # only add host overhead.
        BLOCK_SIZE=1024,
    )

    values = values.view(total_len, *inner_dims)

    return torch.ops.aten._nested_view_from_buffer.default(
        values.view(-1), sizes, nested_strides, storage_offsets
    )


__all__ = ["_nested_from_padded"]
