# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)

_BLOCK_SIZE = 1024
_MAX_RANK = 8


@triton.jit
def _reshape_copy_contig_kernel(
    src_ptr,
    dst_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Linear copy used when the input is contiguous.

    ``src_ptr`` is the input's data pointer, which already accounts for any
    storage offset, and for a contiguous input the logical (row-major) order
    coincides with the flat element order, so no strided gather is needed.
    """
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    offsets = offsets.to(tl.int64)
    values = tl.load(src_ptr + offsets, mask=mask)
    tl.store(dst_ptr + offsets, values, mask=mask)


@triton.jit
def _reshape_copy_strided_kernel(
    src_ptr,
    dst_ptr,
    s0,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    d0,
    d1,
    d2,
    d3,
    d4,
    d5,
    d6,
    d7,
    n_elements,
    RANK: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Gather the input's logical (row-major) order into contiguous storage.

    The destination is contiguous, so its flat offset is the output index. For
    each such index the matching source element is recovered by decomposing it
    along the *source* shape (row-major) and applying the *source* strides.
    ``src_ptr`` already carries the storage offset.
    """
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    offsets = offsets.to(tl.int64)

    src_strides = [s0, s1, s2, s3, s4, s5, s6, s7]
    src_dims = [d0, d1, d2, d3, d4, d5, d6, d7]

    rem = offsets
    src_offsets = tl.zeros_like(offsets)
    for j in tl.static_range(RANK - 1, -1, -1):
        idx = rem % src_dims[j]
        rem = rem // src_dims[j]
        src_offsets += idx * src_strides[j]

    values = tl.load(src_ptr + src_offsets, mask=mask)
    tl.store(dst_ptr + offsets, values, mask=mask)


def _reshape_copy(self: torch.Tensor, size):
    """Return a contiguous copy of ``self`` reshaped to ``size``.

    This mirrors ``aten::_reshape_copy``: the row-major logical order of the
    input is materialized into fresh contiguous storage, so the result is never
    a view and never aliases ``self``. Unlike ``_reshape_alias_copy`` no
    explicit stride is accepted (the layout is the input's logical order), and
    ``size`` may contain a single ``-1`` dimension that is inferred from the
    remaining dimensions and the input ``numel``, exactly like PyTorch's
    ``infer_size``. The requested ``size`` is validated against ``numel``.
    """
    logger.debug("GEMS _RESHAPE_COPY")

    requested = [int(s) for s in size]
    numel = self.numel()

    infer_dim = -1
    known = 1
    for i, s in enumerate(requested):
        if s == -1:
            if infer_dim != -1:
                raise RuntimeError("only one dimension can be inferred")
            infer_dim = i
        elif s < 0:
            raise RuntimeError(f"invalid shape dimension {s}")
        else:
            known *= s
    if infer_dim != -1:
        if known == 0:
            raise RuntimeError(
                f"shape '{requested}' is invalid for input of size {numel}"
            )
        requested[infer_dim] = numel // known

    computed = 1
    for s in requested:
        computed *= s
    if computed != numel:
        raise RuntimeError(f"shape '{requested}' is invalid for input of size {numel}")

    out = torch.empty(requested, dtype=self.dtype, device=self.device)
    if numel == 0:
        return out

    with torch_device_fn.device(self.device):
        if self.is_contiguous():
            grid = lambda meta: (triton.cdiv(numel, meta["BLOCK_SIZE"]),)
            _reshape_copy_contig_kernel[grid](
                self,
                out,
                numel,
                BLOCK_SIZE=_BLOCK_SIZE,
            )
            return out

        rank = self.dim()
        if rank > _MAX_RANK:
            raise RuntimeError(
                f"_reshape_copy supports at most {_MAX_RANK} dimensions, got {rank}"
            )
        src_strides = list(self.stride()) + [0] * (_MAX_RANK - rank)
        src_dims = list(self.shape) + [1] * (_MAX_RANK - rank)
        grid = lambda meta: (triton.cdiv(numel, meta["BLOCK_SIZE"]),)
        _reshape_copy_strided_kernel[grid](
            self,
            out,
            *src_strides,
            *src_dims,
            numel,
            RANK=rank,
            BLOCK_SIZE=_BLOCK_SIZE,
        )
    return out
