# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)

MAXBIT = 30


@triton.jit
def sobol_scramble_kernel(
    sobolstate_ptr, ltm_ptr, MAXBIT: tl.constexpr, BLOCK: tl.constexpr
):
    d = tl.program_id(0)

    arange = tl.arange(0, BLOCK)
    state_mask = arange < MAXBIT
    state_offsets = d * MAXBIT + arange
    state = tl.load(sobolstate_ptr + state_offsets, mask=state_mask, other=0)

    for j in tl.static_range(0, MAXBIT):
        # Load ltm row j
        ltm_row_offsets = d * MAXBIT * MAXBIT + j * MAXBIT + arange
        ltm_row = tl.load(ltm_ptr + ltm_row_offsets, mask=state_mask, other=0)

        # Compute parity: XOR of (ltm_row[k] & state[k]) for k < j (GF(2) matmul)
        k_mask = arange < j
        prod = ltm_row & state
        prod = tl.where(k_mask, prod, 0)
        parity = tl.sum(prod.to(tl.int32)) % 2

        # Update state[j] with computed parity
        state = tl.where(arange == j, state ^ parity, state)

    tl.store(sobolstate_ptr + state_offsets, state, mask=state_mask)


def _sobol_engine_scramble_(sobolstate, ltm, dimension):
    """
    Scramble Sobol quasi-random number generator state using Owen scrambling.

    Performs in-place matrix multiplication in GF(2) (binary field) for each dimension:
    state[d] = (ltm[d] @ state[d]) mod 2

    Args:
        sobolstate: (dimension, 30) int64 tensor - Sobol state to scramble in-place
        ltm: (dimension, 30, 30) int64 lower triangular matrix - scrambling transformation
        dimension: int - dimensionality of the Sobol sequence

    Returns:
        sobolstate: The mutated input tensor
    """
    logger.debug("GEMS _SOBOL_ENGINE_SCRAMBLE_")

    assert (
        sobolstate.dtype == torch.long
    ), f"sobolstate must be int64, got {sobolstate.dtype}"
    assert ltm.dtype == torch.long, f"ltm must be int64, got {ltm.dtype}"
    assert sobolstate.shape == (
        dimension,
        MAXBIT,
    ), f"sobolstate shape must be ({dimension}, {MAXBIT}), got {sobolstate.shape}"
    assert ltm.shape == (
        dimension,
        MAXBIT,
        MAXBIT,
    ), f"ltm shape must be ({dimension}, {MAXBIT}, {MAXBIT}), got {ltm.shape}"

    grid = (dimension,)
    sobol_scramble_kernel[grid](
        sobolstate,
        ltm,
        MAXBIT=MAXBIT,
        BLOCK=32,
    )
    return sobolstate
