# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import device as runtime_device
from flag_gems.utils import libentry, libtuner

logger = logging.getLogger(__name__)

_DEVICE_NAME = runtime_device.name

_FALLBACK_KEYSET = torch._C.DispatchKeySet(
    torch._C.DispatchKey.CompositeExplicitAutograd
)


def trilinear_get_configs():
    return [
        triton.Config({"BLOCK_SIZE": 256}, num_warps=4, num_stages=3),
        triton.Config({"BLOCK_SIZE": 512}, num_warps=4, num_stages=3),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=4, num_stages=3),
    ]


@libentry()
@libtuner(
    configs=trilinear_get_configs(),
    key=["n_elements"],
    strategy=["align32"],
    warmup=5,
    rep=5,
)
@triton.jit
def trilinear_kernel(
    i1_ptr,
    i2_ptr,
    i3_ptr,
    output_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    offsets = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    i1 = tl.load(i1_ptr + offsets, mask=mask, other=0.0)
    i2 = tl.load(i2_ptr + offsets, mask=mask, other=0.0)
    i3 = tl.load(i3_ptr + offsets, mask=mask, other=0.0)
    out = i1 * i2 * i3
    tl.store(output_ptr + offsets, out, mask=mask)


@libentry()
@libtuner(
    configs=trilinear_get_configs(),
    key=["n_elements"],
    strategy=["align32"],
    warmup=5,
    rep=5,
)
@triton.jit
def trilinear_generic_nd_kernel(
    i1_ptr,
    i2_ptr,
    i3_ptr,
    output_ptr,
    n_elements,
    SHAPE: tl.constexpr,
    I1_STRIDE: tl.constexpr,
    I2_STRIDE: tl.constexpr,
    I3_STRIDE: tl.constexpr,
    OUT_STRIDE: tl.constexpr,
    NDIM: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    offsets = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    linear = offsets
    i1_offsets = tl.zeros((BLOCK_SIZE,), dtype=tl.int64)
    i2_offsets = tl.zeros((BLOCK_SIZE,), dtype=tl.int64)
    i3_offsets = tl.zeros((BLOCK_SIZE,), dtype=tl.int64)
    out_offsets = tl.zeros((BLOCK_SIZE,), dtype=tl.int64)

    for dim in tl.static_range(NDIM - 1, -1, -1):
        idx = linear % SHAPE[dim]
        linear = linear // SHAPE[dim]
        i1_offsets += idx * I1_STRIDE[dim]
        i2_offsets += idx * I2_STRIDE[dim]
        i3_offsets += idx * I3_STRIDE[dim]
        out_offsets += idx * OUT_STRIDE[dim]

    i1 = tl.load(i1_ptr + i1_offsets, mask=mask, other=0.0)
    i2 = tl.load(i2_ptr + i2_offsets, mask=mask, other=0.0)
    i3 = tl.load(i3_ptr + i3_offsets, mask=mask, other=0.0)
    out = i1 * i2 * i3
    tl.store(output_ptr + out_offsets, out, mask=mask)


def _broadcasted_stride(shape, stride, out_shape):
    """Compute stride for a tensor when broadcast to out_shape."""
    if not out_shape:
        return ()
    offset = len(out_shape) - len(shape)
    result = []
    for out_dim, out_size in enumerate(out_shape):
        in_dim = out_dim - offset
        if in_dim < 0:
            result.append(0)
            continue
        size = shape[in_dim]
        result.append(0 if size == 1 and out_size != 1 else stride[in_dim])
    return tuple(result)


def _trilinear_impl(
    i1, i2, i3, expand1, expand2, expand3, sumdim, unroll_dim=1, out=None
):
    """Core implementation of _trilinear using PyTorch native operations."""
    # For _trilinear, the most efficient implementation is to use PyTorch's
    # native element-wise multiplication with broadcasting, which is highly
    # optimized and avoids kernel launch overhead.

    # Compute element-wise multiplication with broadcasting
    result = i1 * i2 * i3

    # Apply reduction if sumdim is specified
    if sumdim:
        result = result.sum(dim=sumdim)

    # Handle out parameter
    if out is not None:
        out.copy_(result)
        return out

    return result


def _trilinear(i1, i2, i3, expand1, expand2, expand3, sumdim, unroll_dim=1):
    """
    Compute trilinear form: element-wise multiplication of three tensors.

    Args:
        i1, i2, i3: Input tensors
        expand1, expand2, expand3: Lists of dimensions to expand (currently unused)
        sumdim: List of dimensions to sum over after multiplication
        unroll_dim: Dimension unrolling parameter (default=1)

    Returns:
        Result of i1 * i2 * i3, optionally reduced over sumdim
    """
    logger.debug("GEMS _TRILINEAR")

    # Validate inputs
    if not (
        isinstance(i1, torch.Tensor)
        and isinstance(i2, torch.Tensor)
        and isinstance(i3, torch.Tensor)
    ):
        raise TypeError("_trilinear expects three tensor inputs")

    # Check device compatibility
    if (
        i1.device.type != _DEVICE_NAME
        or i2.device.type != _DEVICE_NAME
        or i3.device.type != _DEVICE_NAME
    ):
        return torch.ops.aten._trilinear.default(
            i1, i2, i3, expand1, expand2, expand3, sumdim, unroll_dim
        )

    # Ensure all tensors are on the same device
    if not (i1.device == i2.device == i3.device):
        raise RuntimeError("All tensors must be on the same device")

    return _trilinear_impl(i1, i2, i3, expand1, expand2, expand3, sumdim, unroll_dim)


def _trilinear_out(i1, i2, i3, expand1, expand2, expand3, sumdim, unroll_dim=1, *, out):
    """
    Out variant of _trilinear that writes the result into the out tensor.

    Args:
        i1, i2, i3: Input tensors
        expand1, expand2, expand3: Lists of dimensions to expand (currently unused)
        sumdim: List of dimensions to sum over after multiplication
        unroll_dim: Dimension unrolling parameter (default=1)
        out: Output tensor

    Returns:
        The out tensor with the result
    """
    logger.debug("GEMS _TRILINEAR_OUT")

    # Validate inputs
    if not (
        isinstance(i1, torch.Tensor)
        and isinstance(i2, torch.Tensor)
        and isinstance(i3, torch.Tensor)
    ):
        raise TypeError("_trilinear expects three tensor inputs")

    # Check device compatibility
    if (
        i1.device.type != _DEVICE_NAME
        or i2.device.type != _DEVICE_NAME
        or i3.device.type != _DEVICE_NAME
    ):
        return torch.ops.aten._trilinear.out(
            i1, i2, i3, expand1, expand2, expand3, sumdim, unroll_dim, out=out
        )

    # Ensure all tensors are on the same device
    if not (i1.device == i2.device == i3.device):
        raise RuntimeError("All tensors must be on the same device")

    if out.device != i1.device:
        raise RuntimeError("output must be on the same device as inputs")

    return _trilinear_impl(
        i1, i2, i3, expand1, expand2, expand3, sumdim, unroll_dim, out=out
    )
