# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import importlib
import logging
import os
from typing import Any, Callable, Mapping, Tuple

from flag_gems.utils.code_cache import code_cache_dir
from flag_gems.utils.code_utils import IndentedBuffer, write_atomic

logger = logging.getLogger(__name__)


def generate_imports(code: IndentedBuffer) -> IndentedBuffer:
    code.writeline("import triton")
    code.writeline("import triton.language as tl")
    code.newline()
    code.writeline("from flag_gems.utils import libentry")
    code.writeline("from flag_gems.utils import triton_lang_extension as tle")
    code.newline()
    code.newline()
    return code


def generate_kernel(rank, kernel_name: str, code: IndentedBuffer):
    code.writeline("@libentry()")
    code.writeline("@triton.jit")
    code.writeline(f"def {kernel_name}(")
    with code.indent():
        code.writeline("input_ptr,")
        code.writeline("mask_ptr,")
        code.writeline("indices_ptr,")
        code.writeline("values_ptr,")
        code.writeline("mask_numel,")
        code.writeline("input_numel,")
        for i in range(rank):
            code.writeline(f"input_shape{i},")
        for i in range(rank):
            code.writeline(f"input_stride{i},")
        code.writeline("BLOCK_SIZE: tl.constexpr = 2048,")
    code.writeline("):")
    with code.indent():
        code.writeline("pid = tl.program_id(axis=0)")
        code.writeline("offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)")
        code.writeline("mask_mask = offsets < mask_numel")
        code.newline()
        code.writeline("# Load mask value")
        code.writeline(
            "mask_val = tl.load(mask_ptr + offsets, mask=mask_mask, other=0)"
        )
        code.newline()
        code.writeline("# Compute position in the flattened mask/indices/values")
        code.writeline("pos = offsets")
        code.newline()
        # Convert flattened position to multi-dimensional indices
        for i in range(rank - 1, -1, -1):
            if i == rank - 1:
                code.writeline(f"idx{i} = pos % input_shape{i}")
            else:
                code.writeline(f"idx{i} = (pos // input_shape{i + 1}) % input_shape{i}")
        code.newline()
        # Compute offset in mask/indices/values tensors
        code.writeline("# Compute offset in mask tensor")
        comp = [f"idx{i} * 1" for i in range(rank)]  # mask has trivial strides for now
        code.writeline(f"mask_offset = {' + '.join(comp) if comp else '0'}")
        code.newline()
        # Reload mask at the correct offset
        code.writeline(
            "mask_val = tl.load(mask_ptr + mask_offset, mask=mask_mask, other=0)"
        )
        code.newline()
        # Compute offset in indices tensor
        code.writeline("# Compute offset in indices tensor")
        comp = [f"idx{i} * 1" for i in range(rank)]
        code.writeline(f"indices_offset = {' + '.join(comp) if comp else '0'}")
        code.writeline(
            "indices_val = tl.load(indices_ptr + indices_offset, mask=mask_mask, other=0).to(tl.int64)"
        )
        code.newline()
        # Compute offset in values tensor
        code.writeline("# Compute offset in values tensor")
        comp = [f"idx{i} * 1" for i in range(rank)]
        code.writeline(f"values_offset = {' + '.join(comp) if comp else '0'}")
        code.writeline(
            "values_val = tl.load(values_ptr + values_offset, mask=mask_mask, other=0)"
        )
        code.newline()
        # Convert linear index from indices tensor to multi-dimensional index in input
        code.writeline("# Convert linear index to multi-dimensional offset in input")
        # First compute the multi-dimensional index in input
        code.writeline("temp_idx = indices_val")
        for i in range(rank - 1, -1, -1):
            code.writeline(f"input_idx{i} = temp_idx % input_shape{i}")
            code.writeline(f"temp_idx = temp_idx // input_shape{i}")
        code.newline()
        # Then compute the memory offset
        code.writeline("# Compute memory offset in input tensor")
        comp = [f"input_idx{i} * input_stride{i}" for i in range(rank)]
        code.writeline(f"dest_offset = {' + '.join(comp)}")
        code.newline()
        code.writeline("# Validate index is within bounds")
        code.writeline("index_valid = (indices_val >= 0) & (indices_val < input_numel)")
        code.writeline("final_mask = mask_mask & (mask_val != 0) & index_valid")
        code.newline()
        code.writeline(
            "# Atomic add at destination, only where mask is True and index is valid"
        )
        code.writeline(
            "tl.atomic_add(input_ptr + dest_offset, values_val, mask=final_mask, sem='relaxed')"
        )
    code.newline()
    code.newline()
    return code


def generate_wrapper(rank, wrapper_name: str, kernel_name: str, code: IndentedBuffer):
    code.writeline(f"def {wrapper_name}(input, mask, indices, values):")
    with code.indent():
        code.writeline("input_numel = input.numel()")
        code.writeline("mask_numel = mask.numel()")
        code.newline()
        code.writeline("# Get input shape and strides")
        for i in range(rank):
            code.writeline(f"input_shape{i} = input.shape[{i}]")
        for i in range(rank):
            code.writeline(f"input_stride{i} = input.stride()[{i}]")
        code.newline()
        code.writeline("BLOCK_SIZE = 2048")
        code.writeline("grid = (triton.cdiv(mask_numel, BLOCK_SIZE),)")
        code.newline()
        code.writeline(f"{kernel_name}[grid](")
        with code.indent():
            code.writeline("input,")
            code.writeline("mask,")
            code.writeline("indices,")
            code.writeline("values,")
            code.writeline("mask_numel,")
            code.writeline("input_numel,")
            for i in range(rank):
                code.writeline(f"input_shape{i},")
            for i in range(rank):
                code.writeline(f"input_stride{i},")
            code.writeline("BLOCK_SIZE=BLOCK_SIZE")
        code.writeline(")")
        code.writeline("return input")
    code.newline()
    code.newline()
    return code


def generate_code(
    inputs: Tuple[Any],
    wrapper_name: str,
    kernel_name: str,
    code: IndentedBuffer,
):
    input_tensor = inputs[0]
    rank = input_tensor.ndim
    code = generate_imports(code)
    generate_kernel(rank, kernel_name, code)
    generate_wrapper(rank, wrapper_name, kernel_name, code)
    return code


class UnsafeMaskedIndexPutAccumulateFunction:
    def __init__(self):
        self.pid = os.getpid()
        self.overloads: Mapping[str, Callable] = {}

    def __call__(self, *args, **kwargs):
        key = self.arg_key(*args)
        if key in self.overloads:
            overload = self.overloads[key]
        else:
            code = IndentedBuffer()
            code = generate_code(
                args,
                "_unsafe_masked_index_put_accumulate_wrapper",
                "_unsafe_masked_index_put_accumulate_jit",
                code,
            )
            file_name = f"unsafe_masked_index_put_accumulate_{key}_pid_{self.pid}.py"
            file_path = code_cache_dir() / file_name
            write_atomic(file_path, code.getvalue())

            spec = importlib.util.spec_from_file_location(
                f"_gen_module_{key}_pid_{self.pid}",
                file_path,
            )

            m = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(m)
            overload = getattr(m, "_unsafe_masked_index_put_accumulate_wrapper")
            self.overloads[key] = overload

        return overload(*args)

    def arg_key(self, *args):
        input_tensor, mask, indices, values = args
        return f"rank_{input_tensor.ndim}"


_unsafe_masked_index_put_accumulate_func = UnsafeMaskedIndexPutAccumulateFunction()


def _unsafe_masked_index_put_accumulate(inp, mask, indices, values):
    logger.debug("GEMS UNSAFE_MASKED_INDEX_PUT_ACCUMULATE")

    # indices is Tensor?[] - a list of optional tensors
    # For this operator, we expect a single index tensor (the common case)
    # Handle both list and tuple cases
    if isinstance(indices, (list, tuple)):
        indices_tensor = indices[0] if len(indices) > 0 else None
        if indices_tensor is None:
            raise ValueError("Empty indices list")
    else:
        indices_tensor = indices

    # Validate shapes
    assert mask.shape == indices_tensor.shape, (
        f"mask and indices must have same shape, got {mask.shape} "
        f"and {indices_tensor.shape}"
    )
    assert mask.shape == values.shape, (
        f"mask and values must have same shape, got {mask.shape} " f"and {values.shape}"
    )

    # Ensure same device
    inp = inp.to(values.device) if inp.device != values.device else inp.clone()
    mask = mask.to(inp.device) if mask.device != inp.device else mask
    indices_tensor = (
        indices_tensor.to(inp.device)
        if indices_tensor.device != inp.device
        else indices_tensor
    )
    values = values.to(inp.device) if values.device != inp.device else values

    return _unsafe_masked_index_put_accumulate_func(inp, mask, indices_tensor, values)
