# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""
_weight_int4pack_mm: Int4 packed weight matrix multiplication.

Conventions (self-consistent across kernel, tests, and reference):
  - A (self):     activation tensor of shape (M, K), dtype fp16/bf16/fp32.
  - mat2:         int4 packed weights of shape (N, K//2), dtype uint8.
                  Each byte packs two adjacent int4 values:
                    low  nibble (bits 0-3)  = weight[n, 2*j]     (even column)
                    high nibble (bits 4-7)  = weight[n, 2*j+1]   (odd column)
                  This packing matches _convert_weight_to_int4pack.
  - qGroupSize:   group size along the K dimension for quantization.
                  K must be divisible by qGroupSize.
  - qScaleAndZeros: shape (K//qGroupSize, N, 2), dtype same as A.
                    Last dim: index 0 = scale, index 1 = zero_point.
  - Output:       tensor of shape (M, N), dtype same as A.
                  Computes C = A @ dequant(W).T, where dequant(W) has
                  shape (N, K) after unpacking and dequantizing mat2.

Implementation:
  The wrapper pre-dequantizes the weight matrix into float32 on GPU, then
  calls a clean Triton GEMM kernel. This avoids layout issues with
  constructing tensors via tl.where for use with tl.dot.
"""

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def weight_int4pack_mm_kernel(
    A_ptr,
    B_ptr,
    C_ptr,
    M,
    N,
    K,
    stride_am,
    stride_ak,
    stride_bk,
    stride_bn,
    stride_cm,
    stride_cn,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
    GROUP_M: tl.constexpr,
):
    """Clean Triton GEMM kernel for pre-dequantized float32 weights.

    Computes C = A @ B where A is (M, K) and B is (K, N).
    B is the pre-dequantized weight matrix transposed to (K, N).
    """
    pid = tl.program_id(0)
    num_pid_m = tl.cdiv(M, BLOCK_M)
    num_pid_n = tl.cdiv(N, BLOCK_N)
    num_pid_in_group = GROUP_M * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * GROUP_M
    group_size_m = tl.minimum(num_pid_m - first_pid_m, GROUP_M)
    pid_m = first_pid_m + (pid % group_size_m)
    pid_n = (pid % num_pid_in_group) // group_size_m

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)

    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)

    for start_k in range(0, K, BLOCK_K):
        # Load A tile: (BLOCK_M, BLOCK_K)
        a_ptrs = (
            A_ptr
            + offs_m[:, None] * stride_am
            + (start_k + offs_k[None, :]) * stride_ak
        )
        k_mask = (start_k + offs_k)[None, :] < K
        a = tl.load(a_ptrs, mask=(offs_m[:, None] < M) & k_mask, other=0.0)
        a = a.to(tl.float32)

        # Load B tile: (BLOCK_K, BLOCK_N) — transposed dequantized weight
        b_ptrs = (
            B_ptr
            + (start_k + offs_k[:, None]) * stride_bk
            + offs_n[None, :] * stride_bn
        )
        k_mask_b = (start_k + offs_k)[:, None] < K
        b = tl.load(b_ptrs, mask=k_mask_b & (offs_n[None, :] < N), other=0.0)
        b = b.to(tl.float32)

        acc += tl.dot(a, b, out_dtype=tl.float32, allow_tf32=False)

    # Store results
    acc = acc.to(C_ptr.dtype.element_ty)
    c_ptrs = C_ptr + offs_m[:, None] * stride_cm + offs_n[None, :] * stride_cn
    c_mask = (offs_m < M)[:, None] & (offs_n < N)[None, :]
    tl.store(c_ptrs, acc, mask=c_mask)


def _dequantize_int4_weights(mat2, K, N, qGroupSize, qScaleAndZeros, dtype, device):
    """Dequantize byte-pair int4 packed weights into float32 matrix of shape (K, N).

    Returns a (K, N) float32 tensor ready for use as the B operand in GEMM.
    The transposition to (K, N) avoids an extra transpose in the kernel.
    """
    # Unpack mat2: low nibble = even K positions, high nibble = odd K positions
    mat2_int = mat2.to(torch.int32)
    low_nibble = mat2_int & 0xF  # (N, K//2) — even positions
    high_nibble = (mat2_int >> 4) & 0xF  # (N, K//2) — odd positions

    # Interleave into (N, K)
    W_int4 = torch.empty((N, K), dtype=torch.int32, device=device)
    W_int4[:, 0::2] = low_nibble
    W_int4[:, 1::2] = high_nibble

    # Gather scales and zeros per K position
    groups = torch.arange(K, device=device) // qGroupSize  # (K,)
    # qScaleAndZeros shape: (num_groups, N, 2)
    scales_all = qScaleAndZeros[:, :, 0].T  # (N, num_groups)
    zeros_all = qScaleAndZeros[:, :, 1].T  # (N, num_groups)

    scales_per_k = scales_all[:, groups].to(torch.float32)  # (N, K)
    zeros_per_k = zeros_all[:, groups].to(torch.float32)  # (N, K)

    # Dequantize: (N, K) float32
    W_deq = (W_int4.to(torch.float32) - zeros_per_k) * scales_per_k

    # Return transposed: (K, N) for use as B in GEMM C = A @ B
    return W_deq.T.contiguous()


def _weight_int4pack_mm(
    A: torch.Tensor,
    mat2: torch.Tensor,
    qGroupSize: int,
    qScaleAndZeros: torch.Tensor,
) -> torch.Tensor:
    """Int4 packed weight matrix multiplication.

    Args:
        A:              Activation tensor of shape (M, K), floating point dtype.
        mat2:           Int4 packed weight tensor of shape (N, K//2), dtype uint8.
                        Byte-pair packing: low nibble = even column, high nibble = odd column.
        qGroupSize:     Group size along K dimension. Must evenly divide K.
        qScaleAndZeros: Scale and zero points of shape (K//qGroupSize, N, 2),
                        dtype same as A. Last dim: [scale, zero].

    Returns:
        Output tensor of shape (M, N), dtype same as A.
    """
    logger.debug("GEMS _WEIGHT_INT4PACK_MM")

    M, K = A.shape
    N = mat2.shape[0]
    K_half = mat2.shape[1]
    assert K == K_half * 2, (
        f"mat2 shape[1] ({K_half}) must equal K//2 where K={K} (from A), "
        f"got K_half * 2 = {K_half * 2} != K={K}"
    )
    assert (
        K % qGroupSize == 0
    ), f"K ({K}) must be divisible by qGroupSize ({qGroupSize})"
    assert mat2.dtype == torch.uint8, f"mat2 must be uint8, got {mat2.dtype}"
    assert A.dtype.is_floating_point, f"A must be a floating point type, got {A.dtype}"

    # Pre-dequantize the weight matrix: (N, K) uint8 → (K, N) float32
    B = _dequantize_int4_weights(
        mat2, K, N, qGroupSize, qScaleAndZeros, A.dtype, A.device
    )

    out = torch.empty((M, N), dtype=A.dtype, device=A.device)

    BLOCK_M = 64
    BLOCK_N = 64
    BLOCK_K = 64
    GROUP_M = 8

    grid = lambda META: (
        triton.cdiv(M, META.get("BLOCK_M", BLOCK_M))
        * triton.cdiv(N, META.get("BLOCK_N", BLOCK_N)),
    )

    with torch_device_fn.device(A.device):
        weight_int4pack_mm_kernel[grid](
            A,
            B,
            out,
            M,
            N,
            K,
            A.stride(0),
            A.stride(1),
            B.stride(0),
            B.stride(1),
            out.stride(0),
            out.stride(1),
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            BLOCK_K=BLOCK_K,
            GROUP_M=GROUP_M,
        )

    return out
