# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def argwhere(input):
    """Triton-accelerated implementation of torch.argwhere.

    Returns a tensor of shape (num_nonzero, ndim) containing indices
    of all non-zero elements in row-major order.

    Delegates to FlagGems nonzero which uses Triton-based prefix-sum
    compaction to produce ordered multi-dimensional indices.
    """
    input = input.contiguous()
    return torch.ops.aten.nonzero(input)
