# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


@libentry()
@triton.heuristics(runtime.get_heuristic_config("elementwise_generic"))
@triton.jit
def argwhere_kernel(
    inp,
    prefix_sum,
    out,
    n_elements,
    shape,
    ndim: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Triton kernel that compacts non-zero element indices into output rows.

    Each thread block processes BLOCK_SIZE elements. For each non-zero element,
    decomposes its flat index into multi-dimensional coordinates and writes
    them to the output at the position given by the prefix-sum.
    """
    pid = ext.program_id(0)

    offset = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offset < n_elements

    inp_vals = tl.load(inp + offset, mask=mask).to(tl.int1)
    out_offset = tl.load(prefix_sum + offset, mask=mask) - 1

    nonzero_mask = mask and inp_vals  # noqa

    # Decompose flat index into multi-dimensional coordinates
    idx_flat = offset
    for dim in range(ndim - 1, -1, -1):
        dim_size = tl.load(shape + dim)
        remainder = idx_flat % dim_size
        idx_flat //= dim_size
        tl.store(out + out_offset * ndim + dim, remainder, mask=nonzero_mask)


def argwhere(input):
    """Triton-accelerated implementation of torch.argwhere.

    Returns a tensor of shape (num_nonzero, ndim) containing the indices
    of all non-zero elements. Uses a prefix-sum compaction strategy:
    1. Flatten input and compute boolean mask of non-zero elements
    2. Compute cumulative sum (prefix-sum) for scatter positions
    3. Launch Triton kernel to decompose flat indices and scatter results
    """
    logger.debug("GEMS ARGWHERE")

    inp_ndim = input.ndim
    input = input.contiguous()
    n_elements = input.numel()
    inp_view = input.view(n_elements)

    shape = torch.tensor(input.shape, dtype=torch.int32, device=input.device)

    inp_bool = inp_view
    if inp_view.dtype != torch.bool:
        inp_bool = inp_view != 0

    prefix_sum = inp_bool.cumsum(axis=0)

    # Allocate max-size output; trim after kernel launch
    out = torch.empty(n_elements, inp_ndim, dtype=torch.int64, device=input.device)

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(input.device):
        argwhere_kernel[grid](inp_bool, prefix_sum, out, n_elements, shape, inp_ndim)

    num_nonzeros = prefix_sum[n_elements - 1].item()
    out = out[0:num_nonzeros]

    return out
