# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def bartlett_window_kernel(
    output_ptr,
    N_compute,  # N used for formula (window_length+1 if periodic, else window_length)
    window_length,  # actual output length
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < window_length

    n = offsets.to(tl.float32)
    N_minus_1 = (N_compute - 1).to(tl.float32)

    # w[n] = 1 - |2*n/(N-1) - 1|
    val = 1.0 - tl.abs(2.0 * n / N_minus_1 - 1.0)

    tl.store(output_ptr + offsets, val, mask=mask)


def bartlett_window(
    window_length,
    periodic=True,
    *,
    dtype=None,
    layout=torch.strided,
    device=None,
    requires_grad=False,
):
    if dtype is None:
        dtype = torch.float32
    assert dtype in (
        torch.float16,
        torch.float32,
        torch.bfloat16,
        torch.float64,
    ), f"bartlett_window: unsupported dtype {dtype}"
    if device is None:
        device = "cuda"

    if window_length <= 0:
        return torch.empty(0, dtype=dtype, device=device, requires_grad=requires_grad)
    if window_length == 1:
        return torch.ones(1, dtype=dtype, device=device, requires_grad=requires_grad)

    # For periodic window, compute symmetric window of length+1, then take first window_length elements
    if periodic:
        N_compute = window_length + 1
    else:
        N_compute = window_length

    output = torch.empty(
        window_length, dtype=dtype, device=device, requires_grad=requires_grad
    )

    # 1024 balances occupancy and register usage for 1-D window generation
    BLOCK_SIZE = 1024
    grid = ((window_length + BLOCK_SIZE - 1) // BLOCK_SIZE,)

    bartlett_window_kernel[grid](
        output,
        N_compute,
        window_length,
        BLOCK_SIZE=BLOCK_SIZE,
    )

    return output
