# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("batch_norm"),
    key=["batch_dim", "spatial_dim"],
)
@triton.heuristics(runtime.get_heuristic_config("batch_norm"))
@triton.jit
def batch_norm_stats_kernel(
    input_pointer,
    mean_pointer,
    invstd_pointer,
    batch_dim,
    spatial_dim,
    input_batch_stride,
    input_feat_stride,
    input_spatial_stride,
    eps,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    # Each program handles one channel
    feat_pid = tl.program_id(axis=0)

    # Accumulate sum and sum_sq using tiled reduction over batch and spatial dims
    _sum = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)
    _sum_sq = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)

    m_num_steps = tl.cdiv(batch_dim, BLOCK_M)
    n_num_steps = tl.cdiv(spatial_dim, BLOCK_N)

    for m_step in range(0, m_num_steps):
        batch_offset = m_step * BLOCK_M + tl.arange(0, BLOCK_M)
        batch_mask = batch_offset < batch_dim

        for n_step in range(0, n_num_steps):
            spatial_offset = n_step * BLOCK_N + tl.arange(0, BLOCK_N)
            spatial_mask = spatial_offset < spatial_dim

            mask = batch_mask[:, None] & spatial_mask[None, :]

            curr_input_pointer = (
                input_pointer
                + input_feat_stride * feat_pid
                + input_batch_stride * batch_offset[:, None]
                + input_spatial_stride * spatial_offset[None, :]
            )

            x = tl.load(curr_input_pointer, mask=mask, other=0.0).to(tl.float32)
            _sum += tl.where(mask, x, 0.0)
            _sum_sq += tl.where(mask, x * x, 0.0)

    # Reduce across the block
    total_sum = tl.sum(_sum)
    total_sum_sq = tl.sum(_sum_sq)

    count = (batch_dim * spatial_dim).to(tl.float32)
    mean = total_sum / count
    var = total_sum_sq / count - mean * mean
    invstd = 1.0 / tl.sqrt(var + eps)

    # Store results
    tl.store(mean_pointer + feat_pid, mean)
    tl.store(invstd_pointer + feat_pid, invstd)


def batch_norm_stats(input, eps):
    """Compute batch normalization statistics (mean and invstd) per channel.

    Args:
        input: Tensor of shape (N, C, *spatial_dims)
        eps: Small constant for numerical stability

    Returns:
        Tuple of (mean, invstd), each of shape (C,)
    """
    logger.debug("GEMS BATCH_NORM_STATS")

    assert input.ndim >= 2, "Input must have at least 2 dimensions (N, C, ...)"

    # Reshape to 3D: (N, C, spatial)
    N = input.shape[0]
    C = input.shape[1]

    if input.ndim == 2:
        input_3d = input.unsqueeze(-1).contiguous()
    elif input.ndim >= 4:
        input_3d = input.flatten(2, -1).contiguous()
    else:
        input_3d = input.contiguous()

    spatial = input_3d.shape[2]

    # Output tensors
    mean = torch.empty(C, dtype=torch.float32, device=input.device)
    invstd = torch.empty(C, dtype=torch.float32, device=input.device)

    # Launch kernel: one program per channel
    with torch_device_fn.device(input.device):
        batch_norm_stats_kernel[(C,)](
            input_3d,
            mean,
            invstd,
            N,
            spatial,
            input_3d.stride(0),
            input_3d.stride(1),
            input_3d.stride(2),
            eps,
        )

    return mean, invstd
