# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=[
        triton.Config({"BLOCK_HW": 256}, num_warps=4),
        triton.Config({"BLOCK_HW": 512}, num_warps=4),
        triton.Config({"BLOCK_HW": 1024}, num_warps=4),
        triton.Config({"BLOCK_HW": 2048}, num_warps=4),
        triton.Config({"BLOCK_HW": 256}, num_warps=8),
        triton.Config({"BLOCK_HW": 512}, num_warps=8),
        triton.Config({"BLOCK_HW": 1024}, num_warps=8),
        triton.Config({"BLOCK_HW": 2048}, num_warps=8),
    ],
    key=["HW"],
)
@triton.jit
def batch_norm_elemt_kernel(
    input_ptr,
    weight_ptr,
    bias_ptr,
    mean_ptr,
    invstd_ptr,
    output_ptr,
    N,
    C,
    HW,
    stride_n,
    stride_c,
    stride_hw,
    BLOCK_HW: tl.constexpr,
):
    """Fused batch_norm_elemt kernel: output = (input - mean) * invstd * weight + bias

    Each program instance handles one (n, c) pair across all spatial elements.
    Grid size = N * C.
    """
    pid = tl.program_id(0)
    n = pid // C
    c = pid % C

    # Load per-channel parameters in fp32 for numerical stability
    mean_val = tl.load(mean_ptr + c).to(tl.float32)
    invstd_val = tl.load(invstd_ptr + c).to(tl.float32)
    weight_val = tl.load(weight_ptr + c).to(tl.float32)
    bias_val = tl.load(bias_ptr + c).to(tl.float32)

    base_offset = n * stride_n + c * stride_c

    # Tiled loop over the spatial (HW) dimension
    for hw_offset in range(0, HW, BLOCK_HW):
        hw_idx = hw_offset + tl.arange(0, BLOCK_HW)
        mask = hw_idx < HW

        offset = base_offset + hw_idx * stride_hw
        x = tl.load(input_ptr + offset, mask=mask).to(tl.float32)

        # Fused computation in fp32: (x - mean) * invstd * weight + bias
        out = (x - mean_val) * invstd_val * weight_val + bias_val

        tl.store(output_ptr + offset, out, mask=mask)


def batch_norm_elemt(input, weight, bias, mean, invstd, eps=0.0):
    """Compute batch_norm_elemt: output = (input - mean) * invstd * weight + bias

    Args:
        input: Tensor of shape (N, C, ...) — supports arbitrary spatial dimensions.
        weight: Tensor of shape (C,).
        bias: Tensor of shape (C,).
        mean: Tensor of shape (C,).
        invstd: Tensor of shape (C,).
        eps: Unused (kept for API compatibility with aten::batch_norm_elemt).

    Returns:
        Tensor of same shape as input.
    """
    assert input.is_cuda, "Input must be a CUDA tensor"
    original_shape = input.shape
    N = input.shape[0]
    C = input.shape[1]
    HW = 1
    for s in input.shape[2:]:
        HW *= s

    # Ensure contiguous layout for coalesced memory access
    input_contig = input.contiguous()
    input_flat = input_contig.view(N, C, HW)

    output = torch.empty_like(input_flat)

    stride_n = input_flat.stride(0)
    stride_c = input_flat.stride(1)
    stride_hw = input_flat.stride(2)

    grid = (N * C,)
    batch_norm_elemt_kernel[grid](
        input_flat,
        weight,
        bias,
        mean,
        invstd,
        output,
        N,
        C,
        HW,
        stride_n,
        stride_c,
        stride_hw,
    )
    return output.view(original_shape)
