# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def cast_func(x):
    # Cast operation - identity function that preserves the input
    # The actual type conversion happens through the output tensor's dtype
    return x


def cast(A):
    logger.debug("GEMS CAST")
    return cast_func(A)


def cast_(A):
    logger.debug("GEMS CAST_")
    cast_func(A, out0=A)
    return A
