# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import Optional

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _clone_kernel(src_ptr, dst_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    vals = tl.load(src_ptr + offsets, mask=mask)
    tl.store(dst_ptr + offsets, vals, mask=mask)


class _CloneFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, inp, memory_format):
        ctx.memory_format = memory_format
        return _clone_impl(inp, memory_format)

    @staticmethod
    def backward(ctx, grad_out):
        return grad_out, None


def _allocate_preserve_format(inp: torch.Tensor) -> torch.Tensor:
    # Replicating the original strides is only valid for a non-overlapping
    # dense layout; other inputs take PyTorch's suggested layout.
    if torch.ops.aten.is_non_overlapping_and_dense(inp):
        return torch.empty_strided(
            inp.size(), inp.stride(), dtype=inp.dtype, device=inp.device
        )
    return torch.empty_like(inp, memory_format=torch.preserve_format)


def _launch_copy(src: torch.Tensor, dst: torch.Tensor):
    n_elements = src.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(src.device):
        _clone_kernel[grid](src, dst, n_elements, BLOCK_SIZE=1024)


def _clone_impl(inp: torch.Tensor, memory_format: torch.memory_format):
    if inp.numel() == 0:
        if memory_format == torch.preserve_format:
            return _allocate_preserve_format(inp)
        return torch.empty_like(inp, memory_format=memory_format)

    if memory_format == torch.preserve_format:
        out = _allocate_preserve_format(inp)
        # Source and destination share the same layout, so element order
        # matches and the flat kernel applies.
        if inp.is_contiguous() or torch.ops.aten.is_non_overlapping_and_dense(inp):
            _launch_copy(inp, out)
        else:
            out.copy_(inp)
        return out

    if memory_format == torch.contiguous_format:
        out = torch.empty_like(inp, memory_format=torch.contiguous_format)
        # flatten() on a contiguous input is a pure view; on a strided input it
        # would dispatch through reshape, whose decomposition calls clone again
        # and recurses.
        if inp.is_contiguous():
            _launch_copy(inp, out)
        else:
            out.copy_(inp)
        return out

    out = torch.empty(inp.size(), dtype=inp.dtype, device=inp.device)
    out = out.to(memory_format=memory_format)
    out.copy_(inp)
    return out


def clone(inp: torch.Tensor, memory_format: Optional[torch.memory_format] = None):
    """
    Returns a copy of the input tensor.

    Args:
        inp: The input tensor to clone.
        memory_format: The desired memory format of the returned tensor.
            Default is torch.preserve_format.
    """
    logger.debug("GEMS CLONE")

    if memory_format is None:
        memory_format = torch.preserve_format

    # Wrap the copy in an autograd node so the output carries a grad_fn and
    # gradients keep flowing when this clone is used inside a training graph.
    out = _CloneFunction.apply(inp, memory_format)
    return out
