# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS"
# BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _detach_copy_flat(x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(0).to(tl.int64)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    val = tl.load(x_ptr + offsets, mask=mask)
    tl.store(out_ptr + offsets, val, mask=mask)


@triton.jit
def _detach_copy_strided(
    x_ptr, out_ptr, n_elements, meta_ptr, ndim: tl.constexpr, BLOCK_SIZE: tl.constexpr
):
    # meta layout: for dim i in [0, ndim): meta[2*i] = shape[i], meta[2*i+1] = stride[i]
    pid = tl.program_id(0).to(tl.int64)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    idx = offsets
    in_off = tl.zeros([BLOCK_SIZE], dtype=tl.int64)
    for k in tl.static_range(ndim):
        i = ndim - 1 - k
        d = tl.load(meta_ptr + 2 * i).to(tl.int64)
        s = tl.load(meta_ptr + 2 * i + 1).to(tl.int64)
        c = idx % d
        idx = idx // d
        in_off += c * s
    val = tl.load(x_ptr + in_off, mask=mask)
    tl.store(out_ptr + offsets, val, mask=mask)


def _resolve_lazy_bits(input: torch.Tensor) -> torch.Tensor:
    """Materialize lazy conjugate / negative bits before any raw storage read.

    Both copy kernels load the underlying storage directly, so a view carrying
    a lazy bit — e.g. ``torch._neg_view(x)`` or ``x.conj()`` — would be copied
    bitwise: ``detach_copy(torch._neg_view(x))`` would return ``x`` instead of
    the logical value ``-x``. ``resolve_conj`` / ``resolve_neg`` return the
    input unchanged when no bit is set and otherwise materialize the logical
    values into fresh storage, which is also what the native operator observes
    before copying (its freshly allocated result carries no lazy bits).
    """
    if input.is_conj():
        input = input.resolve_conj()
    is_neg = getattr(input, "is_neg", None)
    if is_neg is not None and is_neg():
        input = input.resolve_neg()
    return input


def detach_copy(self: torch.Tensor) -> torch.Tensor:
    """Return a copy of ``self`` detached from the autograd graph.

    Mirrors ``aten::detach_copy(Tensor self) -> Tensor``: the values are
    materialized into freshly allocated memory (equivalent to
    ``self.detach().clone()``), so the result never aliases the input.

    Contiguous inputs take a flat 1-D copy kernel; non-contiguous inputs take
    a strided kernel driven by a device-side shape/stride metadata buffer
    (``meta[2*i] = shape[i]``, ``meta[2*i+1] = stride[i]``). Either way the
    output is freshly allocated, dense and contiguous, matching the native
    operator, which also returns a contiguous tensor for a non-contiguous
    input.

    Complex inputs stay on the device path: they are resolved of their lazy
    conjugate/negative bits and reinterpreted through ``torch.view_as_real``
    as interleaved (real, imag) pairs, copied by the same kernels, and
    reassembled with ``torch.view_as_complex`` (Triton has no complex dtype
    mapping, so the kernels themselves stay real-valued).
    """
    logger.debug("GEMS DETACH_COPY")
    # Lazy conjugate/negative bits must be materialized before the kernels
    # read raw storage (no-op views are returned untouched).
    self = _resolve_lazy_bits(self)
    is_complex = self.dtype.is_complex
    if is_complex:
        self = torch.view_as_real(self)
    n = self.numel()
    # Fresh contiguous storage, exactly like native detach_copy. ``empty_like``
    # would preserve a non-contiguous input's strides, which both the kernels'
    # linear stores and the native layout contract rule out.
    out = torch.empty(self.shape, dtype=self.dtype, device=self.device)
    if n == 0:
        # No elements to read: the freshly allocated (dense) output is already
        # the required result, and a grid of (0,) must not be launched.
        return torch.view_as_complex(out) if is_complex else out
    if self.is_contiguous():
        BLOCK = 1024
        grid = (triton.cdiv(n, BLOCK),)
        with torch_device_fn.device(self.device):
            _detach_copy_flat[grid](self, out, n, BLOCK_SIZE=BLOCK, num_warps=4)
    else:
        shape = self.shape
        stride = self.stride()
        nd = len(shape)
        # One host->device transfer for the shape/stride metadata; filling a
        # device tensor with a scalar ``meta[i] = v`` loop would launch
        # 2 * ndim separate device operations before the copy kernel.
        meta = torch.tensor(
            [v for s, st in zip(shape, stride) for v in (s, st)],
            dtype=torch.int64,
            device=self.device,
        )
        # Tuning measured on H20 (see the task report): the strided kernel's
        # per-element div/mod address computation prefers narrower blocks than
        # the flat path — BLOCK=256 beats the shared 1024 default by 10-58%
        # across the shapes swept, with num_warps=4 at the knee.
        BLOCK = 256
        grid = (triton.cdiv(n, BLOCK),)
        with torch_device_fn.device(self.device):
            _detach_copy_strided[grid](
                self, out, n, meta, ndim=nd, BLOCK_SIZE=BLOCK, num_warps=4
            )
    return torch.view_as_complex(out) if is_complex else out
