# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "ALWAYS_BOOL")])
@triton.jit
def _ge_func(x, y):
    return x.to(tl.float32) >= y


def ge_(A, B):
    logger.debug("GEMS GE_")

    if not isinstance(A, torch.Tensor):
        raise TypeError("ge_ expects A to be a torch.Tensor")

    if isinstance(B, torch.Tensor):
        _ge_func(A, B, out0=A)
    else:
        _ge_func_scalar(A, B, out0=A)

    return A


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "ALWAYS_BOOL")])
@triton.jit
def _ge_func_scalar(x, y):
    return x.to(tl.float32) >= y
