# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import pointwise_dynamic


@pointwise_dynamic
def hardshrink_kernel(x, lambd):
    gt = x > lambd
    lt = x < -lambd
    return tl.where(gt, x, tl.where(lt, x, 0.0))


def hardshrink(input: torch.Tensor, lambd: float = 0.5):
    return hardshrink_kernel(input, lambd)
