# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

_exp2 = tl_extra_shim.exp2

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def ldexp_inplace_func(x, other):
    return x.to(tl.float32) * _exp2(other.to(tl.float32))


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def ldexp_inplace_fp64_func(x, other):
    # Some Triton 3.2/CUDA 12.4 builds abort while lowering fp64 exp2.
    # Keep the multiply/output in fp64 and use the portable fp32 exp2 path.
    return x.to(tl.float64) * _exp2(other.to(tl.float32)).to(tl.float64)


@pointwise_dynamic(
    is_tensor=[True, True, True, True],
    num_outputs=2,
    promotion_methods=[
        (0, 1, 2, 3, "INT_TO_FLOAT"),
        (0, 1, 2, 3, "INT_TO_FLOAT"),
    ],
)
@triton.jit
def ldexp_inplace_complex_func(xr, xi, yr, yi):
    xr = xr.to(tl.float32)
    xi = xi.to(tl.float32)
    yr = yr.to(tl.float32)
    yi = yi.to(tl.float32)
    scale = _exp2(yr)
    angle = yi * 0.6931471805599453
    cos_angle = tl.cos(angle)
    sin_angle = tl.sin(angle)
    return (
        scale * (xr * cos_angle - xi * sin_angle),
        scale * (xr * sin_angle + xi * cos_angle),
    )


@pointwise_dynamic(
    is_tensor=[True, True, True, True],
    num_outputs=2,
    promotion_methods=[
        (0, 1, 2, 3, "INT_TO_FLOAT"),
        (0, 1, 2, 3, "INT_TO_FLOAT"),
    ],
)
@triton.jit
def ldexp_inplace_complex_fp64_func(xr, xi, yr, yi):
    xr = xr.to(tl.float64)
    xi = xi.to(tl.float64)
    yr = yr.to(tl.float64)
    yi = yi.to(tl.float64)
    scale = _exp2(yr.to(tl.float32)).to(tl.float64)
    angle = yi * 0.693147180559945309417232121458176568
    cos_angle = tl.cos(angle)
    sin_angle = tl.sin(angle)
    return (
        scale * (xr * cos_angle - xi * sin_angle),
        scale * (xr * sin_angle + xi * cos_angle),
    )


def _result_dtype(self, other):
    self_dtype = (
        torch.float32
        if self.dtype == torch.bool
        or (not self.is_floating_point() and not self.is_complex())
        else self.dtype
    )
    return torch.promote_types(self_dtype, other.dtype)


def _complex_parts(tensor, real_dtype):
    if tensor.is_complex():
        parts = torch.view_as_real(tensor)
        return parts[..., 0].to(real_dtype), parts[..., 1].to(real_dtype)
    real = tensor.to(real_dtype)
    return real, torch.zeros_like(real)


def _ldexp_complex_(self, other):
    real_dtype = torch.float64 if self.dtype == torch.complex128 else torch.float32
    xr, xi = _complex_parts(self, real_dtype)
    yr, yi = _complex_parts(other, real_dtype)
    output = torch.view_as_real(self)
    func = (
        ldexp_inplace_complex_fp64_func
        if self.dtype == torch.complex128
        else ldexp_inplace_complex_func
    )
    func(xr, xi, yr, yi, out0=output[..., 0], out1=output[..., 1])


def ldexp_(self, other):
    logger.debug("GEMS LDEXP_")
    result_dtype = _result_dtype(self, other)
    if not torch.can_cast(result_dtype, self.dtype):
        raise RuntimeError(
            f"result type {result_dtype} can't be cast to the desired output "
            f"type {self.dtype}"
        )

    output_shape = torch.broadcast_shapes(self.shape, other.shape)
    if output_shape != self.shape:
        raise RuntimeError(
            f"output with shape {self.shape} doesn't match the broadcast shape "
            f"{output_shape}"
        )

    if self.is_complex():
        _ldexp_complex_(self, other)
    else:
        func = (
            ldexp_inplace_fp64_func
            if self.dtype == torch.float64
            else ldexp_inplace_func
        )
        func(self, other, out0=self)
    return self
