# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from flag_gems.ops.bmm import bmm
from flag_gems.ops.mm import mm

logger = logging.getLogger(__name__)


def linalg_matmul(input, other):
    """Matrix product of two tensors.

    The behavior depends on the dimensionality of the inputs:
    - If both inputs are 2D, performs regular matrix multiplication: (M, K) @ (K, N) -> (M, N)
    - If both inputs are 3D (batched), performs batched matrix multiplication:
      (B, M, K) @ (B, K, N) -> (B, M, N)

    This is an alias for torch.matmul.
    """
    logger.debug("GEMS LINALG_MATMUL")

    # Handle 2D case: (M, K) @ (K, N) -> (M, N)
    if input.dim() == 2 and other.dim() == 2:
        return mm(input, other)

    # Handle 3D case (batched): (B, M, K) @ (B, K, N) -> (B, M, N)
    if input.dim() == 3 and other.dim() == 3:
        return bmm(input, other)

    # Fallback to torch.matmul for other cases (1D vectors, broadcasting, etc.)
    return torch.matmul(input, other)
