# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def tensorsolve_kernel(W, B, X, M, BLOCK: tl.constexpr):
    """*Vectorized* solve of the linear system W @ x = B for a single square system.

    The M x M matrix is held in a BLOCK x BLOCK register tile and the M-vector B
    in a BLOCK register vector. Gauss-Jordan elimination with partial pivoting is
    performed with whole-row/column vector ops instead of the previous
    single-thread scalar triple loop, so the thread block cooperates and larger
    systems are no longer catastrophically slow. Padding (index >= M) stays zero.
    """
    offs = tl.arange(0, BLOCK)
    rr = offs[:, None]
    cc = offs[None, :]
    mask = (rr < M) & (cc < M)

    Wt = tl.load(W + rr * M + cc, mask=mask, other=0.0)
    Bv = tl.load(B + offs, mask=offs < M, other=0.0)

    for col in range(M):
        # --- Partial pivoting: row (>= col) with the largest |W[r, col]|.
        colvec = tl.sum(tl.where(cc == col, Wt, 0.0), axis=1)  # [BLOCK] = W[:, col]
        cand = tl.where((offs >= col) & (offs < M), tl.abs(colvec), -1.0)
        pmax = tl.max(cand, axis=0)
        prow = tl.min(tl.where(cand == pmax, offs, M), axis=0)

        # --- Swap row `col` and row `prow` in W and B.
        w_row_col = tl.sum(tl.where(rr == col, Wt, 0.0), axis=0)
        w_row_p = tl.sum(tl.where(rr == prow, Wt, 0.0), axis=0)
        Wt = tl.where(rr == col, w_row_p[None, :], Wt)
        Wt = tl.where(rr == prow, w_row_col[None, :], Wt)
        b_col = tl.sum(tl.where(offs == col, Bv, 0.0), axis=0)
        b_p = tl.sum(tl.where(offs == prow, Bv, 0.0), axis=0)
        Bv = tl.where(offs == col, b_p, Bv)
        Bv = tl.where(offs == prow, b_col, Bv)

        # --- Eliminate column `col` from every other row (vectorized).
        # Re-read the pivot column *after* the row swap; colvec above was
        # computed before swapping and is stale once prow != col.
        colvec_s = tl.sum(tl.where(cc == col, Wt, 0.0), axis=1)  # [BLOCK] = W[:, col]
        piv = tl.sum(tl.where((rr == col) & (cc == col), Wt, 0.0), axis=0)
        piv = tl.sum(piv, axis=0)
        prow_w = tl.sum(tl.where(rr == col, Wt, 0.0), axis=0)  # [BLOCK] = W[col, :]
        b_pivrow = tl.sum(tl.where(offs == col, Bv, 0.0), axis=0)  # scalar B[col]
        factor = colvec_s / piv  # [BLOCK] = W[:, col] / W[col, col]
        factor = tl.where(offs == col, 0.0, factor)
        Wt = Wt - factor[:, None] * prow_w[None, :]
        Bv = Bv - factor * b_pivrow

    # After Gauss-Jordan, W is diagonal: x[i] = B[i] / W[i, i].
    diagvec = tl.sum(tl.where(rr == cc, Wt, 0.0), axis=1)  # [BLOCK] = diag(W)
    Xv = tl.where(offs < M, Bv / diagvec, 0.0)
    tl.store(X + offs, Xv, mask=offs < M)


def _tensorsolve_impl(A, B, dims=None):
    logger.debug("GEMS LINALG_TENSORSOLVE")
    assert A.dtype in (
        torch.float32,
        torch.float64,
    ), "linalg_tensorsolve only supports float32 and float64"

    if dims is not None:
        # A = movedim(A, dims, range(len(dims) - A.ndim + 1, 0))
        dest = tuple(range(len(dims) - A.ndim + 1, 0))
        A = torch.movedim(A, dims, dest)

    b_ndim = B.ndim
    result_shape = A.shape[b_ndim:]

    m = 1
    for d in B.shape:
        m *= d
    n = 1
    for d in result_shape:
        n *= d

    if m != n:
        raise RuntimeError(
            "linalg_tensorsolve: prod(A.shape[:B.ndim]) must equal "
            "prod(A.shape[B.ndim:])"
        )

    # Contiguous inputs; the kernel reads them into registers (no host-side clone).
    A_work = A.reshape(m, n).contiguous()
    B_work = B.reshape(m).contiguous()
    X = torch.empty(m, dtype=A.dtype, device=A.device)

    block = triton.next_power_of_2(m)
    grid = (1,)
    with torch.no_grad():
        tensorsolve_kernel[grid](A_work, B_work, X, m, BLOCK=block)

    return X.reshape(result_shape)


def linalg_tensorsolve(A, B, dims=None):
    return _tensorsolve_impl(A, B, dims)


def linalg_tensorsolve_out(A, B, dims=None, *, out):
    result = _tensorsolve_impl(A, B, dims)
    out.copy_(result)
    return out
