# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _eig_2x2_kernel(A, eigenvalues, N, stride_a, stride_e, BLOCK_SIZE: tl.constexpr):
    """Compute eigenvalues of 2x2 symmetric matrices using analytical formula."""
    pid = tl.program_id(0)
    if pid >= N:
        return

    # Load 2x2 matrix elements
    # A is (N, 2, 2) tensor stored as (N, 4)
    a = tl.load(A + pid * stride_a + 0)  # A[0, 0]
    d = tl.load(A + pid * stride_a + 1)  # A[0, 1] or A[1, 0]
    b = tl.load(A + pid * stride_a + 3)  # A[1, 1]

    # For symmetric 2x2 matrix:
    # [a  d]
    # [d  b]
    # eigenvalues = (a+b)/2 +/- sqrt(((a-b)/2)^2 + d^2)

    trace = (a + b) / 2.0
    diff = (a - b) / 2.0
    disc = tl.sqrt(diff * diff + d * d)

    ev1 = trace + disc
    ev2 = trace - disc

    # Sort eigenvalues in ascending order
    ev_min = tl.where(ev1 < ev2, ev1, ev2)
    ev_max = tl.where(ev1 < ev2, ev2, ev1)

    # Store eigenvalues
    tl.store(eigenvalues + pid * stride_e + 0, ev_min)
    tl.store(eigenvalues + pid * stride_e + 1, ev_max)


# NOTE: 3x3 analytical kernel and Jacobi iteration kernel were removed as dead code.
# For n>2, this op falls back to torch.linalg.eigh on CPU (see below).


def linalg_eigh(A, UPLO="L"):
    """
    Compute eigenvalue decomposition of symmetric/Hermitian matrices.

    For 2x2 matrices, uses an analytical formula via Triton kernel.
    For larger matrices, falls back to torch.linalg.eigh on CPU.
    """
    logger.debug("GEMS LINALG_EIGH")

    assert A.dtype.is_floating_point, "linalg_eigh only supports floating point dtypes"  # fmt: skip
    # Check input dimensions
    if A.ndim < 2 or A.shape[-1] != A.shape[-2]:
        raise ValueError(f"Input matrix must be square, got shape {A.shape}")

    # Handle batch dimensions
    batch_shape = A.shape[:-2]
    n = A.shape[-1]
    batch_size = 1
    for dim in batch_shape:
        batch_size *= dim

    # For float16/bfloat32, convert to float32 for computation
    dtype = A.dtype
    if dtype in (torch.float16, torch.bfloat16):
        A = A.to(torch.float32)

    # Handle small matrices with Triton kernels
    if n == 2:
        # Flatten batch dimensions
        A_flat = A.reshape(-1, 2, 2)

        eigenvalues = torch.zeros(A_flat.shape[0], 2, dtype=A.dtype, device=A.device)

        grid = (A_flat.shape[0],)
        _eig_2x2_kernel[grid](
            A_flat,
            eigenvalues,
            A_flat.shape[0],
            A_flat.stride(0),
            eigenvalues.stride(0),
            # BLOCK_SIZE=1: each program processes exactly one 2x2 matrix
            BLOCK_SIZE=1,
        )

        # Vectorized eigenvector computation for 2x2 symmetric matrices.
        # For [a d; d b] with eigenvalues ev1, ev2:
        # eigenvectors are [d; ev1-a] and [d; ev2-a] normalized.
        a_elem = A_flat[:, 0, 0]  # (batch,)
        d_vec = A_flat[:, 0, 1]  # (batch,)
        ev1 = eigenvalues[:, 0]  # (batch,)
        ev2 = eigenvalues[:, 1]  # (batch,)

        # Build un-normalized eigenvectors: shape (batch, 2)
        v1 = torch.stack([d_vec, ev1 - a_elem], dim=1)
        v2 = torch.stack([d_vec, ev2 - a_elem], dim=1)

        # When d is near zero, eigenvectors are the standard basis vectors
        small_d = torch.abs(d_vec) < 1e-10
        v1[small_d, 0] = 1.0
        v1[small_d, 1] = 0.0
        v2[small_d, 0] = 0.0
        v2[small_d, 1] = 1.0

        # Normalize each eigenvector
        v1 = v1 / v1.norm(dim=1, keepdim=True)
        v2 = v2 / v2.norm(dim=1, keepdim=True)

        # Fill eigenvectors tensor: eigenvectors[b, :, k] is k'th eigenvector
        eigenvectors = torch.zeros_like(A_flat)
        eigenvectors[:, 0, 0] = v1[:, 0]
        eigenvectors[:, 0, 1] = v2[:, 0]
        eigenvectors[:, 1, 0] = v1[:, 1]
        eigenvectors[:, 1, 1] = v2[:, 1]

        # Reshape back
        eigenvalues = eigenvalues.reshape(*batch_shape, 2)
        eigenvectors = eigenvectors.reshape(*batch_shape, 2, 2)

    else:
        # NOTE: n>2 falls back to CPU, breaking CUDA graph compatibility.
        # This is a design limitation pending future n>2 kernel implementation.
        # Convert to CPU, compute, then convert back
        A_cpu = A.cpu()
        eigenvalues_cpu, eigenvectors_cpu = torch.linalg.eigh(A_cpu, UPLO=UPLO)
        eigenvalues = eigenvalues_cpu.to(A.device)
        eigenvectors = eigenvectors_cpu.to(A.device)

    # Convert back to original dtype
    if dtype != A.dtype:
        eigenvalues = eigenvalues.to(dtype)
        eigenvectors = eigenvectors.to(dtype)

    return eigenvalues, eigenvectors
