# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging
from typing import Optional, Tuple

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


def compute_output_size(
    input: torch.Tensor,
    indices: torch.Tensor,
    output_size: Optional[Tuple[int, int, int]],
    stride: Optional[Tuple[int, int, int]],
    padding: Optional[Tuple[int, int, int]],
) -> Tuple[int, int, int]:
    """Compute output_size for max_unpool3d.

    The output_size formula is:
    output_size[i] = (pooled_size[i] - 1) * stride[i] + kernel_size[i] - 2 * padding[i]

    Since max_pool typically uses kernel_size = stride, this simplifies to:
    output_size[i] = pooled_size[i] * stride[i]

    When stride is not provided, we assume stride = 2 (common case).
    """
    if output_size is not None:
        return output_size

    N, C, ID, IH, IW = input.shape

    # Default stride is 2 (common for max_pool3d)
    if stride is None:
        stride = (2, 2, 2)

    # Ensure stride is a tuple
    if isinstance(stride, int):
        stride = (stride, stride, stride)

    # Compute output_size: assume kernel_size = stride
    # output_size[i] = pooled_size[i] * stride[i] for kernel_size = stride
    OD = ID * stride[0]
    OH = IH * stride[1]
    OW = IW * stride[2]

    # Adjust for padding
    if padding is not None:
        if isinstance(padding, int):
            padding = (padding, padding, padding)
        OD = OD + 2 * padding[0]
        OH = OH + 2 * padding[1]
        OW = OW + 2 * padding[2]

    return (OD, OH, OW)


@triton.jit
def max_unpool3d_kernel(
    output_ptr,
    input_ptr,
    indices_ptr,
    N,
    C,
    OD,
    OH,
    OW,
    ID,
    IH,
    IW,
    stride_on,
    stride_oc,
    stride_od,
    stride_oh,
    stride_ow,
    stride_in,
    stride_ic,
    stride_id,
    stride_ih,
    stride_iw,
    stride_idxn,
    stride_idxc,
    stride_idxd,
    stride_idxh,
    stride_idxw,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    # Each program processes BLOCK_SIZE elements
    pid = tle.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)

    # Calculate flat index
    num_elements = n_elements

    # Create mask for valid elements
    mask = offsets < num_elements

    # Unflatten offsets to 5D coordinates
    # Input/pooled tensor shape: (N, C, ID, IH, IW)
    idx = offsets

    # Calculate 5D coordinates
    n = idx // (C * ID * IH * IW)
    remainder = idx % (C * ID * IH * IW)
    c = remainder // (ID * IH * IW)
    remainder = remainder % (ID * IH * IW)
    id = remainder // (IH * IW)
    remainder = remainder % (IH * IW)
    ih = remainder // IW
    iw = remainder % IW

    # Load values from input
    input_offset = (
        n * stride_in + c * stride_ic + id * stride_id + ih * stride_ih + iw * stride_iw
    )
    value = tl.load(input_ptr + input_offset, mask=mask)

    # Load indices
    indices_offset = (
        n * stride_idxn
        + c * stride_idxc
        + id * stride_idxd
        + ih * stride_idxh
        + iw * stride_idxw
    )
    flat_idx = tl.load(indices_ptr + indices_offset, mask=mask)

    # Convert flat index to 3D coordinates in output space
    od = flat_idx // (OH * OW)
    remainder_od = flat_idx % (OH * OW)
    oh = remainder_od // OW
    ow = remainder_od % OW

    # Calculate output offset
    output_offset = (
        n * stride_on + c * stride_oc + od * stride_od + oh * stride_oh + ow * stride_ow
    )

    # Store the value at the computed output position
    # Bounds check: flat_idx decoded via OH/OW may produce coordinates
    # outside the output tensor when original input dims are not evenly
    # divisible by stride (e.g. ceil_mode=False MaxPool on odd-sized dims).
    # In that case the index maps beyond the computed output_size, so skip.
    in_bounds = (od >= 0) & (od < OD) & (oh >= 0) & (oh < OH) & (ow >= 0) & (ow < OW)
    tl.store(output_ptr + output_offset, value, mask=mask & in_bounds)


def max_unpool3d(
    input: torch.Tensor,
    indices: torch.Tensor,
    output_size: Optional[Tuple[int, int, int]] = None,
    stride: Optional[Tuple[int, int, int]] = None,
    padding: Optional[Tuple[int, int, int]] = None,
) -> torch.Tensor:
    logger.debug("GEMS MAX_UNPOOL3D")

    assert (
        input.dtype.is_floating_point
    ), "max_unpool3d only supports floating-point dtypes"

    # Compute output_size if not provided
    OD, OH, OW = compute_output_size(input, indices, output_size, stride, padding)

    # Allocate output tensor filled with zeros
    N, C = input.shape[0], input.shape[1]
    output = torch.zeros((N, C, OD, OH, OW), dtype=input.dtype, device=input.device)

    # Flatten tensors for kernel launch
    # Grid: one thread per BLOCK_SIZE elements
    n_elements = input.numel()
    ID, IH, IW = input.shape[2], input.shape[3], input.shape[4]
    # BLOCK_SIZE=1024 balances occupancy and memory bandwidth for typical 3D unpool sizes
    BLOCK_SIZE = 1024

    grid = lambda META: (triton.cdiv(n_elements, BLOCK_SIZE),)

    with torch_device_fn.device(input.device):
        max_unpool3d_kernel[grid](
            output,
            input,
            indices,
            N,
            C,
            OD,
            OH,
            OW,
            ID,
            IH,
            IW,
            *output.stride(),
            *input.stride(),
            *indices.stride(),
            n_elements,
            BLOCK_SIZE,
        )

    return output
