# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)

_pow = tl_extra_shim.pow

# Cap the per-iteration class tile: large class counts are handled by looping
# over C so that register pressure stays bounded.
_MAX_BLOCK_C = 1024
# Below this class count a single unrolled tile beats the looped two-pass form.
_SINGLE_TILE_C = 4096


@libentry()
@triton.jit(do_not_specialize=["p", "margin"])
def multi_margin_loss_backward_kernel(
    grad_output_ptr,
    self_ptr,
    target_ptr,
    weight_ptr,
    out_ptr,
    N,
    C,
    p,
    margin,
    REDUCTION: tl.constexpr,
    HAS_WEIGHT: tl.constexpr,
    IS_FP64: tl.constexpr,
    BLOCK_C: tl.constexpr,
    NUM_BLOCKS: tl.constexpr,
):
    """Compute the gradient of multi_margin_loss with respect to the input.

    For each row i with target index t = target[i], let d_ij = margin - x_it + x_ij.
    The gradient reads
        grad_ij = scale * w[t] / C * p * d_ij^(p-1)   if j != t and d_ij > 0
        grad_it = -sum_j grad_ij (over j != t)
    where scale = grad_output_i for reduction=none, grad_output / N for
    reduction=mean, and grad_output for reduction=sum; w[t] = 1 when no
    class weight is given.
    """
    pid = tle.program_id(0)

    target = tl.load(target_ptr + pid).to(tl.int32)

    if IS_FP64:
        acc_dtype = tl.float64
    else:
        acc_dtype = tl.float32

    x_target = tl.load(self_ptr + pid * C + target)

    # The masking predicate is evaluated in the input dtype to match the
    # reference kernel: a sub-ULP positive difference round to zero there and
    # therefore contributes no gradient.
    margin_in = tl.full([1], margin, dtype=self_ptr.dtype.element_ty)
    d_target = margin_in - x_target

    if HAS_WEIGHT:
        w_target = tl.load(weight_ptr + target).to(acc_dtype)
    else:
        w_target = 1.0

    if REDUCTION == 0:
        go = tl.load(grad_output_ptr + pid)
    else:
        go = tl.load(grad_output_ptr)
    go = go.to(acc_dtype)
    if REDUCTION == 1:
        go = go / N

    p_acc = tl.full([1], p, dtype=acc_dtype)
    exponent = tl.full([1], p - 1.0, dtype=acc_dtype)
    scale = go * w_target / C * p_acc

    # First pass: accumulate the sum of coefficients over the non-target
    # classes, then a second pass writes the per-class gradient.
    total = tl.zeros([BLOCK_C], dtype=acc_dtype)
    for start in range(0, NUM_BLOCKS):
        offset_c = start * BLOCK_C + tl.arange(0, BLOCK_C)
        mask_c = offset_c < C
        x = tl.load(self_ptr + pid * C + offset_c, mask=mask_c, other=0.0)
        d = d_target + x
        active = mask_c & (offset_c != target) & (d > 0)
        coef = tl.where(active, scale * _pow(d.to(acc_dtype), exponent), 0.0)
        total += coef
    row_sum = tl.sum(total)

    for start in range(0, NUM_BLOCKS):
        offset_c = start * BLOCK_C + tl.arange(0, BLOCK_C)
        mask_c = offset_c < C
        x = tl.load(self_ptr + pid * C + offset_c, mask=mask_c, other=0.0)
        d = d_target + x
        active = mask_c & (offset_c != target) & (d > 0)
        coef = tl.where(active, scale * _pow(d.to(acc_dtype), exponent), 0.0)
        # The target class collects the negated sum of the other coefficients.
        grad = tl.where(offset_c == target, -row_sum, coef)
        tl.store(
            out_ptr + pid * C + offset_c,
            grad.to(out_ptr.dtype.element_ty),
            mask=mask_c,
        )


def multi_margin_loss_backward(
    grad_output: torch.Tensor,
    self_tensor: torch.Tensor,
    target: torch.Tensor,
    p,
    margin,
    weight=None,
    reduction=1,
):
    logger.debug("GEMS MULTI_MARGIN_LOSS_BACKWARD")

    assert self_tensor.ndim >= 1, "multi_margin_loss_backward: input must have >= 1 dim"
    if self_tensor.ndim == 1:
        self_tensor = self_tensor.unsqueeze(0)
        target = target.reshape(1)

    N, C = self_tensor.shape

    if weight is not None:
        weight = weight.contiguous()
        has_weight = True
    else:
        has_weight = False

    self_tensor = self_tensor.contiguous()
    target = target.contiguous()
    grad_output = grad_output.contiguous()

    out = torch.empty_like(self_tensor)

    block_c = (
        triton.next_power_of_2(C)
        if C <= _SINGLE_TILE_C
        else min(triton.next_power_of_2(C), _MAX_BLOCK_C)
    )
    grid = (N,)
    with torch_device_fn.device(self_tensor.device):
        multi_margin_loss_backward_kernel[grid](
            grad_output,
            self_tensor,
            target,
            weight,
            out,
            N,
            C,
            float(p),
            float(margin),
            reduction,
            HAS_WEIGHT=has_weight,
            IS_FP64=self_tensor.dtype == torch.float64,
            BLOCK_C=block_c,
            NUM_BLOCKS=triton.cdiv(C, block_c),
        )
    return out
