# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)


@triton.jit
def mvlgamma__kernel(
    x_ptr,
    p_val: tl.constexpr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    x_f32 = x.to(tl.float32)

    # p_val is a Python int (tl.constexpr), convert to float for computation
    p_f32 = tl.cast(p_val, tl.float32)

    # PI defined inside kernel to avoid module-level global (Rule 44)
    PI = tl.constexpr(3.1415926535897932384626433832795028841971)

    # Compute constant C = log(pi) * p * (p - 1) / 4
    C = tl_extra_shim.log(PI) * p_f32 * (p_f32 - 1.0) / 4.0

    # Compute sum: sum_{i=0}^{p-1} lgamma(x - i/2)
    # The formula is: log(Gamma_p(x)) = C + sum_{i=1}^{p} lgamma(x - (i-1)/2)
    # = C + sum_{i=0}^{p-1} lgamma(x - i/2)
    result = tl.zeros_like(x_f32)

    # Use a loop to sum over p terms
    # We need to handle different p values at runtime, so we use a for loop
    for i in range(16):  # Max p is typically small, but we handle up to 16
        i_f32 = i.to(tl.float32)
        cond = i < p_val
        if cond:
            arg = x_f32 - i_f32 / 2.0
            result = result + tl_extra_shim.lgamma(arg)

    result = result + C
    result = result.to(x.dtype)

    tl.store(x_ptr + offsets, result, mask=mask)


def mvlgamma__(A, p=2):
    """
    In-place multivariate log-gamma function.

    Computes the multivariate log-gamma function with dimension p element-wise.

    Args:
        A: Input tensor, must be > (p-1)/2 for all elements
        p: Dimension of the multivariate gamma function (default: 2)

    Returns:
        Tensor with multivariate log-gamma computed in-place
    """
    logger.debug("GEMS MVLGAMMA_")

    if not isinstance(A, torch.Tensor):
        raise TypeError("mvlgamma__ expects a torch.Tensor as the first argument")

    if not A.is_contiguous():
        A = A.contiguous()

    n_elements = A.numel()
    if n_elements == 0:
        return A

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    with torch_device_fn.device(A.device):
        mvlgamma__kernel[grid](A, p, n_elements, BLOCK_SIZE=1024)

    return A


def mvlgamma_(A, p=2):
    """
    Multivariate log-gamma function.

    Computes the multivariate log-gamma function with dimension p element-wise.

    Args:
        A: Input tensor, must be > (p-1)/2 for all elements
        p: Dimension of the multivariate gamma function (default: 2)

    Returns:
        Tensor with multivariate log-gamma computed
    """
    logger.debug("GEMS MVLGAMMA")
    result = A.clone()
    return mvlgamma__(result, p)
