# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
# KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.heuristics(runtime.get_heuristic_config("dropout"))
@triton.jit(do_not_specialize=["scale"])
def native_dropout_backward_kernel(
    DY,
    DX,
    dropout_mask,
    N,
    scale,
    BLOCK: tl.constexpr,
):
    offset = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    mask = offset < N
    m = tl.load(
        dropout_mask + offset, mask=mask, other=0, eviction_policy="evict_first"
    )
    dy = tl.load(DY + offset, mask=mask, other=0, eviction_policy="evict_first")
    dx = dy * m * scale
    tl.store(DX + offset, dx, mask=mask, eviction_policy="evict_first")


def _native_dropout_backward_out_dtype(grad_output):
    if grad_output.is_floating_point() or grad_output.is_complex():
        return grad_output.dtype
    return torch.float32


def native_dropout_backward(grad_output, mask, scale):
    logger.debug("GEMS NATIVE_DROPOUT_BACKWARD")
    mask = mask.contiguous()
    grad_output = grad_output.contiguous()
    grad_input = torch.empty_like(
        grad_output, dtype=_native_dropout_backward_out_dtype(grad_output)
    )
    N = grad_output.numel()
    grid_fn = lambda meta: (triton.cdiv(N, meta["BLOCK"]),)
    with torch_device_fn.device(grad_output.device):
        native_dropout_backward_kernel[grid_fn](grad_output, grad_input, mask, N, scale)
    return grad_input


def native_dropout_backward_out(grad_output, mask, scale, *, out):
    logger.debug("GEMS NATIVE_DROPOUT_BACKWARD_OUT")
    expected_dtype = _native_dropout_backward_out_dtype(grad_output)
    if out.dtype != expected_dtype:
        raise RuntimeError(
            f"Expected out tensor to have dtype {expected_dtype}, but got {out.dtype} instead"
        )
    if out.shape != grad_output.shape:
        out.resize_(grad_output.shape)

    mask = mask.contiguous()
    grad_output = grad_output.contiguous()
    out_contiguous = out if out.is_contiguous() else torch.empty_like(out)
    N = grad_output.numel()
    grid_fn = lambda meta: (triton.cdiv(N, meta["BLOCK"]),)
    with torch_device_fn.device(grad_output.device):
        native_dropout_backward_kernel[grid_fn](
            grad_output, out_contiguous, mask, N, scale
        )
    if out_contiguous is not out:
        out.copy_(out_contiguous)
    return out
