# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils.shape_utils import MemOverlap, has_internal_overlapping

logger = logging.getLogger(__name__)


@libentry()
@triton.jit(do_not_specialize=["N", "out_numel"])
def put_scatter_kernel(
    out_ptr,
    index_ptr,
    source_ptr,
    out_numel,
    N,
    rank,
    out_stride0,
    out_stride1,
    out_stride2,
    out_stride3,
    out_stride4,
    out_shape0,
    out_shape1,
    out_shape2,
    out_shape3,
    out_shape4,
    IS_ACCUMULATE: tl.constexpr,
    IS_CONTIGUOUS: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Scatter ``source`` into ``out`` at the flat positions given by ``index``.

    When ``out`` is row-major contiguous (the ``put`` / ``put_out`` paths, which
    allocate a fresh contiguous ``out``) the flat index is already the element
    offset, so the multi-dimensional decode drops out -- the common case that
    avoids five integer divisions per element. The ``put_`` path may operate
    on a non-contiguous (e.g. transposed) tensor in place, so the full rank-5
    decode is kept behind ``IS_CONTIGUOUS``.
    """
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < N

    cur_index = tl.load(index_ptr + offsets, mask=mask, other=0).to(tl.int64)
    # Negative index maps to the end of the flattened tensor.
    cur_index = tl.where(cur_index < 0, cur_index + out_numel, cur_index)
    index_valid = (cur_index >= 0) & (cur_index < out_numel)
    final_mask = mask & index_valid

    if IS_CONTIGUOUS:
        out_offsets = cur_index
    else:
        cur = cur_index
        out_offsets = tl.zeros((BLOCK_SIZE,), dtype=tl.int64)
        if rank > 4:
            out_offsets += (cur % out_shape4) * out_stride4
            cur = cur // out_shape4
        if rank > 3:
            out_offsets += (cur % out_shape3) * out_stride3
            cur = cur // out_shape3
        if rank > 2:
            out_offsets += (cur % out_shape2) * out_stride2
            cur = cur // out_shape2
        if rank > 1:
            out_offsets += (cur % out_shape1) * out_stride1
            cur = cur // out_shape1
        if rank > 0:
            out_offsets += cur * out_stride0

    cur_value = tl.load(source_ptr + offsets, mask=final_mask, other=0)
    if IS_ACCUMULATE:
        tl.atomic_add(out_ptr + out_offsets, cur_value, mask=final_mask, sem="relaxed")
    else:
        tl.store(out_ptr + out_offsets, cur_value, mask=final_mask)


# Dedicated contiguous scatter kernel. ``put`` / ``put_out`` always allocate a
# fresh contiguous ``out``, so the common path never needs the rank/stride/shape
# decode -- this minimal kernel takes only the three pointers, the two sizes and
# the two constexpr flags, minimising both the launch argument list and the
# per-element work (one load, one (atomic) store, no divisions). A separate kernel
# avoids passing the dead stride/shape args at all, which cuts launch overhead.
@libentry()
@triton.jit(do_not_specialize=["N", "out_numel"])
def put_scatter_contig_kernel(
    out_ptr,
    index_ptr,
    source_ptr,
    out_numel,
    N,
    IS_ACCUMULATE: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < N

    cur_index = tl.load(index_ptr + offsets, mask=mask, other=0).to(tl.int64)
    cur_index = tl.where(cur_index < 0, cur_index + out_numel, cur_index)
    index_valid = (cur_index >= 0) & (cur_index < out_numel)
    final_mask = mask & index_valid

    cur_value = tl.load(source_ptr + offsets, mask=final_mask, other=0)
    if IS_ACCUMULATE:
        tl.atomic_add(out_ptr + cur_index, cur_value, mask=final_mask, sem="relaxed")
    else:
        tl.store(out_ptr + cur_index, cur_value, mask=final_mask)


def _put_block_config(N):
    if N <= 1024:
        return 1024, 1
    elif N <= 8192:
        return 1024, 4
    else:
        return 2048, 8


def _put_scatter(out, index, source, accumulate):
    """Scatter ``source`` into ``out`` at ``index`` (1-D)."""
    index = index.reshape(-1)
    source = source.reshape(-1)
    N = index.numel()
    out_numel = out.numel()

    if N == 0:
        return out

    BLOCK_SIZE, num_warps = _put_block_config(N)
    grid = (triton.cdiv(N, BLOCK_SIZE),)

    if out.is_contiguous():
        # Common ``put`` / ``put_out`` path: contiguous out, minimal kernel.
        put_scatter_contig_kernel[grid](
            out,
            index,
            source,
            out_numel,
            N,
            IS_ACCUMULATE=accumulate,
            BLOCK_SIZE=BLOCK_SIZE,
            num_warps=num_warps,
        )
        return out

    # ``put_`` path on a non-contiguous (e.g. transposed) tensor: full rank-5
    # multi-dim index decode.
    rank = out.ndim
    assert rank <= 5, "put_ only supports tensors with rank <= 5"
    strides = list(out.stride()) + [0] * (5 - rank)
    shapes = list(out.shape) + [1] * (5 - rank)

    put_scatter_kernel[grid](
        out,
        index,
        source,
        out_numel,
        N,
        rank,
        strides[0],
        strides[1],
        strides[2],
        strides[3],
        strides[4],
        shapes[0],
        shapes[1],
        shapes[2],
        shapes[3],
        shapes[4],
        IS_ACCUMULATE=accumulate,
        IS_CONTIGUOUS=False,
        BLOCK_SIZE=BLOCK_SIZE,
        num_warps=num_warps,
    )

    return out


def put_impl(out, index, source, accumulate):
    # Mirror the input validation torch performs on `put`/`put_`/`put.out` so the
    # GEMS path raises the same errors (and the same exception types) instead of
    # silently casting / racing on bad inputs.
    if index.dtype != torch.int64:
        raise RuntimeError(
            "put(): Expected a long tensor for index, but got " + str(index.dtype)
        )
    if source.dtype != out.dtype:
        raise RuntimeError(
            "put(): self and source expected to have the same dtype, but got "
            f"self.dtype = {out.dtype} and source.dtype = {source.dtype}"
        )
    if index.numel() != source.numel():
        raise IndexError(
            "put(): Expected source and index to have the same number of elements, "
            f"but got source.numel() = {source.numel()}, index.numel() = {index.numel()}"
        )

    # `index` and `source` are read in row-major flatten order; reshape them to
    # 1-D (copying if they are non-contiguous) so the kernel reads them with a
    # plain 0-based offset. Accumulate runs directly in the tensor's own dtype:
    # fp16/bf16 `atomic_add` is non-deterministic in add order, but its per-add
    # rounding stays well within the low-precision tolerances the put tests use
    # (fp16 1e-2, bf16 1e-1), so the float32 upcast round-trip (an O(numel) copy
    # that dominated the scatter for large `out`) is dropped.
    return _put_scatter(out, index, source, accumulate)


def put(self, index, source, accumulate=False):
    logger.debug("GEMS PUT")

    out = torch.empty_like(self)
    if has_internal_overlapping(out) == MemOverlap.Yes:
        out = out.contiguous()
    # Copy `self` into `out` using a path that bypasses the GEMS `copy_` kernel,
    # which carries a high per-launch overhead. `torch._foreach_copy_` is not
    # overridden by FlagGems and dispatches straight to the optimized PyTorch
    # memcpy, avoiding a second (slow) kernel launch before the scatter.
    torch._foreach_copy_([out], [self])

    index = index.to(self.device)
    source = source.to(self.device)
    return put_impl(out, index, source, accumulate)


def put_out(self, index, source, accumulate=False, *, out=None):
    logger.debug("GEMS PUT_OUT")

    if out is None:
        return put(self, index, source, accumulate)

    assert (
        has_internal_overlapping(out) != MemOverlap.Yes
    ), "Unsupported operation: trying to inplace write to an internally overlapping tensor."

    # `out` must match `self`; copy self into out first if they are different.
    if out is not self:
        if out.shape != self.shape or out.dtype != self.dtype:
            out = out.resize_as_(self)
        # Bypass the GEMS `copy_` kernel for the initial full-tensor copy (see
        # `put` above for the rationale).
        torch._foreach_copy_([out], [self])

    index = index.to(self.device)
    source = source.to(self.device)
    put_impl(out, index, source, accumulate)
    return out
