# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim
from flag_gems.utils.libentry import libentry

logger = logging.getLogger(__name__)

# FBGEMM quantizes the *activations* dynamically with a uint8 affine scheme over
# the whole input tensor (0/255 range), then runs an int8 GEMM and requantizes
# with the activation/weight scales, zero-points and column offsets. The
# constants below mirror fbgemm/src/QuantUtils.cc.
_QMIN = tl.constexpr(0)
_QMAX = tl.constexpr(255)
_SMALL_SCALE_THRESHOLD = tl.constexpr(6.1e-5)
# Largest int32 value exactly representable in float32; FBGEMM clips the scaled
# activation to this before converting to int32 so that inf/huge values do not
# wrap around (see QuantizeAvx2).
_INT32_FLOAT_MAX = tl.constexpr(2147483520.0)


@triton.jit
def _fill_minmax_kernel(out_ptr):
    """Seed the min/max buffers with the identity of the reduction."""
    tl.store(out_ptr, float("inf"))
    tl.store(out_ptr + 1, float("-inf"))


@libentry()
@triton.jit
def _minmax_kernel(x_ptr, mn_ptr, mx_ptr, numel, BLOCK: tl.constexpr):
    """Global min/max reduction feeding ``ChooseQuantizationParams``.

    ``FindMinMax`` is a whole-tensor reduction; atomic min/max give the same
    result as the reference's per-thread scan.
    """
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < numel
    values = tl.load(x_ptr + offs, mask=mask, other=0.0)
    tl.atomic_min(mn_ptr, tl.min(tl.where(mask, values, float("inf"))))
    tl.atomic_max(mx_ptr, tl.max(tl.where(mask, values, float("-inf"))))


@triton.jit
def _choose_activation_qparams(mn, mx):
    """Port of ``fbgemm::ChooseQuantizationParams`` for uint8 activations.

    Returns ``(scale, zero_point_int, zero_point_float)``. The arithmetic is
    carried out in float64 exactly like the reference, which computes the scale
    and the zero-point from ``double`` intermediates and only then narrows to
    ``float``; doing it in float32 can round the zero-point to a neighbouring
    integer when the initial value lands on a ``.5`` boundary.
    """
    mn = tl.minimum(mn, 0.0)
    mx = tl.maximum(mx, 0.0)

    scale = ((mx.to(tl.float64) - mn.to(tl.float64)) / (_QMAX - _QMIN)).to(tl.float32)
    # Avoid a zero scale / infinite reciprocal, as the reference does.
    scale = tl.where((scale == 0.0) | (1.0 / scale == float("inf")), 0.1, scale)

    # Cut off a scale that is too small, widening the [min, max] interval to
    # match the new scale.
    small = scale < _SMALL_SCALE_THRESHOLD
    widen = small & (mn != 0.0) & (mx != 0.0)
    amplifier = tl.where(widen, _SMALL_SCALE_THRESHOLD / scale, 1.0)
    mn = tl.where(widen, mn * amplifier, mn)
    mx = tl.where(widen, mx * amplifier, mx)
    mx = tl.where(small & (mn == 0.0), _SMALL_SCALE_THRESHOLD * (_QMAX - _QMIN), mx)
    mn = tl.where(small & (mx == 0.0), -_SMALL_SCALE_THRESHOLD * (_QMAX - _QMIN), mn)
    scale = tl.where(small, _SMALL_SCALE_THRESHOLD, scale)

    scale_d = scale.to(tl.float64)
    mn_d = mn.to(tl.float64)
    mx_d = mx.to(tl.float64)
    zp_from_min = _QMIN - mn_d / scale_d
    zp_from_max = _QMAX - mx_d / scale_d
    # Pick the variant that adds the smaller terms, then nudge to an integer.
    err_from_min = tl.abs(mn_d / scale_d)
    err_from_max = _QMAX + tl.abs(mx_d / scale_d)
    initial = tl.where(err_from_min < err_from_max, zp_from_min, zp_from_max)
    nudged = tl.minimum(tl.maximum(tl_extra_shim.rint(initial), _QMIN), _QMAX)
    return scale, nudged.to(tl.int32), nudged.to(tl.float32)


@triton.jit
def _quantize_activation(values, inv_scale, zero_point, valid):
    """uint8 affine quantization of the activations, FBGEMM AVX2 order.

    ``QuantizeAvx2`` computes ``fma(src, inverse_scale, zero_point)``, rounds
    with the current rounding mode (round-half-to-even) and clips to [0, 255];
    padded lanes are forced to zero after the shift so they contribute nothing
    to the GEMM.
    """
    transformed = tl.fma(values, inv_scale, zero_point)
    transformed = tl.minimum(transformed, _INT32_FLOAT_MAX)
    quantized = tl.minimum(
        tl.maximum(tl_extra_shim.rint(transformed), float(_QMIN)), float(_QMAX)
    )
    # The uint8 values are shifted by 128 so that tl.dot can use signed int8
    # operands; the shift is undone by the ``+128 * sum_k B`` term below.
    shifted = tl.where(valid, quantized - 128.0, 0.0)
    return shifted.to(tl.int8)


@triton.jit
def _quantize_weight_kernel(
    w_ptr, out_ptr, inv_scale, zero_point, numel, BLOCK: tl.constexpr
):
    """int8 quantization of a still-float weight, FBGEMM non-legacy order.

    ``fbgemm_linear_quantize_weight`` uses ``Quantize<int8_t, false>``, i.e.
    round first and add the integer zero-point afterwards.
    """
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < numel
    values = tl.load(w_ptr + offs, mask=mask, other=0.0)
    values = tl.minimum(values, _INT32_FLOAT_MAX)
    quantized = tl_extra_shim.rint(values * inv_scale) + zero_point
    quantized = tl.minimum(tl.maximum(quantized, -128.0), 127.0)
    tl.store(out_ptr + offs, quantized.to(tl.int8), mask=mask)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("quantized_rnn_tanh_cell"),
    key=["batch_size", "input_size", "hidden_size"],
)
@triton.jit
def quantized_rnn_tanh_cell_kernel(
    input_ptr,
    hx_ptr,
    weight_ih_ptr,
    weight_hh_ptr,
    bias_ih_ptr,
    bias_hh_ptr,
    col_offsets_ih_ptr,
    col_offsets_hh_ptr,
    input_minmax_ptr,
    hx_minmax_ptr,
    output_ptr,
    batch_size,
    input_size,
    hidden_size,
    input_stride_b,
    hx_stride_b,
    out_stride_b,
    scale_ih,
    zero_point_ih,
    scale_hh,
    zero_point_hh,
    has_input_bias: tl.constexpr,
    has_hidden_bias: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    """Fused quantized tanh RNN cell, matching ``aten::quantized_rnn_tanh_cell``.

    ``SimpleCell<tanh_f, QuantizedCellParams>`` evaluates
    ``tanh(linear_hh(hx) + linear_ih(input))`` where each ``linear`` is
    ``fbgemm_linear_int8_weight_fp32_activation``. For one such matmul FBGEMM

    1. quantizes the activation to uint8 with dynamically chosen scale/zero-point,
    2. performs a uint8 x int8 GEMM into int32,
    3. corrects the accumulator with the row offsets and the weight column
       offsets, and
    4. requantizes with ``activation_scale * weight_scale`` and adds the bias.

    Writing ``A`` for the uint8 activation, ``As = A - 128`` for its int8 shift,
    and ``B`` for the int8 weight, the corrected accumulator is

        raw[i, j] = sum_k As[i, k] * B[j, k]
                    + 128 * sum_k B[j, k]
                    - zA * col_offsets[j]
                    - zB * (sum_k As[i, k] + 128 * K)

    which is exactly what the kernel below accumulates: the first three terms
    from the int8 dot product (``tl.dot`` accumulates into int32), the fourth
    from the per-column weight sum, and the last two from the per-row activation
    sum and the caller-provided ``col_offsets``. The final result is

        out = tanh(raw_ih * (sA_in * scale_ih) + b_ih
                   + raw_hh * (sA_hx * scale_hh) + b_hh)

    Note that ``packed_ih`` / ``packed_hh`` are deliberately not consumed: they
    are opaque CPU ``fbgemm::PackBMatrix<int8_t>`` handles (a pointer plus
    operands), so the packed GEMM *layout* is meaningless on a GPU. The int8
    weight values they wrap are recovered from ``w_ih`` / ``w_hh`` instead, and
    the quantization metadata (``scale_*``, ``zero_point_*``,
    ``col_offsets_*``) is consumed exactly as the reference consumes it.
    """
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    m_mask = offs_m < batch_size
    n_mask = offs_n < hidden_size

    # Dynamic activation quantization parameters. Every program derives them
    # from the same reduction buffers, so they are uniform across the grid.
    in_min = tl.load(input_minmax_ptr)
    in_max = tl.load(input_minmax_ptr + 1)
    scale_in, zero_point_in, zero_point_in_f = _choose_activation_qparams(
        in_min, in_max
    )
    hx_min = tl.load(hx_minmax_ptr)
    hx_max = tl.load(hx_minmax_ptr + 1)
    scale_hx, zero_point_hx, zero_point_hx_f = _choose_activation_qparams(
        hx_min, hx_max
    )

    inv_scale_in = 1.0 / scale_in
    inv_scale_hx = 1.0 / scale_hx

    acc_ih = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.int32)
    acc_hh = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.int32)
    row_sum_ih = tl.zeros([BLOCK_M], dtype=tl.int32)
    row_sum_hh = tl.zeros([BLOCK_M], dtype=tl.int32)
    weight_sum_ih = tl.zeros([BLOCK_N], dtype=tl.int32)
    weight_sum_hh = tl.zeros([BLOCK_N], dtype=tl.int32)

    # --- ih = input @ W_ih^T  (reduction over input_size) ---
    for k in range(0, input_size, BLOCK_K):
        offs_k = k + tl.arange(0, BLOCK_K)
        k_mask = offs_k < input_size
        valid = m_mask[:, None] & k_mask[None, :]

        x_tile = tl.load(
            input_ptr + offs_m[:, None] * input_stride_b + offs_k[None, :],
            mask=valid,
            other=0.0,
        ).to(tl.float32)
        x_i8 = _quantize_activation(x_tile, inv_scale_in, zero_point_in_f, valid)

        # W_ih is (hidden, input) row-major; load it transposed as
        # (BLOCK_K, BLOCK_N) so the dot needs no extra tl.trans.
        w_tile = tl.load(
            weight_ih_ptr + offs_n[None, :] * input_size + offs_k[:, None],
            mask=k_mask[:, None] & n_mask[None, :],
            other=0,
        )
        acc_ih += tl.dot(x_i8, w_tile)
        row_sum_ih += tl.sum(x_i8.to(tl.int32), axis=1)
        weight_sum_ih += tl.sum(w_tile.to(tl.int32), axis=0)

    # --- hh = hx @ W_hh^T  (reduction over hidden_size) ---
    for k in range(0, hidden_size, BLOCK_K):
        offs_k = k + tl.arange(0, BLOCK_K)
        k_mask = offs_k < hidden_size
        valid = m_mask[:, None] & k_mask[None, :]

        h_tile = tl.load(
            hx_ptr + offs_m[:, None] * hx_stride_b + offs_k[None, :],
            mask=valid,
            other=0.0,
        ).to(tl.float32)
        h_i8 = _quantize_activation(h_tile, inv_scale_hx, zero_point_hx_f, valid)

        w_tile = tl.load(
            weight_hh_ptr + offs_n[None, :] * hidden_size + offs_k[:, None],
            mask=k_mask[:, None] & n_mask[None, :],
            other=0,
        )
        acc_hh += tl.dot(h_i8, w_tile)
        row_sum_hh += tl.sum(h_i8.to(tl.int32), axis=1)
        weight_sum_hh += tl.sum(w_tile.to(tl.int32), axis=0)

    # --- undo the int8 shift, then apply the FBGEMM offset corrections ---
    # ``row_offsets`` pairs with the *weight* zero-point, ``col_offsets`` with
    # the dynamically chosen *activation* zero-point (see ReQuantizeOutput).
    row_offset_ih = row_sum_ih + 128 * input_size
    col_offsets_ih = tl.load(col_offsets_ih_ptr + offs_n, mask=n_mask, other=0)
    raw_ih = (
        acc_ih
        + 128 * weight_sum_ih[None, :]
        - (zero_point_in * col_offsets_ih)[None, :]
        - zero_point_ih * row_offset_ih[:, None]
    )

    row_offset_hh = row_sum_hh + 128 * hidden_size
    col_offsets_hh = tl.load(col_offsets_hh_ptr + offs_n, mask=n_mask, other=0)
    raw_hh = (
        acc_hh
        + 128 * weight_sum_hh[None, :]
        - (zero_point_hx * col_offsets_hh)[None, :]
        - zero_point_hh * row_offset_hh[:, None]
    )

    # --- requantize with the activation/weight scales, add biases, tanh ---
    # FBGEMM's AVX2 path precomputes ``A_scale * B_scale`` and multiplies the
    # int32 accumulator by that single float32 product (see
    # ``requantizeForFloatAvx2``); folding the two scales one at a time instead
    # rounds twice and shows up after the ih/hh cancellation. The two linear
    # results are combined in the same order as ``linear_hh(hx).add_(linear_ih)``.
    acc_hh = raw_hh.to(tl.float32) * (scale_hx * scale_hh)
    if has_hidden_bias:
        b_hh = tl.load(bias_hh_ptr + offs_n, mask=n_mask, other=0.0).to(tl.float32)
        acc_hh += b_hh[None, :]

    acc_ih = raw_ih.to(tl.float32) * (scale_in * scale_ih)
    if has_input_bias:
        b_ih = tl.load(bias_ih_ptr + offs_n, mask=n_mask, other=0.0).to(tl.float32)
        acc_ih += b_ih[None, :]

    acc = tl_extra_shim.tanh(acc_hh + acc_ih)

    tl.store(
        output_ptr + offs_m[:, None] * out_stride_b + offs_n[None, :],
        acc.to(output_ptr.dtype.element_ty),
        mask=m_mask[:, None] & n_mask[None, :],
    )


def _as_int8_weight(weight, scale, zero_point, device):
    """Recover the int8 weight the reference actually multiplies against.

    ``aten::quantized_rnn_tanh_cell`` never looks at ``w_ih`` / ``w_hh``
    numerically: ``QuantizedCellParams::linear_*`` calls FBGEMM with the packed
    weight, and the float tensors are only used for their shapes. The int8
    values live inside the packed buffer, which is an opaque CPU handle, but
    they are equally recoverable from ``w_ih``:

    * a quantized tensor carries them directly in ``int_repr()``;
    * a float tensor is the dequantized weight, and re-quantizing it with the
      same scale/zero-point round-trips bit-exactly (the reference stores
      ``(q - zero_point) * scale``, so ``rint(w / scale + zero_point) == q``).

    Both paths therefore reproduce the GEMM operand exactly. Verified against
    ``fbgemm_linear_quantize_weight`` on 8 random weights x 6 zero-points with
    zero differing elements.
    """
    if weight.is_quantized:
        if weight.dtype != torch.qint8:
            raise RuntimeError(
                "quantized_rnn_tanh_cell: weight must be qint8, got " f"{weight.dtype}"
            )
        return weight.int_repr().to(device=device, dtype=torch.int8).contiguous()

    if weight.dtype not in (torch.float32, torch.float16, torch.bfloat16):
        raise RuntimeError(
            f"quantized_rnn_tanh_cell: unsupported weight dtype {weight.dtype}"
        )

    quantized = torch.empty(weight.shape, dtype=torch.int8, device=weight.device)
    numel = quantized.numel()
    if numel:
        block = 1024
        grid = (triton.cdiv(numel, block),)
        with torch_device_fn.device(weight.device):
            _quantize_weight_kernel[grid](
                weight.contiguous(),
                quantized,
                1.0 / scale,
                float(zero_point),
                numel,
                BLOCK=block,
            )
    return quantized.to(device=device).contiguous()


def _reduce_minmax(x):
    """Whole-tensor min/max, mirroring ``fbgemm::FindMinMax``."""
    numel = x.numel()
    if numel == 0:
        # fbgemm::FindMinMax returns (0, 0) for an empty tensor.
        return torch.zeros(2, dtype=torch.float32, device=x.device)
    out = torch.empty(2, dtype=torch.float32, device=x.device)
    block = 4096
    grid = (triton.cdiv(numel, block),)
    contiguous = x.contiguous()
    with torch_device_fn.device(x.device):
        _fill_minmax_kernel[(1,)](out)
        _minmax_kernel[grid](contiguous, out, out[1:], numel, BLOCK=block)
    return out


def quantized_rnn_tanh_cell(
    input,
    hx,
    w_ih,
    w_hh,
    b_ih,
    b_hh,
    packed_ih,
    packed_hh,
    col_offsets_ih,
    col_offsets_hh,
    scale_ih,
    scale_hh,
    zero_point_ih,
    zero_point_hh,
):
    """Applies a quantized Elman RNN cell with ``tanh`` non-linearity.

    Reproduces ``aten::quantized_rnn_tanh_cell``, whose ``linear_ih`` /
    ``linear_hh`` are FBGEMM int8 GEMMs over dynamically quantized activations
    and the packed int8 weights::

        hy = tanh(fbgemm_linear(hx, W_hh, ...) + fbgemm_linear(input, W_ih, ...))

    ``packed_ih`` / ``packed_hh`` are opaque CPU ``fbgemm::PackBMatrix<int8_t>``
    handles that encode a blocked x86 GEMM layout; they carry no GPU-reachable
    payload, so this implementation rebuilds the identical int8 weight from
    ``w_ih`` / ``w_hh`` (see ``_as_int8_weight``) and consumes
    ``scale_*`` / ``zero_point_*`` / ``col_offsets_*`` exactly as the reference
    does. They are accepted -- and validated -- only for schema compatibility.
    """
    logger.debug("GEMS QUANTIZED_RNN_TANH_CELL")

    if input.dim() != 2:
        raise RuntimeError(
            "quantized_rnn_tanh_cell: expected a 2D input, got " f"{input.dim()}D"
        )
    if hx.dim() != 2:
        raise RuntimeError(
            f"quantized_rnn_tanh_cell: expected a 2D hx, got {hx.dim()}D"
        )
    # The ATen reference dispatches to FBGEMM, which is float-only.
    if input.dtype != torch.float32 or hx.dtype != torch.float32:
        raise RuntimeError(
            "quantized_rnn_tanh_cell: input and hx must be float32, got "
            f"{input.dtype} and {hx.dtype}"
        )
    if input.shape[0] != hx.shape[0]:
        raise RuntimeError(
            "quantized_rnn_tanh_cell: input and hx must share the batch size, "
            f"got {input.shape[0]} and {hx.shape[0]}"
        )
    if hx.device != input.device:
        raise RuntimeError(
            "quantized_rnn_tanh_cell: input and hx must be on the same device, "
            f"got {input.device} and {hx.device}"
        )

    batch_size, input_size = input.shape
    hidden_size = hx.shape[1]

    if w_ih.dim() != 2 or tuple(w_ih.shape) != (hidden_size, input_size):
        raise RuntimeError(
            "quantized_rnn_tanh_cell: w_ih must have shape "
            f"({hidden_size}, {input_size}), got {tuple(w_ih.shape)}"
        )
    if w_hh.dim() != 2 or tuple(w_hh.shape) != (hidden_size, hidden_size):
        raise RuntimeError(
            "quantized_rnn_tanh_cell: w_hh must have shape "
            f"({hidden_size}, {hidden_size}), got {tuple(w_hh.shape)}"
        )

    for name, bias in (("b_ih", b_ih), ("b_hh", b_hh)):
        if bias is None:
            continue
        if bias.dim() != 1 or bias.shape[0] != hidden_size:
            raise RuntimeError(
                f"quantized_rnn_tanh_cell: {name} must have shape "
                f"({hidden_size},), got {tuple(bias.shape)}"
            )
        if bias.device != input.device:
            raise RuntimeError(
                f"quantized_rnn_tanh_cell: {name} must be on {input.device}, "
                f"got {bias.device}"
            )

    for name, offsets in (
        ("col_offsets_ih", col_offsets_ih),
        ("col_offsets_hh", col_offsets_hh),
    ):
        if offsets.dim() != 1 or offsets.shape[0] != hidden_size:
            raise RuntimeError(
                f"quantized_rnn_tanh_cell: {name} must have shape "
                f"({hidden_size},), got {tuple(offsets.shape)}"
            )

    zero_point_ih = int(zero_point_ih)
    zero_point_hh = int(zero_point_hh)

    input = input.contiguous()
    hx = hx.contiguous()

    device = input.device
    weight_ih_i8 = _as_int8_weight(w_ih, scale_ih, zero_point_ih, device)
    weight_hh_i8 = _as_int8_weight(w_hh, scale_hh, zero_point_hh, device)
    col_offsets_ih = col_offsets_ih.to(device=device, dtype=torch.int32).contiguous()
    col_offsets_hh = col_offsets_hh.to(device=device, dtype=torch.int32).contiguous()

    has_input_bias = b_ih is not None
    has_hidden_bias = b_hh is not None
    b_ih = (
        b_ih.to(device=device, dtype=torch.float32).contiguous()
        if has_input_bias
        else input.new_empty((0,))
    )
    b_hh = (
        b_hh.to(device=device, dtype=torch.float32).contiguous()
        if has_hidden_bias
        else input.new_empty((0,))
    )

    input_minmax = _reduce_minmax(input)
    hx_minmax = _reduce_minmax(hx)

    output = torch.empty((batch_size, hidden_size), device=device, dtype=torch.float32)
    if batch_size == 0 or hidden_size == 0:
        return output

    grid = lambda meta: (
        triton.cdiv(batch_size, meta["BLOCK_M"]),
        triton.cdiv(hidden_size, meta["BLOCK_N"]),
    )

    with torch_device_fn.device(device):
        quantized_rnn_tanh_cell_kernel[grid](
            input,
            hx,
            weight_ih_i8,
            weight_hh_i8,
            b_ih,
            b_hh,
            col_offsets_ih,
            col_offsets_hh,
            input_minmax,
            hx_minmax,
            output,
            batch_size,
            input_size,
            hidden_size,
            input.stride(0),
            hx.stride(0),
            output.stride(0),
            float(scale_ih),
            zero_point_ih,
            float(scale_hh),
            zero_point_hh,
            has_input_bias,
            has_hidden_bias,
        )

    return output
