# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def replication_pad1d_backward_kernel(
    grad_out_ptr,
    grad_in_ptr,
    B: tl.constexpr,
    C: tl.constexpr,
    W_in,
    W_out,
    pad_left,
    pad_right,
    grad_out_stride_n,
    grad_out_stride_c,
    grad_out_stride_w,
    grad_in_stride_n,
    grad_in_stride_c,
    grad_in_stride_w,
    BLOCK_SIZE: tl.constexpr,
):
    """
    Backward pass for replication_pad1d.

    Strategy:
    - Each program handles one (N, C) slice
    - Left edge (w_in=0): sum grad_out[0:pad_left+1]
    - Middle (0 < w_in < W_in-1): direct copy grad_out[pad_left+w_in]
    - Right edge (w_in=W_in-1): sum grad_out[pad_left+W_in-1:W_out]

    Optimizations:
    - Scalar accumulation for edges (2 elements) to minimize overhead
    - Vectorized loads for middle elements (most data)
    - No atomics required

    Performance note: This operator is memory bandwidth bound with small
    shapes where launch overhead dominates. PyTorch's native CUDA kernel
    is highly optimized for this simple operation.
    """
    pid_nc = tl.program_id(axis=0)

    n = pid_nc // C
    c = pid_nc % C

    # Base offsets
    base_out = n.to(tl.int64) * grad_out_stride_n + c.to(tl.int64) * grad_out_stride_c
    base_in = n.to(tl.int64) * grad_in_stride_n + c.to(tl.int64) * grad_in_stride_c

    # Handle left edge (w_in=0): accumulate grad_out[0:pad_left+1]
    if W_in >= 1:
        left_acc = 0.0
        for i in range(min(pad_left + 1, W_out)):
            ptr = grad_out_ptr + base_out + i * grad_out_stride_w
            left_acc += tl.load(ptr)
        ptr_in = grad_in_ptr + base_in
        tl.store(ptr_in, left_acc.to(grad_out_ptr.dtype.element_ty))

    # Handle middle elements: direct 1:1 mapping (vectorized)
    for block_start in range(1, W_in - 1, BLOCK_SIZE):
        w_in = block_start + tl.arange(0, BLOCK_SIZE)
        mask = w_in < W_in - 1

        w_out = pad_left + w_in
        out_mask = mask & (w_out < W_out)

        out_offset = w_out.to(tl.int64) * grad_out_stride_w
        out_ptr = grad_out_ptr + base_out + out_offset
        val = tl.load(out_ptr, mask=out_mask, other=0.0)

        in_offset = w_in.to(tl.int64) * grad_in_stride_w
        in_ptr = grad_in_ptr + base_in + in_offset
        tl.store(in_ptr, val.to(grad_out_ptr.dtype.element_ty), mask=mask)

    # Handle right edge (w_in=W_in-1): accumulate grad_out[pad_left+W_in-1:W_out]
    if W_in >= 2:
        right_acc = 0.0
        right_start = pad_left + W_in - 1
        for i in range(right_start, W_out):
            ptr = grad_out_ptr + base_out + i * grad_out_stride_w
            right_acc += tl.load(ptr)
        ptr_in = grad_in_ptr + base_in + (W_in - 1) * grad_in_stride_w
        tl.store(ptr_in, right_acc.to(grad_out_ptr.dtype.element_ty))
    elif W_in == 1:
        # Special case: only one element, accumulate all output
        acc = 0.0
        for i in range(W_out):
            ptr = grad_out_ptr + base_out + i * grad_out_stride_w
            acc += tl.load(ptr)
        ptr_in = grad_in_ptr + base_in
        tl.store(ptr_in, acc.to(grad_out_ptr.dtype.element_ty))


def _launch_replication_pad1d_backward_kernel(
    grad_output: torch.Tensor,
    self_tensor: torch.Tensor,
    padding,
    grad_input: torch.Tensor,
):
    if isinstance(padding, torch.Tensor):
        padding = tuple(padding.tolist())
    left, right = int(padding[0]), int(padding[1])

    dim = self_tensor.dim()
    if dim not in (2, 3):
        raise ValueError(
            "replication_pad1d_backward expects 2D (C, W) or 3D (N, C, W) input"
        )

    if dim == 3:
        N, C, W_in = self_tensor.shape
        B = N
        grad_in_s_n, grad_in_s_c, grad_in_s_w = grad_input.stride()
        grad_out_s_n, grad_out_s_c, grad_out_s_w = grad_output.stride()
    else:
        C, W_in = self_tensor.shape
        B = 1
        grad_in_s_c, grad_in_s_w = grad_input.stride()
        grad_in_s_n = 0
        if grad_output.dim() == 2:
            grad_out_s_c, grad_out_s_w = grad_output.stride()
            grad_out_s_n = 0
        elif grad_output.dim() == 3:
            grad_out_s_n, grad_out_s_c, grad_out_s_w = grad_output.stride()
        else:
            raise ValueError("grad_output has invalid dimensions")

    W_out = W_in + left + right

    # Validate shapes
    expected_grad_output_shape = (N, C, W_out) if dim == 3 else (C, W_out)
    if tuple(grad_output.shape) != expected_grad_output_shape:
        raise ValueError(
            f"grad_output has incorrect shape. Expected {expected_grad_output_shape}, got {tuple(grad_output.shape)}"
        )

    if tuple(grad_input.shape) != tuple(self_tensor.shape):
        raise ValueError(
            f"grad_input has incorrect shape. Expected {tuple(self_tensor.shape)}, got {tuple(grad_input.shape)}"
        )

    # Grid: one block per (N, C) combination
    grid = (B * C,)
    BLOCK_SIZE = 256

    with torch_device_fn.device(grad_output.device):
        replication_pad1d_backward_kernel[grid](
            grad_output,
            grad_input,
            B,
            C,
            W_in,
            W_out,
            left,
            right,
            grad_out_s_n if dim == 3 else grad_out_s_n,
            grad_out_s_c,
            grad_out_s_w,
            grad_in_s_n if dim == 3 else grad_in_s_n,
            grad_in_s_c,
            grad_in_s_w,
            BLOCK_SIZE=BLOCK_SIZE,
        )
    return grad_input


def replication_pad1d_backward(
    grad_output: torch.Tensor, self_tensor: torch.Tensor, padding
) -> torch.Tensor:
    logger.debug("GEMS REPLICATION_PAD1D_BACKWARD")
    if isinstance(padding, torch.Tensor):
        padding = tuple(padding.tolist())
    left, right = int(padding[0]), int(padding[1])

    dim = self_tensor.dim()
    if dim == 3:
        N, C, W_in = self_tensor.shape
        grad_input = torch.empty(
            (N, C, W_in),
            device=grad_output.device,
            dtype=grad_output.dtype,
        )
    elif dim == 2:
        C, W_in = self_tensor.shape
        grad_input = torch.empty(
            (C, W_in),
            device=grad_output.device,
            dtype=grad_output.dtype,
        )
    else:
        raise ValueError(
            "replication_pad1d_backward expects 2D (C, W) or 3D (N, C, W) input"
        )

    return _launch_replication_pad1d_backward_kernel(
        grad_output, self_tensor, (left, right), grad_input
    )
