# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry, tl_extra_shim

_tanh = tl_extra_shim.tanh

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=[
        triton.Config({"BLOCK_H": 32, "BLOCK_K": 64}, num_warps=2, num_stages=2),
        triton.Config({"BLOCK_H": 64, "BLOCK_K": 64}, num_warps=4, num_stages=2),
        triton.Config({"BLOCK_H": 128, "BLOCK_K": 64}, num_warps=4, num_stages=2),
        triton.Config({"BLOCK_H": 64, "BLOCK_K": 128}, num_warps=4, num_stages=2),
    ],
    key=["batch_size", "input_size", "hidden_size"],
)
@triton.jit
def rnn_tanh_cell_kernel(
    input_ptr,
    hx_ptr,
    w_ih_ptr,
    w_hh_ptr,
    b_ih_ptr,
    b_hh_ptr,
    out_ptr,
    batch_size,
    input_size,
    hidden_size,
    IS_FP64: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    """
    Triton kernel for the single-timestep Elman RNN cell with tanh activation:

        h' = tanh(x @ W_ih^T + b_ih + h @ W_hh^T + b_hh)

    Grid: (batch_size * cdiv(hidden_size, BLOCK_H),).  Each program computes
    one BLOCK_H-sized slice of the hidden state for one batch element, looping
    over the contraction dimensions (input_size, hidden_size) in BLOCK_K-sized
    chunks.  The products are accumulated in float32 (or float64 for double
    inputs) before the tanh non-linearity is applied.
    """
    pid = tl.program_id(0)
    num_h_blocks = tl.cdiv(hidden_size, BLOCK_H)
    batch_idx = pid // num_h_blocks
    if batch_idx >= batch_size:
        return

    hid_start = (pid % num_h_blocks) * BLOCK_H
    h_offs = hid_start + tl.arange(0, BLOCK_H)
    h_mask = h_offs < hidden_size
    k_offs = tl.arange(0, BLOCK_K)

    if IS_FP64:
        acc = tl.zeros([BLOCK_H], dtype=tl.float64)
    else:
        acc = tl.zeros([BLOCK_H], dtype=tl.float32)

    # --- ih = W_ih @ x + b_ih ---
    x_base = input_ptr + batch_idx * input_size
    for k_start in range(0, input_size, BLOCK_K):
        kk = k_start + k_offs
        k_mask = kk < input_size
        w_offs = h_offs[:, None] * input_size + kk[None, :]
        w_mask = h_mask[:, None] & k_mask[None, :]
        w_tile = tl.load(w_ih_ptr + w_offs, mask=w_mask, other=0.0)
        x_val = tl.load(x_base + kk, mask=k_mask, other=0.0)
        if not IS_FP64:
            w_tile = w_tile.to(tl.float32)
            x_val = x_val.to(tl.float32)
        acc += tl.sum(w_tile * x_val[None, :], axis=1)

    if b_ih_ptr is not None:
        b_ih = tl.load(b_ih_ptr + h_offs, mask=h_mask, other=0.0)
        if not IS_FP64:
            b_ih = b_ih.to(tl.float32)
        acc += b_ih

    # --- hh = W_hh @ h + b_hh ---
    h_base = hx_ptr + batch_idx * hidden_size
    for k_start in range(0, hidden_size, BLOCK_K):
        kk = k_start + k_offs
        k_mask = kk < hidden_size
        w_offs = h_offs[:, None] * hidden_size + kk[None, :]
        w_mask = h_mask[:, None] & k_mask[None, :]
        w_tile = tl.load(w_hh_ptr + w_offs, mask=w_mask, other=0.0)
        h_val = tl.load(h_base + kk, mask=k_mask, other=0.0)
        if not IS_FP64:
            w_tile = w_tile.to(tl.float32)
            h_val = h_val.to(tl.float32)
        acc += tl.sum(w_tile * h_val[None, :], axis=1)

    if b_hh_ptr is not None:
        b_hh = tl.load(b_hh_ptr + h_offs, mask=h_mask, other=0.0)
        if not IS_FP64:
            b_hh = b_hh.to(tl.float32)
        acc += b_hh

    # --- h' = tanh(ih + hh) ---
    h_new = _tanh(acc)
    tl.store(
        out_ptr + batch_idx * hidden_size + h_offs,
        h_new.to(out_ptr.dtype.element_ty),
        mask=h_mask,
    )


def rnn_tanh_cell(input, hx, w_ih, w_hh, b_ih=None, b_hh=None):
    """Applies a single-timestep Elman RNN cell with tanh activation.

    h' = tanh(x @ W_ih^T + b_ih + h @ W_hh^T + b_hh)
    """
    logger.debug("GEMS RNN_TANH_CELL")

    if input.dim() != 2:
        raise RuntimeError(
            "GEMS rnn_tanh_cell expects 2D input of shape (batch, input_size), "
            f"got {tuple(input.shape)}"
        )
    if hx.dim() != 2:
        raise RuntimeError(
            "GEMS rnn_tanh_cell expects 2D hx of shape (batch, hidden_size), "
            f"got {tuple(hx.shape)}"
        )

    batch_size, input_size = input.shape
    hidden_size = w_ih.shape[0]

    if hx.shape != (batch_size, hidden_size):
        raise RuntimeError(
            "GEMS rnn_tanh_cell: hx shape "
            f"{tuple(hx.shape)} does not match (batch={batch_size}, "
            f"hidden={hidden_size})"
        )
    if w_ih.shape != (hidden_size, input_size):
        raise RuntimeError(
            f"GEMS rnn_tanh_cell: w_ih shape {tuple(w_ih.shape)} does not match "
            f"({hidden_size}, {input_size})"
        )
    if w_hh.shape != (hidden_size, hidden_size):
        raise RuntimeError(
            f"GEMS rnn_tanh_cell: w_hh shape {tuple(w_hh.shape)} does not match "
            f"({hidden_size}, {hidden_size})"
        )

    input = input.contiguous()
    hx = hx.contiguous()
    w_ih = w_ih.contiguous()
    w_hh = w_hh.contiguous()
    if b_ih is not None:
        b_ih = b_ih.contiguous()
    if b_hh is not None:
        b_hh = b_hh.contiguous()

    out = torch.empty((batch_size, hidden_size), dtype=input.dtype, device=input.device)
    if out.numel() == 0:
        return out

    is_fp64 = input.dtype == torch.float64
    grid = lambda META: (  # noqa: E731
        batch_size * triton.cdiv(hidden_size, META["BLOCK_H"]),
    )

    rnn_tanh_cell_kernel[grid](
        input,
        hx,
        w_ih,
        w_hh,
        b_ih,
        b_hh,
        out,
        batch_size,
        input_size,
        hidden_size,
        IS_FP64=is_fp64,
    )

    return out
