# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(
    is_tensor=[True, True, False, False],
    num_outputs=2,
    promotion_methods=[
        (0, 1, "DEFAULT"),
        (0, 1, "DEFAULT"),
    ],
)
@triton.jit
def rrelu_with_noise_forward(self, noise, lower, upper):
    # RReLU: if x >= 0: out = x, else: out = x * noise
    # noise is pre-generated uniform random in [lower, upper]
    out = tl.where(self >= 0, self, self * noise)
    return out, noise


def rrelu_with_noise_functional(
    self, noise, lower=0.125, upper=0.33333333333333331, training=False, generator=None
):
    logger.debug("GEMS RRELU_WITH_NOISE_FUNCTIONAL")
    assert noise.shape == self.shape, "noise tensor must have the same shape as self"
    assert generator is None, "generator is not supported in FlagGems"

    if not training:
        # When training=False (eval mode), use deterministic slope for computation
        # but still return the original noise tensor as noise_out
        slope = (lower + upper) * 0.5
        # Create a temporary tensor for computation (filled with slope)
        noise_tmp = torch.full_like(self, slope)
        output = rrelu_with_noise_forward(self, noise_tmp, lower, upper)
        # output[0] is the result, output[1] is the noise (which is slope-filled temp)
        # We need to return original noise as noise_out
        return output[0], noise
    else:
        output = rrelu_with_noise_forward(self, noise, lower, upper)
        return output


def rrelu_with_noise_functional_(
    self, noise, lower=0.125, upper=0.33333333333333331, training=False, generator=None
):
    logger.debug("GEMS RRELU_WITH_NOISE_FUNCTIONAL_")
    assert noise.shape == self.shape, "noise tensor must have the same shape as self"
    assert generator is None, "generator is not supported in FlagGems"

    if not training:
        # When training=False (eval mode), use deterministic slope
        slope = (lower + upper) * 0.5
        noise_tmp = torch.full_like(self, slope)
        output = rrelu_with_noise_forward(self, noise_tmp, lower, upper)
        return output[0], noise
    else:
        output = rrelu_with_noise_forward(self, noise, lower, upper)
        return output
