# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def slice_copy_kernel(
    inp_ptr,
    out_ptr,
    numel,
    inner,
    slice_len,
    dim_size,
    start,
    step,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)

    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < numel

    # Decompose the flat output index into (outer_idx, slice_idx, inner_idx)
    outer_idx = offsets // (slice_len * inner)
    slice_idx = (offsets // inner) % slice_len
    inner_idx = offsets % inner

    # Map the slice position back into the input dimension: start + slice_idx * step
    dim_index = start + slice_idx * step

    input_offset = outer_idx * dim_size * inner + dim_index * inner + inner_idx

    val = tl.load(inp_ptr + input_offset, mask=mask)
    tl.store(out_ptr + offsets, val, mask=mask)


# Fast path for slicing the trailing dimension (``inner == 1``). With no inner
# axis the index math collapses to a single division: ``outer_idx = offsets //
# slice_len`` and ``slice_idx = offsets % slice_len`` (the inner modulo and the
# multiply by ``inner`` both drop out). This is the shape exercised by the
# standard benchmark, which slices a 2-D tensor along dim 1 with step > 1.
@libentry()
@triton.jit
def slice_copy_kernel_inner1(
    inp_ptr,
    out_ptr,
    numel,
    slice_len,
    dim_size,
    start,
    step,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < numel

    outer_idx = offsets // slice_len
    slice_idx = offsets - outer_idx * slice_len
    dim_index = start + slice_idx * step

    input_offset = outer_idx * dim_size + dim_index

    val = tl.load(inp_ptr + input_offset, mask=mask)
    tl.store(out_ptr + offsets, val, mask=mask)


# Fast path for the common ``step == 1`` contiguous slice. Avoids the three
# integer divisions of the general kernel: the input offset is a plain affine
# function of the flat output index, so a single gather copy is enough. This
# dominates the workloads where ``slice_copy`` is actually hot (loading a
# contiguous sub-range of a tensor along one dim).
@libentry()
@triton.jit
def slice_copy_kernel_step1(
    inp_ptr,
    out_ptr,
    numel,
    inner,
    slice_len,
    dim_size,
    start,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < numel

    outer_idx = offsets // (slice_len * inner)
    inner_idx = offsets % inner
    slice_idx = offsets // inner - outer_idx * slice_len

    dim_index = start + slice_idx
    input_offset = outer_idx * dim_size * inner + dim_index * inner + inner_idx

    val = tl.load(inp_ptr + input_offset, mask=mask)
    tl.store(out_ptr + offsets, val, mask=mask)


def _resolve_slice_bounds(dim_size, start, end, step):
    # step must be positive (validated by the caller)
    if start is None:
        start = 0
    if end is None:
        end = dim_size
    if start < 0:
        start += dim_size
    if end < 0:
        end += dim_size
    start = max(0, min(start, dim_size))
    end = max(0, min(end, dim_size))
    return start, end


def _slice_copy_impl(inp, dim, start, end, step, out):
    if step <= 0:
        # PyTorch only supports positive step for slice_copy.
        raise RuntimeError("slice step must be positive")

    ndim = inp.ndim
    if dim < 0:
        dim += ndim
    if dim < 0 or dim >= ndim:
        raise RuntimeError(
            f"Dimension out of range (expected to be in range of "
            f"[{-ndim}, {ndim - 1}], but got {dim})"
        )

    dim_size = inp.size(dim)
    start, end = _resolve_slice_bounds(dim_size, start, end, step)
    slice_len = max(0, (end - start + step - 1) // step)

    if out is None:
        out_shape = list(inp.shape)
        out_shape[dim] = slice_len
        out = torch.empty(out_shape, dtype=inp.dtype, device=inp.device)
    else:
        if out.dtype != inp.dtype:
            raise RuntimeError(
                "slice_copy expected out tensor to have the same dtype as input"
            )
        target_shape = list(inp.shape)
        target_shape[dim] = slice_len
        if list(out.shape) != target_shape:
            out.resize_(target_shape)

    if out.numel() == 0:
        return out

    # Work on a contiguous view of the input so the simple flat-index mapping holds.
    inp = inp.contiguous()

    inner = 1
    for d in range(dim + 1, inp.ndim):
        inner *= inp.size(d)

    numel = out.numel()

    # BLOCK_SIZE 512 balances bandwidth saturation on large tensors against
    # avoiding wasted work on small ones.
    BLOCK_SIZE = 512
    grid = (triton.cdiv(numel, BLOCK_SIZE),)

    if inner == 1:
        # Trailing-dim slice (incl. step > 1): one integer division instead of
        # three. This is the benchmark's common case (2-D tensor, dim=1).
        slice_copy_kernel_inner1[grid](
            inp,
            out,
            numel,
            slice_len,
            dim_size,
            start,
            step,
            BLOCK_SIZE=BLOCK_SIZE,
        )
    elif step == 1:
        # The contiguous-slice fast path: the input dim index is ``start + i``,
        # so the gather reduces to a single affine offset with no per-element
        # multiply (only one division/modulo instead of three).
        slice_copy_kernel_step1[grid](
            inp,
            out,
            numel,
            inner,
            slice_len,
            dim_size,
            start,
            BLOCK_SIZE=BLOCK_SIZE,
        )
    else:
        slice_copy_kernel[grid](
            inp,
            out,
            numel,
            inner,
            slice_len,
            dim_size,
            start,
            step,
            BLOCK_SIZE=BLOCK_SIZE,
        )

    return out


def slice_copy(inp, dim=0, start=None, end=None, step=1):
    logger.debug("GEMS SLICE_COPY")
    return _slice_copy_impl(inp, dim, start, end, step, out=None)


def slice_copy_out(inp, dim=0, start=None, end=None, step=1, *, out):
    logger.debug("GEMS SLICE_COPY_OUT")
    return _slice_copy_impl(inp, dim, start, end, step, out=out)
