# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Triton implementation of ``aten::slow_conv_transpose3d`` (forward).

Semantics (im2col / col2im form):

  out[n, co, od, oh, ow] = bias[co]
      + sum_{ci, kd, kh, kw} self[n, ci, id, ih, iw] * weight[ci, co, kd, kh, kw]

  id = od + pad_d - kd*dil_d, valid iff id % stride_d == 0 and 0 <= id/stride_d < D_in
  (and likewise for h / w).

``weight`` uses the transposed-conv layout (C_in, C_out, kD, kH, kW) and no
kernel flipping is applied.  The implementation is a deterministic
output-stationary tiled gather: every program computes a (BLOCK_CO, BLOCK_SP)
tile of the output plane by accumulating an implicit GEMM whose K axis is
C_in*kD*kH*kW.
"""

import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)

__all__ = ["slow_conv_transpose3d"]


def _as_triple(value, name, default):
    if value is None:
        value = default
    if torch.is_tensor(value):
        if value.dim() == 0:
            value = [int(value.item())]
        else:
            value = [int(v) for v in value.tolist()]
    elif isinstance(value, (int, float)):
        value = [int(value)]
    else:
        value = [int(v) for v in value]
    if len(value) == 1:
        value = value * 3
    if len(value) != 3:
        raise RuntimeError(
            "%s must be a single integer or a sequence of 3 integers" % name
        )
    return value


def _cdiv(a, b):
    return -(-a // b)


def _np2_at_least(v, lo):
    p = lo
    while p < v:
        p *= 2
    return p


@triton.jit
def _sct3d_fwd_kernel(
    x_ptr,
    w_ptr,
    b_ptr,
    o_ptr,
    C_in,
    C_out,
    S,
    W_out,
    HW,
    D_in,
    H_in,
    W_in,
    sC,
    sD,
    sH,
    sW,
    sN,
    wCi,
    wCo,
    wKd,
    wKh,
    wKw,
    oC,
    oD,
    oH,
    oW,
    oN,
    NSP,
    kD: tl.constexpr,
    kH: tl.constexpr,
    kW: tl.constexpr,
    stD,
    stH,
    stW,
    paD,
    paH,
    paW,
    diD,
    diH,
    diW,
    HAS_BIAS: tl.constexpr,
    DOT: tl.constexpr,
    ST1: tl.constexpr,
    F64: tl.constexpr,
    BLOCK_SP: tl.constexpr,
    BLOCK_CO: tl.constexpr,
    BLOCK_CI: tl.constexpr,
):
    pid0 = tl.program_id(0)
    pid1 = tl.program_id(1)

    n = pid0 // NSP
    sp0 = (pid0 % NSP) * BLOCK_SP
    sp = sp0 + tl.arange(0, BLOCK_SP)
    spm = sp < S

    od = sp // HW
    rem = sp - od * HW
    oh = rem // W_out
    ow = rem - oh * W_out

    co = pid1 * BLOCK_CO + tl.arange(0, BLOCK_CO)
    com = co < C_out

    x_n = x_ptr + n * sN

    if F64:
        acc = tl.zeros((BLOCK_CO, BLOCK_SP), dtype=tl.float64)
    else:
        acc = tl.zeros((BLOCK_CO, BLOCK_SP), dtype=tl.float32)

    if DOT:
        ci = tl.arange(0, BLOCK_CI)
        for kd in tl.static_range(kD):
            idr = od + paD - kd * diD
            if ST1:
                vd = (idr >= 0) & (idr < D_in)
                id_ = idr
            else:
                vd = (idr >= 0) & (idr < D_in * stD) & (idr % stD == 0)
                id_ = idr // stD
            for kh in tl.static_range(kH):
                ihr = oh + paH - kh * diH
                if ST1:
                    vh = (ihr >= 0) & (ihr < H_in)
                    ih_ = ihr
                else:
                    vh = (ihr >= 0) & (ihr < H_in * stH) & (ihr % stH == 0)
                    ih_ = ihr // stH
                vdh = vd & vh & spm
                off_dh = id_ * sD + ih_ * sH
                for kw in tl.static_range(kW):
                    iwr = ow + paW - kw * diW
                    if ST1:
                        vw = (iwr >= 0) & (iwr < W_in)
                        iw_ = iwr
                    else:
                        vw = (iwr >= 0) & (iwr < W_in * stW) & (iwr % stW == 0)
                        iw_ = iwr // stW
                    m = vdh & vw
                    xoff = x_n + off_dh + iw_ * sW
                    woff = w_ptr + kd * wKd + kh * wKh + kw * wKw
                    for c0 in range(0, C_in, BLOCK_CI):
                        cci = c0 + ci
                        ok = cci < C_in
                        xt = tl.load(
                            xoff[None, :] + (cci * sC)[:, None],
                            mask=m[None, :] & ok[:, None],
                            other=0.0,
                        )
                        wt = tl.load(
                            woff + (co * wCo)[:, None] + (cci * wCi)[None, :],
                            mask=com[:, None] & ok[None, :],
                            other=0.0,
                        )
                        acc = tl.dot(wt, xt, acc, input_precision="ieee")
    else:
        for kd in tl.static_range(kD):
            idr = od + paD - kd * diD
            if ST1:
                vd = (idr >= 0) & (idr < D_in)
                id_ = idr
            else:
                vd = (idr >= 0) & (idr < D_in * stD) & (idr % stD == 0)
                id_ = idr // stD
            for kh in tl.static_range(kH):
                ihr = oh + paH - kh * diH
                if ST1:
                    vh = (ihr >= 0) & (ihr < H_in)
                    ih_ = ihr
                else:
                    vh = (ihr >= 0) & (ihr < H_in * stH) & (ihr % stH == 0)
                    ih_ = ihr // stH
                vdh = vd & vh & spm
                off_dh = id_ * sD + ih_ * sH
                for kw in tl.static_range(kW):
                    iwr = ow + paW - kw * diW
                    if ST1:
                        vw = (iwr >= 0) & (iwr < W_in)
                        iw_ = iwr
                    else:
                        vw = (iwr >= 0) & (iwr < W_in * stW) & (iwr % stW == 0)
                        iw_ = iwr // stW
                    m = vdh & vw
                    xoff = x_n + off_dh + iw_ * sW
                    woff = w_ptr + kd * wKd + kh * wKh + kw * wKw
                    for c in range(0, C_in):
                        xr = tl.load(xoff + c * sC, mask=m, other=0.0)
                        wr = tl.load(woff + c * wCi + co * wCo, mask=com, other=0.0)
                        acc = acc + wr[:, None] * xr[None, :]

    if HAS_BIAS:
        bv = tl.load(b_ptr + co, mask=com, other=0.0)
        acc = acc + bv[:, None]

    ooff = o_ptr + n * oN + (co * oC)[:, None] + (od * oD + oh * oH + ow * oW)[None, :]
    tl.store(ooff, acc.to(o_ptr.dtype.element_ty), mask=com[:, None] & spm[None, :])


def _pow2_leq(value, lo, hi):
    """Largest power of two in [lo, hi] that does not exceed value (or lo)."""
    p = lo
    best = lo
    while p <= value and p <= hi:
        best = p
        p *= 2
    return best


def _pick_blocks(S, C_out, N, min_programs=200):
    """Choose ``(BLOCK_SP, BLOCK_CO)`` for the flat output-plane decomposition.

    A wider channel tile means fewer redundant passes over the gathered
    activation plane, so BLOCK_CO is taken as large as the register budget and
    the dtype's dot shape allow.  BLOCK_SP is then the largest spatial tile that
    still leaves at least one full 78-SM device wave of programs; when no tiling
    reaches that floor, the configuration with the most programs is used so the
    machine is at least partly occupied.  The 1x1x1 GEMM-like case is included
    only by the 16-wide spatial tile, which is the finest the masks allow.
    """
    bsp_max = _np2_at_least(max(S, 1), 16)
    bco_max = _pow2_leq(C_out, 16, 32)
    for bsp in (64, 32, 16):
        if bsp > bsp_max:
            continue
        if N * _cdiv(S, bsp) * _cdiv(C_out, bco_max) >= min_programs:
            return bsp, bco_max

    best = None
    for bsp in (16, 32, 64):
        if bsp > bsp_max:
            continue
        for bco in (16, 32, 64):
            if bco > _np2_at_least(max(C_out, 1), 16):
                continue
            progs = N * _cdiv(S, bsp) * _cdiv(C_out, bco)
            key = (progs, bco, bsp)
            if best is None or key > best[0]:
                best = (key, bsp, bco)
    if best is None:
        return 16, 16
    return best[1], best[2]


def slow_conv_transpose3d(
    self,
    weight,
    kernel_size=None,
    bias=None,
    stride=1,
    padding=0,
    output_padding=0,
    dilation=1,
    out=None,
):
    logger.debug("GEMS SLOW_CONV_TRANSPOSE3D")
    inp = self
    if not torch.is_tensor(inp) or not torch.is_tensor(weight):
        raise TypeError("slow_conv_transpose3d expects tensor inputs")

    st = _as_triple(stride, "stride", 1)
    pa = _as_triple(padding, "padding", 0)
    op = _as_triple(output_padding, "output_padding", 0)
    dl = _as_triple(dilation, "dilation", 1)

    if inp.dim() not in (4, 5):
        raise RuntimeError(
            "slow_conv_transpose3d: expected 4D or 5D input, got %dD" % inp.dim()
        )
    if weight.dim() != 5:
        raise RuntimeError(
            "slow_conv_transpose3d: expected 5D weight, got %dD" % weight.dim()
        )
    if not inp.is_floating_point() or not weight.is_floating_point():
        raise RuntimeError(
            "slow_conv_transpose3d not implemented for non-floating point dtypes"
        )
    if any(s <= 0 for s in st):
        raise RuntimeError("slow_conv_transpose3d: stride must be greater than zero")
    if any(d <= 0 for d in dl):
        raise RuntimeError("slow_conv_transpose3d: dilation must be greater than zero")
    if any(p < 0 for p in pa):
        raise RuntimeError("slow_conv_transpose3d: padding must be non-negative")
    for i in range(3):
        if op[i] >= max(st[i], dl[i]):
            raise RuntimeError(
                "slow_conv_transpose3d: output padding must be smaller than either "
                "stride or dilation"
            )

    unbatched = inp.dim() == 4
    x = inp.unsqueeze(0) if unbatched else inp

    N, C_in, D_in, H_in, W_in = x.shape
    if weight.shape[0] != C_in:
        raise RuntimeError(
            "slow_conv_transpose3d: weight.shape[0] (%d) must match input channels (%d)"
            % (weight.shape[0], C_in)
        )
    kD, kH, kW = weight.shape[2], weight.shape[3], weight.shape[4]
    if kernel_size is not None:
        ks = _as_triple(kernel_size, "kernel_size", 1)
        if tuple(ks) != (kD, kH, kW):
            raise RuntimeError(
                "slow_conv_transpose3d: kernel_size %s does not match weight spatial "
                "dims %s" % (tuple(ks), (kD, kH, kW))
            )
    C_out = weight.shape[1]
    if bias is not None:
        if not torch.is_tensor(bias):
            raise TypeError("slow_conv_transpose3d: bias must be a Tensor or None")
        if bias.numel() != C_out:
            raise RuntimeError(
                "slow_conv_transpose3d: bias size (%d) must match C_out (%d)"
                % (bias.numel(), C_out)
            )

    D_out = (D_in - 1) * st[0] - 2 * pa[0] + dl[0] * (kD - 1) + op[0] + 1
    H_out = (H_in - 1) * st[1] - 2 * pa[1] + dl[1] * (kH - 1) + op[1] + 1
    W_out = (W_in - 1) * st[2] - 2 * pa[2] + dl[2] * (kW - 1) + op[2] + 1

    shape = (N, C_out, D_out, H_out, W_out)
    if out is None:
        out_t = torch.empty(shape, device=x.device, dtype=x.dtype)
    else:
        if not torch.is_tensor(out):
            raise TypeError("slow_conv_transpose3d: out must be a Tensor")
        if tuple(out.shape) != shape:
            raise RuntimeError(
                "slow_conv_transpose3d: out shape %s does not match expected %s"
                % (tuple(out.shape), shape)
            )
        out_t = out

    S = D_out * H_out * W_out
    if out_t.numel() == 0 or S == 0:
        return out_t.squeeze(0) if unbatched else out_t

    dtype = x.dtype
    if dtype is torch.float64:
        f64 = True
    elif dtype in (torch.float32, torch.float16, torch.bfloat16):
        f64 = False
    else:
        raise RuntimeError("slow_conv_transpose3d: unsupported dtype %s" % str(dtype))
    # The fp32 ieee tl.dot needs 255 registers and spills heavily; the scalar
    # FMA outer-product path keeps fp32 fully in registers.  Tensor cores stay
    # in use for the low-precision dtypes, where they are cheap.
    dot = dtype in (torch.float16, torch.bfloat16)

    BLOCK_SP, BLOCK_CO = _pick_blocks(S, C_out, N)
    BLOCK_CI = min(_np2_at_least(max(C_in, 1), 16), 64)

    NSP = _cdiv(S, BLOCK_SP)
    grid = (N * NSP, _cdiv(C_out, BLOCK_CO))

    # The scalar outer-product path holds the whole (BLOCK_CO, BLOCK_SP)
    # accumulator in registers and walks C_in serially, so its throughput comes
    # from per-thread instruction-level parallelism rather than from covered
    # latency.  Once the tile is large, giving the whole tile to one warp beats
    # spreading it thin: measured 1.6-2x on the fp32 shapes with C_in <= 16 and
    # a >= 1024-element tile.
    num_warps = 1 if (not dot) and C_in <= 16 and BLOCK_SP * BLOCK_CO >= 1024 else 4

    _sct3d_fwd_kernel[grid](
        x,
        weight,
        bias if bias is not None else x,
        out_t,
        C_in,
        C_out,
        S,
        W_out,
        H_out * W_out,
        D_in,
        H_in,
        W_in,
        x.stride(1),
        x.stride(2),
        x.stride(3),
        x.stride(4),
        x.stride(0),
        weight.stride(0),
        weight.stride(1),
        weight.stride(2),
        weight.stride(3),
        weight.stride(4),
        out_t.stride(1),
        out_t.stride(2),
        out_t.stride(3),
        out_t.stride(4),
        out_t.stride(0),
        NSP,
        kD,
        kH,
        kW,
        st[0],
        st[1],
        st[2],
        pa[0],
        pa[1],
        pa[2],
        dl[0],
        dl[1],
        dl[2],
        HAS_BIAS=bias is not None,
        DOT=dot,
        ST1=(st[0] == 1 and st[1] == 1 and st[2] == 1),
        F64=f64,
        BLOCK_SP=BLOCK_SP,
        BLOCK_CO=BLOCK_CO,
        BLOCK_CI=BLOCK_CI,
        num_warps=num_warps,
    )

    return out_t.squeeze(0) if unbatched else out_t
