# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, "DEFAULT")])
@triton.jit
def special_round_func(x, scale):
    """Round to nearest integer with ties to even (banker's rounding)."""
    x_f32 = (x * scale).to(tl.float32)

    # Banker's rounding: round half to even.
    # Decompose into sign, absolute value, and fractional part.
    sign = tl.where(x_f32 >= 0.0, 1.0, -1.0)
    abs_x = tl.math.abs(x_f32)
    floor_x = tl.math.floor(abs_x)
    frac = abs_x - floor_x
    is_even = (floor_x % 2.0) == 0.0

    # Round up when frac > 0.5, down when frac < 0.5, to even when frac == 0.5.
    rounded_abs = tl.where(
        frac > 0.5,
        floor_x + 1.0,
        tl.where(
            frac < 0.5,
            floor_x,
            tl.where(is_even, floor_x, floor_x + 1.0),
        ),
    )
    result = sign * rounded_abs

    return (result / scale).to(x.dtype)


def special_round(A, *, decimals=0):
    logger.debug("GEMS SPECIAL_ROUND")
    scale = float(10**decimals)
    return special_round_func(A, scale)


def special_round_out(A, *, decimals=0, out=None):
    logger.debug("GEMS SPECIAL_ROUND_OUT")
    scale = float(10**decimals)
    if out is None:
        return special_round_func(A, scale)
    special_round_func(A, scale, out0=out)
    return out
