# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger("flag_gems." + __name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT"), (1, "DEFAULT")])
@triton.jit
def special_legendre_polynomial_p_forward(x, n):
    """Compute the Legendre polynomial P_n(x) using recurrence relation.

    P_0(x) = 1
    P_1(x) = x
    P_{n+1}(x) = 2*x*P_n(x) - P_{n-1}(x)
    """
    n_val = n.to(tl.int32)

    # Handle n < 0 case - return 0
    result = tl.where(n_val < 0, tl.zeros(1, dtype=x.dtype), x)

    # P_0(x) = 1
    result = tl.where(n_val == 0, tl.full((1,), 1.0, dtype=x.dtype), result)

    # P_1(x) = x
    result = tl.where(n_val == 1, x, result)

    # For n > 1, use recurrence relation
    # P_{n+1}(x) = 2*x*P_n(x) - P_{n-1}(x)
    # We compute iteratively from P_0 and P_1
    p_prev2 = tl.full((1,), 1.0, dtype=x.dtype)  # P_0
    p_prev1 = x  # P_1

    # Use a for loop to compute higher order polynomials
    for i in range(
        2, 256
    ):  # Loop bound 256 covers degree up to n=255, sufficient for typical usage
        # Only compute if n >= i
        mask = n_val >= i
        p_curr = tl.where(mask, 2.0 * x * p_prev1 - p_prev2, p_prev1)
        p_prev2 = tl.where(mask, p_prev1, p_prev2)
        p_prev1 = p_curr

    # Final result
    result = tl.where(n_val > 1, p_prev1, result)

    return result


def special_legendre_polynomial_p(x: torch.Tensor, n: torch.Tensor) -> torch.Tensor:
    logger.debug("GEMS SPECIAL_LEGENDRE_POLYNOMIAL_P")
    assert x.dtype == torch.float32, "only float32 supported"
    return special_legendre_polynomial_p_forward(x, n)
