# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def y0_func(x):
    xf = x.to(tl.float32)
    y = tl_extra_shim.y0(xf)
    # y0 is only defined for x > 0. libdevice agrees with the reference on
    # negative inputs, zero and nan, but returns 0.0 at +inf where the reference
    # returns nan, so that single case is corrected here.
    return tl.where(xf == float("inf"), float("nan"), y)


def special_bessel_y0(A):
    logger.debug("GEMS SPECIAL_BESSEL_Y0")
    return y0_func(A)
