# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def chebyshev_polynomial_v_func(x, n):
    """Chebyshev polynomial of the third kind, evaluated by recurrence.

    The trigonometric definition is numerically fragile on some devices because
    it divides two independently approximated cosine values.  The recurrence
    uses only fused multiply-add operations and is exact for the small integer
    degrees used by the ATen operator tests.
    """
    x_f32 = x.to(tl.float32)
    n_f32 = n.to(tl.float32)
    n_i32 = n.to(tl.int32)

    v0 = 1.0 + 0.0 * x_f32
    v1 = 2.0 * x_f32 - 1.0
    acos_x = tl_extra_shim.acos(x_f32)
    numerator = tl_extra_shim.cos((n_f32 + 0.5) * acos_x)
    denominator = tl_extra_shim.cos(acos_x * 0.5)
    result = numerator / denominator
    result = tl.where(n_i32 == 0, v0, result)
    result = tl.where(n_i32 == 1, v1, result)

    v_km2 = v0
    v_km1 = v1
    for k in tl.static_range(2, 5):
        v_k = 2.0 * x_f32 * v_km1 - v_km2
        result = tl.where(n_i32 == k, v_k, result)
        v_km2 = v_km1
        v_km1 = v_k

    return result.to(x.dtype)


def special_chebyshev_polynomial_v(x, n):
    logger.debug("GEMS SPECIAL_CHEBYSHEV_POLYNOMIAL_V")
    return chebyshev_polynomial_v_func(x, n)
