# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

import flag_gems
from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def special_scaled_modified_bessel_k1_kernel(
    x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    x_f32 = x.to(tl.float32)

    # Handle x <= 0: return inf for x=0, handle negative values
    # K_1 is not defined for x <= 0, but we'll handle the singularity at x=0
    zero = 0.0
    ax = tl.abs(x_f32)
    is_zero = ax < 1e-30  # close to zero
    is_negative = x_f32 < zero

    # For scaled K1: scaled_K1(x) = exp(x) * x * K_1(x)
    # Using polynomial approximation from Cephes/scipy

    # Small region: 0 < x <= 2.0
    # Use series expansion for small x
    t_small = x_f32 * x_f32
    p_small = -0.5 + t_small * (
        -0.625
        + t_small
        * (
            0.2916666666666667
            + t_small
            * (
                -0.06875
                + t_small * (0.008680555555555555 + t_small * -0.0003854166666666667)
            )
        )
    )
    # Add the leading 1/x term that's part of K1(x) expansion
    # The full expansion for small x: x*K1(x)*exp(x) = 1 + (-0.5)*x^2 + ...
    small_result = 1.0 + p_small

    # For large region: x > 2.0
    # Use asymptotic expansion
    y = 2.0 / ax
    p_big = 1.2533141373155 + y * (
        -0.0783232033301
        + y
        * (
            0.0218950680508
            + y * (-0.0030107026380 + y * (0.0003240681134 + y * -0.0001273162979))
        )
    )
    big_result = p_big * tl.sqrt(ax)

    # Combine results
    use_small = ax <= 2.0
    result = tl.where(use_small, small_result, big_result)

    # Handle singularity at x=0 -> infinity
    # Handle negative inputs: return inf (following scipy behavior)
    result = tl.where(is_zero, float("inf"), result)
    result = tl.where(is_negative, float("inf"), result)

    # Cast back to input dtype and store
    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


def _launch_special_scaled_modified_bessel_k1(out: torch.Tensor, x: torch.Tensor):
    if x.device.type != flag_gems.device or out.device.type != flag_gems.device:
        raise ValueError(f"Tensors must be {flag_gems.device} tensors")
    assert (
        out.numel() == x.numel()
    ), "Input and output must have the same number of elements"
    assert out.device == x.device, "Input and output must be on the same device"

    x_in = x
    out_in = out

    # Ensure floating point compute
    if not x_in.is_floating_point():
        x_in = x_in.to(torch.get_default_dtype())

    # Cast input to match the desired output dtype if needed
    if x_in.dtype != out_in.dtype:
        x_in = x_in.to(out_in.dtype)

    x_contig = x_in.contiguous()
    out_was_noncontig = not out_in.is_contiguous()
    out_contig = out_in.contiguous() if out_was_noncontig else out_in

    n_elements = out_contig.numel()
    if n_elements == 0:
        return

    # Balance occupancy and register pressure for Bessel kernel
    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        special_scaled_modified_bessel_k1_kernel[grid](
            x_contig, out_contig, n_elements, BLOCK_SIZE=BLOCK_SIZE
        )

    if out_was_noncontig:
        out_in.copy_(out_contig)
    return out_in


def special_scaled_modified_bessel_k1(x: torch.Tensor):
    logger.debug("GEMS SPECIAL_SCALED_MODIFIED_BESSEL_K1")
    if x.device.type != flag_gems.device:
        raise ValueError(
            "special_scaled_modified_bessel_k1: input tensor must be on CUDA device"
        )
    # Result dtype follows PyTorch's floating type behavior
    out_dtype = x.dtype if x.is_floating_point() else torch.get_default_dtype()
    out = torch.empty_like(x.to(dtype=out_dtype), dtype=out_dtype, device=x.device)
    _launch_special_scaled_modified_bessel_k1(out, x)
    return out


def special_scaled_modified_bessel_k1_out(x: torch.Tensor, out: torch.Tensor):
    logger.debug("GEMS SPECIAL_SCALED_MODIFIED_BESSEL_K1_OUT")
    if x.device.type != flag_gems.device or out.device.type != flag_gems.device:
        raise ValueError(
            "special_scaled_modified_bessel_k1_out: input and output tensors must be on CUDA device"
        )
    if not out.is_floating_point():
        raise TypeError(
            "special_scaled_modified_bessel_k1_out: output tensor must be a floating point type"
        )
    if x.numel() != out.numel():
        raise ValueError(
            "special_scaled_modified_bessel_k1_out: input and output must have the same number of elements"
        )
    _launch_special_scaled_modified_bessel_k1(out, x)
    return out
