# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def gammaincc_func(a, x):
    """
    Regularized upper incomplete gamma function: Q(a, x) = Γ(a, x) / Γ(a)

    Uses the relationship: Q(a, x) = 1 - P(a, x) where P is the lower incomplete gamma.

    Implementation based on Numerical Recipes:
    - For x < a + 1: use series expansion for P
    - For x >= a + 1: use continued fraction for Q
    """
    # Convert to float32
    a_f32 = a.to(tl.float32)
    x_f32 = x.to(tl.float32)

    # Edge cases
    edge_case = (a_f32 <= 0.0) | (x_f32 < 0.0)
    zero_x = x_f32 == 0.0
    zero_a = a_f32 == 0.0
    pos_a = a_f32 > 0.0
    pos_x = x_f32 > 0.0

    # Safe values
    a_safe = tl.where(a_f32 > 0.0, a_f32, 1.0)
    x_safe = tl.where(x_f32 > 0.0, x_f32, 1.0)

    # Compute log(Γ(a)) using Stirling's series with more terms
    a2 = a_safe * a_safe
    a3 = a2 * a_safe
    a4 = a3 * a_safe
    a5 = a4 * a_safe

    log_gamma_a = (a_safe - 0.5) * tl.log(a_safe) - a_safe + 0.5 * tl.log(6.28318530718)
    log_gamma_a = log_gamma_a + 1.0 / (12.0 * a_safe)
    log_gamma_a = log_gamma_a - 1.0 / (360.0 * a3)
    log_gamma_a = log_gamma_a + 1.0 / (1260.0 * a5)

    # ==== Series expansion for P(a,x) when x < a + 1 ====
    log_p0 = -x_safe + a_f32 * tl.log(x_safe) - log_gamma_a
    p0 = tl.exp(log_p0)

    # Series sum
    series_sum = 1.0
    series_sum = series_sum + x_safe / a_safe
    series_sum = series_sum + (x_safe * x_safe) / (a_safe * (a_safe + 1.0)) * 0.5
    series_sum = series_sum + (x_safe * x_safe * x_safe) / (
        a_safe * (a_safe + 1.0) * (a_safe + 2.0)
    ) * (1.0 / 3.0)
    series_sum = (
        series_sum
        + (x_safe * x_safe * x_safe * x_safe)
        / (a_safe * (a_safe + 1.0) * (a_safe + 2.0) * (a_safe + 3.0))
        * 0.25
    )

    p_series = p0 * series_sum
    p_clamped = tl.where(p_series > 1.0, 1.0, tl.where(p_series < 0.0, 0.0, p_series))
    q_from_p = 1.0 - p_clamped

    # ==== Asymptotic expansion for Q when x >= a + 1 ====
    # Q(a,x) ≈ e^(-x) * x^(a-1) * [1 + (a-1)/x + (a-1)(a-2)/x^2 + ...]
    log_q = -x_safe + (a_f32 - 1.0) * tl.log(x_safe)

    # Correction terms
    corr = 1.0
    corr = corr + (a_f32 - 1.0) / x_safe
    corr = corr + (a_f32 - 1.0) * (a_f32 - 2.0) / (x_safe * x_safe)
    corr = (
        corr
        + (a_f32 - 1.0)
        * (a_f32 - 2.0)
        * (a_f32 - 3.0)
        / (x_safe * x_safe * x_safe)
        * 0.5
    )
    corr = (
        corr
        + (a_f32 - 1.0)
        * (a_f32 - 2.0)
        * (a_f32 - 3.0)
        * (a_f32 - 4.0)
        / (x_safe * x_safe * x_safe * x_safe)
        * 0.25
    )

    q_asymp = tl.exp(log_q) * corr
    q_clamped = tl.where(q_asymp > 1.0, 1.0, tl.where(q_asymp < 0.0, 0.0, q_asymp))

    # Use threshold at a + 1
    use_series = x_f32 < (a_f32 + 1.0)
    q_val = tl.where(use_series, q_from_p, q_clamped)

    # Handle edge cases
    result = tl.where(zero_x & pos_a, 1.0, q_val)
    result = tl.where(zero_a & pos_x, 0.0, result)
    result = tl.where(edge_case, 0.0, result)

    return result.to(a.dtype)


def gammaincc(A, B):
    """Regularized upper incomplete gamma function Q(a, x) = Γ(a, x) / Γ(a)"""
    logger.debug("GEMS GAMMAINCC")
    return gammaincc_func(A, B)


def gammaincc_(A, B):
    """In-place version - not supported for this function"""
    raise NotImplementedError("gammaincc_ in-place operation is not supported")
