# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "INT_TO_FLOAT")])
@triton.jit
def shifted_chebyshev_polynomial_t_kernel(x, n):
    # Shifted Chebyshev polynomial of the first kind: T_n^*(x)
    # Formula: T_n^*(x) = T_n(2x-1)
    # Where T_n(y) = cos(n * arccos(y))
    # The shifted polynomial is defined on [0, 1]

    # Convert to float32 for computation, then convert back
    x_f32 = x.to(tl.float32)
    n_f32 = n.to(tl.float32)

    # Shift from [0, 1] to [-1, 1]
    x_shifted = x_f32 * 2.0 - 1.0

    # Clamp to valid range for acos to avoid numerical issues
    x_shifted = tl.where(x_shifted > 1.0, 1.0, x_shifted)
    x_shifted = tl.where(x_shifted < -1.0, -1.0, x_shifted)

    # T_n(y) = cos(n * arccos(y))
    acos_val = tl_extra_shim.acos(x_shifted)
    result = tl_extra_shim.cos(n_f32 * acos_val)

    # Convert back to original dtype
    return result.to(x.dtype)


# Kernel for scalar n (n is not a tensor)
@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "INT_TO_FLOAT")])
@triton.jit
def shifted_chebyshev_polynomial_t_kernel_scalar_n(x, n):
    # Same as above but n is a scalar
    x_f32 = x.to(tl.float32)
    n_f32 = n.to(tl.float32)

    x_shifted = x_f32 * 2.0 - 1.0

    x_shifted = tl.where(x_shifted > 1.0, 1.0, x_shifted)
    x_shifted = tl.where(x_shifted < -1.0, -1.0, x_shifted)

    acos_val = tl_extra_shim.acos(x_shifted)
    result = tl_extra_shim.cos(n_f32 * acos_val)

    return result.to(x.dtype)


def special_shifted_chebyshev_polynomial_t(x, n):
    logger.debug("GEMS SPECIAL_SHIFTED_CHEBYSHEV_POLYNOMIAL_T")
    # shifted_chebyshev_polynomial_t_cuda only supports float32
    if x.dtype not in (torch.float32,):
        raise ValueError(f"Unsupported dtype {x.dtype}, only float32 is supported")
    # Handle scalar n
    if not isinstance(n, torch.Tensor):
        return shifted_chebyshev_polynomial_t_kernel_scalar_n(x, n)
    return shifted_chebyshev_polynomial_t_kernel(x, n)


def special_shifted_chebyshev_polynomial_t_(x, n):
    logger.debug("GEMS SPECIAL_SHIFTED_CHEBYSHEV_POLYNOMIAL_T_")
    # shifted_chebyshev_polynomial_t_cuda only supports float32
    if x.dtype not in (torch.float32,):
        raise ValueError(f"Unsupported dtype {x.dtype}, only float32 is supported")
    if not isinstance(n, torch.Tensor):
        return shifted_chebyshev_polynomial_t_kernel_scalar_n(x, n, out0=x)
    return shifted_chebyshev_polynomial_t_kernel(x, n, out0=x)
