# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from flag_gems.ops.igammac import igammac, igammac_out

logger = logging.getLogger(__name__)


def special_gammaincc(a: torch.Tensor, x: torch.Tensor, *, out: torch.Tensor = None):
    """Computes the regularized upper incomplete gamma function Q(a, x).

    `aten::special_gammaincc` is the canonical schema for this function; the
    kernel itself lives in `igammac.py`, which provides an autotuned Triton
    implementation covering both the functional and the `out=` form. This
    wrapper only maps the canonical name onto that kernel.
    """
    logger.debug("GEMS SPECIAL_GAMMAINCC")
    return igammac(a, x, out=out)


def special_gammaincc_out(a: torch.Tensor, x: torch.Tensor, out: torch.Tensor):
    """`out=` variant of `special_gammaincc`, writing the result into `out`."""
    logger.debug("GEMS SPECIAL_GAMMAINCC_OUT")
    return igammac_out(a, x, out)
