# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.ops.add import add as gems_add
from flag_gems.ops.cat import cat as gems_cat
from flag_gems.ops.mul import mul as gems_mul
from flag_gems.ops.sub import sub as gems_sub
from flag_gems.ops.sum import sum_dim as gems_sum_dim
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, libtuner
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


@libentry()
@libtuner(
    configs=runtime.get_tuned_config("naive_reduction"),
    key=["M", "N"],
)
@triton.jit
def trapezoid_dx_kernel(
    y_ptr,
    out_ptr,
    dx,
    M,
    N,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    COMPUTE_DTYPE: tl.constexpr,
):
    pid = ext.program_id(0) * BLOCK_M + tl.arange(0, BLOCK_M)[:, None]
    row_mask = pid < M
    y_row = y_ptr + pid * N

    acc = tl.zeros([BLOCK_M, BLOCK_N], dtype=COMPUTE_DTYPE)
    # The trapezoidal rule sum_{i=1..N-1} 0.5*(y_i + y_{i-1}) is equivalent to a
    # single weighted pass over y where every element has weight 1 except the two
    # endpoints, which have weight 0.5. This reads each y element only once.
    for off in range(0, N, BLOCK_N):
        k = off + tl.arange(0, BLOCK_N)[None, :]
        col_mask = k < N
        mask = row_mask & col_mask
        y_k = tl.load(y_row + k, mask=mask, other=0.0).to(COMPUTE_DTYPE)
        w = tl.where((k == 0) | (k == N - 1), 0.5, 1.0)
        acc += y_k * w

    out = tl.sum(acc, axis=1)[:, None] * dx.to(COMPUTE_DTYPE)
    tl.store(out_ptr + pid, out, mask=row_mask)


@libentry()
@libtuner(
    configs=runtime.get_tuned_config("naive_reduction"),
    key=["M", "N"],
)
@triton.jit
def trapezoid_x_kernel(
    y_ptr,
    x_ptr,
    out_ptr,
    M,
    N,
    x_m_stride,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    COMPUTE_DTYPE: tl.constexpr,
):
    # Fast path used when y and x share the same length N along the integration
    # dim. sum_{i=1..N-1} 0.5*(x_i - x_{i-1})*(y_i + y_{i-1}) is rewritten as a
    # single weighted pass sum_k y_k * 0.5*(x_{k+1} - x_{k-1}), where the neighbour
    # indices are clamped at the endpoints. This reads each y element only once.
    pid = ext.program_id(0) * BLOCK_M + tl.arange(0, BLOCK_M)[:, None]
    row_mask = pid < M
    y_row = y_ptr + pid * N
    # x_m_stride is 0 when x is a 1-D spacing shared across rows, or N when x
    # provides per-row spacing (broadcast to y's shape by the wrapper).
    x_row = x_ptr + pid * x_m_stride

    acc = tl.zeros([BLOCK_M, BLOCK_N], dtype=COMPUTE_DTYPE)
    for off in range(0, N, BLOCK_N):
        k = off + tl.arange(0, BLOCK_N)[None, :]
        col_mask = k < N
        mask = row_mask & col_mask
        kp = tl.minimum(k + 1, N - 1)
        km = tl.maximum(k - 1, 0)
        y_k = tl.load(y_row + k, mask=mask, other=0.0).to(COMPUTE_DTYPE)
        x_kp = tl.load(x_row + kp, mask=mask, other=0.0).to(COMPUTE_DTYPE)
        x_km = tl.load(x_row + km, mask=mask, other=0.0).to(COMPUTE_DTYPE)
        acc += y_k * 0.5 * (x_kp - x_km)

    out = tl.sum(acc, axis=1)[:, None]
    tl.store(out_ptr + pid, out, mask=row_mask)


@libentry()
@libtuner(
    configs=runtime.get_tuned_config("naive_reduction"),
    key=["M", "N"],
)
@triton.jit
def trapezoid_x_pair_kernel(
    lpr_ptr,
    dx_ptr,
    out_ptr,
    M,
    N,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    COMPUTE_DTYPE: tl.constexpr,
):
    # Slow path for pair-space broadcasting (y and x differ in length along the
    # integration dim). lpr (y_left + y_right) and dx (x_right - x_left) are
    # already reduced by one and broadcast to the common pair shape, then flattened
    # to (M, N). Compute the inner product sum_k lpr_k * dx_k and scale by 0.5.
    pid = ext.program_id(0) * BLOCK_M + tl.arange(0, BLOCK_M)[:, None]
    row_mask = pid < M
    lpr_row = lpr_ptr + pid * N
    dx_row = dx_ptr + pid * N

    acc = tl.zeros([BLOCK_M, BLOCK_N], dtype=COMPUTE_DTYPE)
    for off in range(0, N, BLOCK_N):
        k = off + tl.arange(0, BLOCK_N)[None, :]
        col_mask = k < N
        mask = row_mask & col_mask
        lpr_k = tl.load(lpr_row + k, mask=mask, other=0.0).to(COMPUTE_DTYPE)
        dx_k = tl.load(dx_row + k, mask=mask, other=0.0).to(COMPUTE_DTYPE)
        acc += lpr_k * dx_k

    out = tl.sum(acc, axis=1)[:, None] * 0.5
    tl.store(out_ptr + pid, out, mask=row_mask)


def _normalize_dim(ndim, dim):
    # Mirror ATen's dim validation: a 0-d tensor has no dims, and out-of-range dims
    # raise IndexError with the exact same message wording.
    if ndim == 0:
        raise IndexError(f"Dimension specified as {dim} but tensor has no dimensions")
    if dim < -ndim or dim >= ndim:
        raise IndexError(
            f"Dimension out of range (expected to be in range of [{-ndim}, {ndim - 1}], "
            f"but got {dim})"
        )
    return dim if dim >= 0 else dim + ndim


def _check_bool(y, x=None):
    for name, t in (("y", y), ("x", x)):
        if t is not None and t.dtype == torch.bool:
            raise RuntimeError(
                "trapezoid: received a bool input for `x` or `y`, but bool is not supported"
            )


def _check_complex(y, x=None):
    # The Triton kernels are real-valued only. Complex inputs take the
    # device-side complex path below instead of erroring out, so ATen's
    # complex forward/backward contract is preserved.
    for name, t in (("y", y), ("x", x)):
        if t is not None and t.is_complex():
            logger.debug("GEMS TRAPEZOID_COMPLEX")


def _is_complex(y, x=None):
    return y.is_complex() or (x is not None and x.is_complex())


def _complex_pair_out(y, x, dim):
    """Device-side complex trapezoid over the x sample points.

    sum_k (y[k] + y[k+1]) / 2 * (x[k+1] - x[k]) with ATen-compatible
    broadcasting between y and x along `dim`. FlagGems' add/sub/mul kernels
    support complex dtypes; the final reduction decomposes through
    view_as_real because the reduction kernels are real-valued.
    """
    dim = _normalize_dim(y.dim(), dim)
    out_dtype = _result_dtype(y, x)
    y = y.to(out_dtype)
    x = x.to(out_dtype)

    x_viewed = _view_x(x, y, dim)
    N = y.shape[dim]

    if N == x_viewed.shape[dim] and N <= 1:
        # A single (or absent) sample point spans no interval.
        full_shape = torch.broadcast_shapes(y.shape, x_viewed.shape)
        out_shape = full_shape[:dim] + full_shape[dim + 1 :]
        return torch.zeros(out_shape, dtype=out_dtype, device=y.device)

    # Pair space: (y_left + y_right) * (x_right - x_left) / 2, then sum over dim.
    N_pair = N - 1
    Nx_pair = x_viewed.shape[dim] - 1
    yl = y.narrow(dim, 0, N_pair)
    yr = y.narrow(dim, 1, N_pair)
    xl = x_viewed.narrow(dim, 0, Nx_pair)
    xr = x_viewed.narrow(dim, 1, Nx_pair)
    lpr = gems_add(yl, yr)
    dx = gems_sub(xr, xl)

    pair_shape = torch.broadcast_shapes(lpr.shape, dx.shape)
    lpr_b = lpr.broadcast_to(pair_shape)
    dx_b = dx.broadcast_to(pair_shape)
    # Scale through a device tensor so the complex-typed gemsmul kernel applies
    # (a python scalar would downcast to the real promotion path).
    half = torch.tensor(0.5, dtype=out_dtype, device=lpr_b.device)  # noqa: E501
    prod = gems_mul(gems_mul(lpr_b, dx_b), half)

    # Complex sums decompose into real and imaginary parts; the FlagGems
    # reduction kernels are real-valued. view_as_real appends the (..., 2)
    # real/imag axis last, which does not disturb the earlier `dim` indices,
    # so reducing `dim` on the real view and recombining is exact.
    prod_r = torch.view_as_real(prod)
    total = gems_sum_dim(prod_r.contiguous(), dim=[dim])
    return torch.view_as_complex(total.contiguous())


def _trapezoid_x_complex(y, x, dim):
    return _complex_pair_out(y, x, dim)


def _validate_dx(dx):
    # ATen rejects boolean and complex scalar dx ("we only support dx as a real
    # number"). float(True) would silently coerce to 1.0, and complex would drop
    # the imaginary part, so validate before any conversion.
    if isinstance(dx, bool):
        raise RuntimeError("trapezoid: Currently, we only support dx as a real number.")
    if isinstance(dx, complex):
        raise RuntimeError("trapezoid: Currently, we only support dx as a real number.")
    if isinstance(dx, torch.Tensor):
        if dx.dtype == torch.bool or dx.is_complex():
            raise RuntimeError(
                "trapezoid: Currently, we only support dx as a real number."
            )


def _result_dtype(y, x=None):
    # ATen promotes y and x via result_type, but a pure-integer result is computed
    # in float32 (matching ATen's do_trapezoid, which returns float32 for int inputs).
    # Complex results are preserved as-is (ATen keeps complex64/complex128).
    if x is None:
        dt = y.dtype
    else:
        dt = torch.result_type(y, x)
    if not dt.is_floating_point and not dt.is_complex:
        dt = torch.float32
    return dt


def _compute_dtype(dtype):
    return tl.float64 if dtype == torch.float64 else tl.float32


def _zeros_shape(shape, dim):
    return shape[:dim] + shape[dim + 1 :]


def _view_x(x, y, dim):
    # Align x to y's dimensionality following ATen:
    #   - a 1-D x is placed along `dim` (all other dims are 1);
    #   - otherwise x is right-aligned by padding leading 1s to match y.dim().
    if x.dim() == 1:
        if x.shape[0] != y.shape[dim]:
            raise RuntimeError(
                "trapezoid: There must be one `x` value for each sample point"
            )
        new_sizes = [1] * y.dim()
        new_sizes[dim] = x.shape[0]
        return x.view(new_sizes)
    if x.dim() < y.dim():
        return x.view([1] * (y.dim() - x.dim()) + list(x.shape))
    return x


def _prepare(y, dim):
    # Move the reduction dim to the innermost position and make it contiguous
    # so each row is a contiguous span of length N.
    y2 = y.movedim(dim, -1).contiguous()
    out_shape = y2.shape[:-1]
    N = y2.shape[-1] if y2.ndim > 0 else 1
    y2 = y2.reshape(-1, N)
    M = y2.shape[0]
    return y2, M, N, out_shape


def _sum_dim_any(grad, dim, keepdim=False):
    """FlagGems sum_dim that also accepts complex tensors.

    The reduction kernels are real-valued, so a complex tensor is reduced by
    splitting it into its real/imaginary parts (view_as_real appends that axis
    last, so `dim` indices stay valid), summing each, and recombining.
    """
    if not grad.is_complex():
        return gems_sum_dim(grad, dim=dim, keepdim=keepdim)
    real = torch.view_as_real(grad)  # (..., 2)
    summed = gems_sum_dim(real, dim=dim, keepdim=keepdim)
    return torch.view_as_complex(summed.contiguous())


def _unbroadcast(grad, target_shape):
    # Sum a broadcast gradient back into the (possibly smaller) target shape.
    # Reductions route through the FlagGems sum_dim kernel (host-function
    # convention: no native PyTorch compute in the wrapper).
    while grad.dim() > len(target_shape):
        grad = _sum_dim_any(grad, dim=[0])
    for i, s in enumerate(target_shape):
        if s == 1 and grad.shape[i] != 1:
            grad = _sum_dim_any(grad, dim=[i], keepdim=True)
    return grad.reshape(target_shape)


def _cat_any(parts, dim):
    """FlagGems cat that also accepts complex tensors (via the real view)."""
    if not parts[0].is_complex():
        return gems_cat(parts, dim)
    reals = [torch.view_as_real(p) for p in parts]
    return torch.view_as_complex(gems_cat(reals, dim).contiguous())


def _accumulate_plus(grad_diff, dim):
    # Given grad wrt (y[k] + y[k+1]) over the pair axis, recover grad wrt y[k] via
    # grad_y[k] = grad_diff[k] + grad_diff[k-1] (endpoints clamped). The concat and
    # element-wise sum route through FlagGems kernels (host-function convention).
    pad = torch.zeros_like(grad_diff.narrow(dim, 0, 1))
    return gems_add(_cat_any([pad, grad_diff], dim), _cat_any([grad_diff, pad], dim))


def _accumulate_minus(grad_diff, dim):
    # Given grad wrt (x[k+1] - x[k]) over the pair axis, recover grad wrt x[k] via
    # grad_x[k] = grad_diff[k-1] - grad_diff[k] (endpoints clamped). The concat and
    # element-wise difference route through FlagGems kernels (host-function convention).
    pad = torch.zeros_like(grad_diff.narrow(dim, 0, 1))
    return gems_sub(_cat_any([pad, grad_diff], dim), _cat_any([grad_diff, pad], dim))


def _trapezoid_dx_impl(y, dx_val, dim):
    dim = _normalize_dim(y.dim(), dim)

    if y.shape[dim] == 0:
        out_dtype = _result_dtype(y)
        return torch.zeros(_zeros_shape(y.shape, dim), dtype=out_dtype, device=y.device)

    _check_bool(y)
    _check_complex(y)
    out_dtype = _result_dtype(y)

    y2, M, N, out_shape = _prepare(y, dim)

    if N <= 1:
        # A single point spans no interval, so the integral is zero.
        return torch.zeros(out_shape, dtype=out_dtype, device=y.device)

    out = torch.empty((M,), dtype=out_dtype, device=y.device)
    if M > 0:
        grid = lambda meta: (triton.cdiv(M, meta["BLOCK_M"]),)
        with torch_device_fn.device(y.device):
            trapezoid_dx_kernel[grid](
                y2, out, dx_val, M, N, COMPUTE_DTYPE=_compute_dtype(out_dtype)
            )
    return out.reshape(out_shape)


def _trapezoid_x_impl(y, x, dim):
    dim = _normalize_dim(y.dim(), dim)

    _check_bool(y, x)
    if _is_complex(y, x):
        return _trapezoid_x_complex(y, x, dim)

    out_dtype = _result_dtype(y, x)

    # Validate x against ATen's contract before the N <= 1 / empty-input early
    # returns: a 1-D x must provide one sample point per integration point.
    # ATen itself only rejects a mismatch when the integration dim is non-empty
    # (an empty dim integrates to zero regardless of x), so mirror that by
    # checking the length up front and skipping the check for size 0.
    if y.shape[dim] == 0:
        return torch.zeros(_zeros_shape(y.shape, dim), dtype=out_dtype, device=y.device)

    x_viewed = _view_x(x, y, dim)

    N = y.shape[dim]
    Nx = x_viewed.shape[dim]

    if N == Nx:
        # Fast path: y and x share the integration length, so the weighted-sum
        # kernel applies directly once the non-dim axes are broadcast together.
        full_shape = torch.broadcast_shapes(y.shape, x_viewed.shape)
        out_shape = full_shape[:dim] + full_shape[dim + 1 :]

        if N <= 1:
            # A single sample point spans no interval, so the integral is zero.
            return torch.zeros(out_shape, dtype=out_dtype, device=y.device)

        y_b = y.broadcast_to(full_shape)
        y2 = y_b.movedim(dim, -1).contiguous().reshape(-1, N)
        M = y2.shape[0]

        if M == 0:
            return torch.zeros(out_shape, dtype=out_dtype, device=y.device)

        if x.dim() == 1:
            # 1-D spacing shared across every row.
            x2 = x.contiguous()
            x_m_stride = 0
        else:
            x_b = x_viewed.broadcast_to(full_shape)
            x2 = x_b.movedim(dim, -1).contiguous().reshape(-1, N)
            x_m_stride = N

        out = torch.empty((M,), dtype=out_dtype, device=y.device)
        grid = lambda meta: (triton.cdiv(M, meta["BLOCK_M"]),)
        with torch_device_fn.device(y.device):
            trapezoid_x_kernel[grid](
                y2, x2, out, M, N, x_m_stride, COMPUTE_DTYPE=_compute_dtype(out_dtype)
            )
        return out.reshape(out_shape)

    # Slow path: pair-space broadcasting (N != Nx). Reproduce ATen's
    # ((y_left + y_right) * (x_right - x_left)).sum(dim) / 2 exactly, computing the
    # intermediate differences in the compute dtype to preserve precision. The
    # element-wise sum/difference route through the FlagGems add/sub kernels
    # (host-function convention: no native PyTorch compute in the wrapper).
    compute_dtype = torch.float64 if out_dtype == torch.float64 else torch.float32
    left = y.narrow(dim, 0, N - 1)
    right = y.narrow(dim, 1, N - 1)
    lpr = gems_add(left.to(compute_dtype), right.to(compute_dtype))

    x_left = x_viewed.narrow(dim, 0, Nx - 1)
    x_right = x_viewed.narrow(dim, 1, Nx - 1)
    dx = gems_sub(x_right.to(compute_dtype), x_left.to(compute_dtype))

    pair_shape = torch.broadcast_shapes(lpr.shape, dx.shape)
    P = pair_shape[dim]
    out_shape = pair_shape[:dim] + pair_shape[dim + 1 :]

    if P == 0:
        # An empty pair axis yields a zero integral.
        return torch.zeros(out_shape, dtype=out_dtype, device=y.device)

    lpr_b = lpr.broadcast_to(pair_shape)
    dx_b = dx.broadcast_to(pair_shape)

    lpr_2d = lpr_b.movedim(dim, -1).contiguous().reshape(-1, P)
    dx_2d = dx_b.movedim(dim, -1).contiguous().reshape(-1, P)
    M = lpr_2d.shape[0]

    if M == 0:
        return torch.zeros(out_shape, dtype=out_dtype, device=y.device)

    out = torch.empty((M,), dtype=out_dtype, device=y.device)
    grid = lambda meta: (triton.cdiv(M, meta["BLOCK_M"]),)
    with torch_device_fn.device(y.device):
        trapezoid_x_pair_kernel[grid](
            lpr_2d, dx_2d, out, M, P, COMPUTE_DTYPE=_compute_dtype(out_dtype)
        )
    return out.reshape(out_shape)


class _TrapezoidDX(torch.autograd.Function):
    @staticmethod
    def forward(ctx, y, dx, dim):
        _validate_dx(dx)
        ctx.dx_val = dx.item() if isinstance(dx, torch.Tensor) else float(dx)
        ctx.dim = _normalize_dim(y.dim(), dim)
        ctx.save_for_backward(y)
        return _trapezoid_dx_impl(y, ctx.dx_val, dim)

    @staticmethod
    def backward(ctx, grad_out):
        (y,) = ctx.saved_tensors
        dx_val = ctx.dx_val
        dim = ctx.dim
        N = y.shape[dim]
        if N <= 1:
            grad_y = torch.zeros_like(y)
        else:
            # out = dx * sum_k w[k] * y[k] with w = [0.5, 1, ..., 1, 0.5], so
            # d out / d y[k] = dx * w[k]. torch.ones/weight filling is host-side
            # constant setup (not tensor compute); the element-wise scaling that
            # touches the gradient routes through the FlagGems mul kernel
            # (host-function convention: no native Tensor arithmetic).
            compute_dtype = torch.float64 if y.dtype == torch.float64 else torch.float32
            weight = torch.ones(N, device=y.device, dtype=compute_dtype)
            weight[0] = 0.5
            weight[-1] = 0.5
            grad_scaled = gems_mul(grad_out.to(compute_dtype).unsqueeze(dim), weight)
            grad_y = gems_mul(grad_scaled, dx_val).to(y.dtype)
        return grad_y, None, None


class _TrapezoidX(torch.autograd.Function):
    @staticmethod
    def forward(ctx, y, x, dim):
        dim = _normalize_dim(y.dim(), dim)
        ctx.dim = dim
        ctx.x_shape = x.shape
        ctx.save_for_backward(y, x)
        return _trapezoid_x_impl(y, x, dim)

    @staticmethod
    def backward(ctx, grad_out):
        y, x = ctx.saved_tensors
        dim = ctx.dim
        x_shape = ctx.x_shape

        N = y.shape[dim]
        if N <= 1:
            # N == 0 would pass a negative length to narrow, and N == 1 leaves an
            # empty pair axis for _accumulate_*; either way a single (or absent)
            # sample point spans no interval, so both gradients are zero (ATen).
            return torch.zeros_like(y), torch.zeros_like(x), None

        # Complex autograd follows the Wirtinger convention: each input's
        # gradient is conj(d out / d input), matching ATen. In the analytic
        # chain below the conjugate must therefore apply to the *other*
        # complex factors while the upstream grad stays plain:
        #   grad_y[i,k] = grad_out[i] * conj(w[k] * dx[k])
        #   grad_x[k]  = sum_i grad_out[i] * conj(±0.5 * lpr[i,k])
        # (real tensors are unaffected by conjugation).
        complex_case = grad_out.is_complex() or y.is_complex() or x.is_complex()

        x_viewed = _view_x(x, y, dim)

        lpr = gems_add(y.narrow(dim, 0, N - 1), y.narrow(dim, 1, N - 1))

        Nx = x_viewed.shape[dim]
        x_left = x_viewed.narrow(dim, 0, Nx - 1)
        x_right = x_viewed.narrow(dim, 1, Nx - 1)
        dx = gems_sub(x_right, x_left)

        pair_shape = torch.broadcast_shapes(lpr.shape, dx.shape)
        lpr_b = lpr.broadcast_to(pair_shape)
        dx_b = dx.broadcast_to(pair_shape)

        # out = (lpr * dx).sum(dim) / 2; route the element-wise products through
        # the FlagGems mul kernel (host-function convention: no native compute).
        grad_pair = gems_mul(grad_out.unsqueeze(dim), 0.5)
        if complex_case:
            grad_lpr_b = gems_mul(grad_pair, dx_b.conj().resolve_conj())
            grad_dx_b = gems_mul(grad_pair, lpr_b.conj().resolve_conj())
        else:
            grad_lpr_b = gems_mul(grad_pair, dx_b)
            grad_dx_b = gems_mul(grad_pair, lpr_b)

        grad_lpr = _unbroadcast(grad_lpr_b, lpr.shape)
        grad_dx = _unbroadcast(grad_dx_b, dx.shape)

        grad_y = _accumulate_plus(grad_lpr, dim)
        grad_x_viewed = _accumulate_minus(grad_dx, dim)
        grad_x = grad_x_viewed.view(x_shape)

        return grad_y, grad_x, None


def trapezoid(y, dx=1, dim=-1):
    logger.debug("GEMS TRAPEZOID")
    _validate_dx(dx)
    if torch.is_grad_enabled() and y.requires_grad:
        return _TrapezoidDX.apply(y, dx, dim)
    dx_val = dx.item() if isinstance(dx, torch.Tensor) else float(dx)
    return _trapezoid_dx_impl(y, dx_val, dim)


def trapezoid_x(y, x, dim=-1):
    logger.debug("GEMS TRAPEZOID_X")
    if torch.is_grad_enabled() and (y.requires_grad or x.requires_grad):
        return _TrapezoidX.apply(y, x, dim)
    return _trapezoid_x_impl(y, x, dim)
