# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry, tl_extra_shim
from flag_gems.utils import triton_lang_extension as ext

_pow = tl_extra_shim.pow
logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def vander_kernel(
    x_ptr,
    out_ptr,
    M: tl.constexpr,
    N: tl.constexpr,
    increasing: tl.constexpr,
    is_float: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """
    Kernel for generating Vandermonde matrix.
    For each element x[i], generates row [x[i]^p0, x[i]^p1, ..., x[i]^p(N-1)]
    where powers depend on the increasing flag.
    """
    pid_m = ext.program_id(0)
    pid_n = ext.program_id(1)

    # Compute row and column indices
    row_start = pid_m * BLOCK_M
    col_start = pid_n * BLOCK_N

    rows = row_start + tl.arange(0, BLOCK_M)
    cols = col_start + tl.arange(0, BLOCK_N)

    # Load x values for this block of rows
    mask_m = rows < M
    x_vals = tl.load(x_ptr + rows, mask=mask_m, other=0.0)

    # Compute output for each (row, col) pair
    # Broadcasting: x_vals is [BLOCK_M], cols is [BLOCK_N]
    # Need to expand to [BLOCK_M, BLOCK_N]
    x_expanded = x_vals[:, None]  # [BLOCK_M, 1]
    cols_expanded = cols[None, :]  # [1, BLOCK_N]

    # Compute powers based on increasing flag
    if increasing:
        powers = cols_expanded  # x^0, x^1, x^2, ...
    else:
        powers = N - 1 - cols_expanded  # x^(N-1), x^(N-2), ..., x^0

    # Compute x^power for each element
    # Convert to float32 for computation to ensure accurate pow
    x_f32 = x_expanded.to(tl.float32)
    powers_f32 = powers.to(tl.float32)
    result_f32 = _pow(x_f32, powers_f32)

    # For integer dtypes, round to fix floating point errors (e.g., 5^2 = 24.999...)
    # For float dtypes, keep the result as-is
    if is_float:
        result = result_f32
    else:
        result = tl.math.floor(result_f32 + 0.5)

    # Store results
    mask_n = cols_expanded < N
    mask = mask_m[:, None] & mask_n
    out_offset = rows[:, None] * N + cols_expanded
    tl.store(out_ptr + out_offset, result, mask=mask)


def vander(x, N=None, increasing=False):
    """
    Generates a Vandermonde matrix.

    Args:
        x: 1-D input tensor
        N: Number of columns in the output (default: len(x))
        increasing: Order of powers (default: False, decreasing powers)

    Returns:
        Vandermonde matrix of shape (len(x), N)
    """
    logger.debug("GEMS VANDER")

    # Validate input
    if x.ndim != 1:
        raise ValueError(f"x must be a 1-D tensor, got {x.ndim}-D")

    M = x.shape[0]
    if N is None:
        N = M

    # Handle edge case: empty input
    if M == 0 or N == 0:
        return torch.empty((M, N), dtype=x.dtype, device=x.device)

    # Allocate output
    out = torch.empty((M, N), dtype=x.dtype, device=x.device)

    # Check if dtype is floating point
    is_float = x.dtype in [torch.float16, torch.bfloat16, torch.float32, torch.float64]

    # Launch kernel with 2D grid
    BLOCK_M = 32
    BLOCK_N = 32
    grid = (triton.cdiv(M, BLOCK_M), triton.cdiv(N, BLOCK_N))

    vander_kernel[grid](
        x,
        out,
        M=M,
        N=N,
        increasing=increasing,
        is_float=is_float,
        BLOCK_M=BLOCK_M,
        BLOCK_N=BLOCK_N,
    )

    return out
