# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

import flag_gems

logger = logging.getLogger(__name__)


@triton.jit
def zero_kernel(
    out_ptr,  # *Pointer* to tensor to be zeroed
    n_elements,  # Number of elements
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    # Create a zero value with the correct dtype using a dummy load to infer dtype
    dummy = tl.load(out_ptr + offsets, mask=mask, other=0)
    z = tl.zeros([BLOCK_SIZE], dtype=dummy.dtype)
    tl.store(out_ptr + offsets, z, mask=mask)


def _launch_zero_kernel(tensor: torch.Tensor):
    assert isinstance(tensor, torch.Tensor), "Expected a torch.Tensor"
    if tensor.device.type != flag_gems.device:
        raise ValueError(f"Tensor must be on {flag_gems.device} device")
    assert tensor.is_contiguous(), "Tensor must be contiguous"
    assert tensor.numel() >= 0
    n_elements = tensor.numel()
    if n_elements == 0:
        return tensor
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    zero_kernel[grid](tensor, n_elements, BLOCK_SIZE=1024)
    return tensor


def zero(self):
    logger.debug("GEMS ZERO")
    target = self
    return _launch_zero_kernel(target)


def zero_out(self, *, out):
    logger.debug("GEMS ZERO_OUT")
    return _launch_zero_kernel(out)
