# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils.random_utils import (
    philox_backend_seed_offset,
    uint_to_uniform_float,
)

logger = logging.getLogger(f'flag_gems.runtime._ascend.ops.{__name__.split(".")[-1]}')


@triton.heuristics(runtime.get_heuristic_config("bernoulli"))
@triton.jit(do_not_specialize=["philox_seed", "philox_offset", "N"])
def bernoulli_kernel(
    out_ptr,
    prob_ptr,
    N,
    philox_seed,
    philox_offset,
    UNROLL: tl.constexpr,
    BLOCK: tl.constexpr,
):
    n_workers = tl.num_programs(0)
    pid = tl.program_id(0)
    n_tasks = tl.cdiv(N, BLOCK * UNROLL)
    tasks_per_worker = tl.cdiv(n_tasks, n_workers)

    for task_index in range(tasks_per_worker):
        task_id = pid + task_index * n_workers
        philox_seed = philox_seed.to(tl.int64)
        philox_offset_64 = philox_offset.to(tl.int64)
        c0 = (philox_offset_64 & 0xFFFFFFFF).to(tl.uint32)
        c1 = ((philox_offset_64 >> 32) & 0xFFFFFFFF).to(tl.uint32)
        i4 = task_id * BLOCK + tl.arange(0, BLOCK)
        c0 += i4
        _O = c0 * 0
        r0, r1, r2, r3 = tl.philox(philox_seed, c0, c1, _O, _O)

        f0 = uint_to_uniform_float(r0)
        f1 = uint_to_uniform_float(r1)
        f2 = uint_to_uniform_float(r2)
        f3 = uint_to_uniform_float(r3)

        start = task_id.to(tl.int64) * BLOCK * UNROLL
        off_0 = start + tl.arange(0, BLOCK)
        prob_0 = tl.load(prob_ptr + off_0, mask=off_0 < N)
        out_0 = prob_0.to(tl.float32) > f0
        tl.store(out_ptr + off_0, out_0, mask=off_0 < N, eviction_policy="evict_first")

        off_1 = off_0 + BLOCK
        prob_1 = tl.load(prob_ptr + off_1, mask=off_1 < N)
        out_1 = prob_1.to(tl.float32) > f1
        tl.store(out_ptr + off_1, out_1, mask=off_1 < N, eviction_policy="evict_first")

        off_2 = off_1 + BLOCK
        prob_2 = tl.load(prob_ptr + off_2, mask=off_2 < N)
        out_2 = prob_2.to(tl.float32) > f2
        tl.store(out_ptr + off_2, out_2, mask=off_2 < N, eviction_policy="evict_first")

        off_3 = off_2 + BLOCK
        prob_3 = tl.load(prob_ptr + off_3, mask=off_3 < N)
        out_3 = prob_3.to(tl.float32) > f3
        tl.store(out_ptr + off_3, out_3, mask=off_3 < N, eviction_policy="evict_first")


@triton.heuristics(runtime.get_heuristic_config("bernoulli"))
@triton.jit(do_not_specialize=["philox_seed", "philox_offset", "N"])
def bernoulli_scalar_kernel(
    out_ptr,
    N,
    p,
    EPS,
    philox_seed,
    philox_offset,
    UNROLL: tl.constexpr,
    BLOCK: tl.constexpr,
):
    n_workers = tl.num_programs(0)
    pid = tl.program_id(0)
    n_tasks = tl.cdiv(N, BLOCK * UNROLL)
    tasks_per_worker = tl.cdiv(n_tasks, n_workers)

    for task_index in range(tasks_per_worker):
        task_id = pid + task_index * n_workers
        philox_seed = philox_seed.to(tl.int64)
        philox_offset_64 = philox_offset.to(tl.int64)
        c0 = (philox_offset_64 & 0xFFFFFFFF).to(tl.uint32)
        c1 = ((philox_offset_64 >> 32) & 0xFFFFFFFF).to(tl.uint32)
        i4 = task_id * BLOCK + tl.arange(0, BLOCK)
        c0 += i4
        _O = c0 * 0
        r0, r1, r2, r3 = tl.philox(philox_seed, c0, c1, _O, _O)

        f0 = uint_to_uniform_float(r0)
        f1 = uint_to_uniform_float(r1)
        f2 = uint_to_uniform_float(r2)
        f3 = uint_to_uniform_float(r3)

        out_0 = f0 < (p + EPS)
        out_1 = f1 < (p + EPS)
        out_2 = f2 < (p + EPS)
        out_3 = f3 < (p + EPS)

        start = task_id.to(tl.int64) * BLOCK * UNROLL
        off_0 = start + tl.arange(0, BLOCK)
        tl.store(out_ptr + off_0, out_0, mask=off_0 < N, eviction_policy="evict_first")
        off_1 = off_0 + BLOCK
        tl.store(out_ptr + off_1, out_1, mask=off_1 < N, eviction_policy="evict_first")
        off_2 = off_1 + BLOCK
        tl.store(out_ptr + off_2, out_2, mask=off_2 < N, eviction_policy="evict_first")
        off_3 = off_2 + BLOCK
        tl.store(out_ptr + off_3, out_3, mask=off_3 < N, eviction_policy="evict_first")


def bernoulli(self, *, generator=None):
    logger.debug("GEMS_ASCEND BERNOULLI")
    N = self.numel()
    UNROLL = 4
    device = self.device

    def grid_fn(meta):
        grid = triton.cdiv(N, meta["BLOCK"] * UNROLL)
        grid = grid if grid < 240 else 240
        return (grid,)

    increment = triton.cdiv(N, UNROLL)
    philox_seed, philox_offset = philox_backend_seed_offset(increment)

    out = torch.empty_like(self, dtype=self.dtype)
    with torch_device_fn.device(device):
        bernoulli_kernel[grid_fn](out, self, N, philox_seed, philox_offset, UNROLL)
    return out


def bernoulli_p(self, p, *, generator=None):
    logger.debug("GEMS_ASCEND BERNOULLI P")
    N = self.numel()
    UNROLL = 4
    device = self.device
    dtype = self.dtype
    eps = torch.finfo(dtype).eps

    def grid_fn(meta):
        grid = triton.cdiv(N, meta["BLOCK"] * UNROLL)
        grid = grid if grid < 240 else 240
        return (grid,)

    increment = triton.cdiv(N, UNROLL)
    philox_seed, philox_offset = philox_backend_seed_offset(increment)

    out = torch.empty_like(self, dtype=self.dtype)
    with torch_device_fn.device(device):
        bernoulli_scalar_kernel[grid_fn](
            out, N, p, eps, philox_seed, philox_offset, UNROLL
        )
    return out
