# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(f'flag_gems.runtime._ascend.ops.{__name__.split(".")[-1]}')


@libentry()
@triton.jit
def _binary_cross_entropy_elementwise_kernel(
    x_ptr,
    y_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0.0)

    xf = x.to(tl.float32)
    yf = y.to(tl.float32)

    log_x = tl.log(xf)
    log_1mx = tl.log(1.0 - xf)
    result = -(yf * log_x + (1.0 - yf) * log_1mx)

    tl.store(out_ptr + offsets, result, mask=mask)


@libentry()
@triton.jit
def _binary_cross_entropy_sum_kernel(
    x_ptr,
    y_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0.0)

    xf = x.to(tl.float32)
    yf = y.to(tl.float32)

    log_x = tl.log(xf)
    log_1mx = tl.log(1.0 - xf)
    result = -(yf * log_x + (1.0 - yf) * log_1mx)
    result = tl.where(mask, result, 0.0)

    acc = tl.sum(result, axis=0)
    tl.atomic_add(out_ptr, acc)


@libentry()
@triton.jit
def _binary_cross_entropy_weighted_kernel(
    x_ptr,
    y_ptr,
    w_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0.0)
    w = tl.load(w_ptr + offsets, mask=mask, other=0.0)

    xf = x.to(tl.float32)
    yf = y.to(tl.float32)
    wf = w.to(tl.float32)

    log_x = tl.log(xf)
    log_1mx = tl.log(1.0 - xf)
    result = -wf * (yf * log_x + (1.0 - yf) * log_1mx)

    tl.store(out_ptr + offsets, result, mask=mask)


@libentry()
@triton.jit
def _binary_cross_entropy_weighted_sum_kernel(
    x_ptr,
    y_ptr,
    w_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0.0)
    w = tl.load(w_ptr + offsets, mask=mask, other=0.0)

    xf = x.to(tl.float32)
    yf = y.to(tl.float32)
    wf = w.to(tl.float32)

    log_x = tl.log(xf)
    log_1mx = tl.log(1.0 - xf)
    result = -wf * (yf * log_x + (1.0 - yf) * log_1mx)
    result = tl.where(mask, result, 0.0)

    acc = tl.sum(result, axis=0)
    tl.atomic_add(out_ptr, acc)


def _normalize_reduction(reduction):
    if isinstance(reduction, str):
        r = reduction.lower()
        if r == "none":
            return 0
        if r == "mean":
            return 1
        if r == "sum":
            return 2
        raise ValueError(f"Invalid reduction: {reduction}")
    if isinstance(reduction, int):
        if reduction in (0, 1, 2):
            return reduction
        raise ValueError(f"Invalid reduction int: {reduction}")
    raise ValueError(f"Unsupported reduction type: {type(reduction)}")


def binary_cross_entropy(self, target, weight=None, reduction=1):
    logger.debug("ASCEND GEMS BINARY_CROSS_ENTROPY")
    red = _normalize_reduction(reduction)
    n_elements = self.numel()
    dtype = self.dtype

    if weight is not None:
        if weight.numel() == 1:
            weight = weight.expand_as(self)
        elif not weight.is_contiguous():
            weight = weight.contiguous()

    if red == 0:
        out = torch.empty_like(self)
        if n_elements == 0:
            return out
        BLOCK_SIZE = 1024
        grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
        with torch_device_fn.device(self.device):
            if weight is not None:
                _binary_cross_entropy_weighted_kernel[grid](
                    self, target, weight, out, n_elements, BLOCK_SIZE=BLOCK_SIZE
                )
            else:
                _binary_cross_entropy_elementwise_kernel[grid](
                    self, target, out, n_elements, BLOCK_SIZE=BLOCK_SIZE
                )
        return out
    else:
        if n_elements == 0:
            if red == 2:
                return torch.zeros((), device=self.device, dtype=dtype)
            else:
                return torch.full((), float("nan"), device=self.device, dtype=dtype)
        tmp_sum = torch.zeros((), device=self.device, dtype=torch.float32)
        BLOCK_SIZE = 1024
        grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
        with torch_device_fn.device(self.device):
            if weight is not None:
                _binary_cross_entropy_weighted_sum_kernel[grid](
                    self, target, weight, tmp_sum, n_elements, BLOCK_SIZE=BLOCK_SIZE
                )
            else:
                _binary_cross_entropy_sum_kernel[grid](
                    self, target, tmp_sum, n_elements, BLOCK_SIZE=BLOCK_SIZE
                )
        if red == 2:
            return tmp_sum.to(dtype=dtype)
        else:
            if weight is not None:
                w_sum = weight.to(torch.float32).sum()
                if w_sum == 0:
                    return tmp_sum.to(dtype=dtype)
                return (tmp_sum / w_sum).to(dtype=dtype)
            else:
                return (tmp_sum / float(n_elements)).to(dtype=dtype)
