name: Sync docs branch
on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-flaggems
        with:
          checkout_ref: gh-pages
          checkout_submodules: recursive
          checkout_fetch_depth: "0"

      - id: rebase
        run: |
          git rebase master
          git push -u origin gh-pages -f
